// ===========================================================================
// lululemon — Retail / Fashion (technical apparel) client instance
// Representative campaign data + a full insight list + market news.
// Performance-heavy DTC e-commerce; "conversions" are online orders, revenue is
// AOV-driven. Illustrative demo figures grounded in the real category lineup,
// audiences, and a brand/performance/community agency structure.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, PURPLE, MUTED, GOLD, GRID } from '../insight-visual-types';

export const LULULEMON_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — BRAND (In-House Brand Studio) ──
  { id: 'lulu-womens-brand', name: "Women's — Feel Your Best Brand Hero",
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-womens',
    audiences: ['lulu-yogis', 'lulu-everyday'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'instagram', 'tiktok', 'ooh'], geos: ['national'], budgetMultiplier: 1.30,
    plannedBudget: 9_600_000, revPerConvRange: [128, 240], cvrModifier: 1.15, cplCalibration: 0.72, revTrend: 0.0005 },
  { id: 'lulu-mens-grow', name: "Men's — Beyond the Studio Growth",
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-mens',
    audiences: ['lulu-mens-perf', 'lulu-everyday'], objective: 'consideration', status: 'live',
    channels: ['instagram', 'tiktok', 'google-search', 'ttd'], geos: ['national', 'ontario'], budgetMultiplier: 1.05,
    plannedBudget: 6_800_000, revPerConvRange: [118, 220], cvrModifier: 1.10, cplCalibration: 0.74, revTrend: 0.0006 },
  { id: 'lulu-footwear-launch', name: 'Footwear — Next Step Launch',
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-footwear',
    audiences: ['lulu-runners', 'lulu-genz'], objective: 'awareness', status: 'live',
    channels: ['tiktok', 'instagram', 'ctv', 'ttd'], geos: ['national'], budgetMultiplier: 1.15,
    plannedBudget: 7_400_000, revPerConvRange: [140, 250], cvrModifier: 1.05, cplCalibration: 0.70, revTrend: 0.0007 },

  // ── TIER 2 — PERFORMANCE MEDIA ──
  { id: 'lulu-align-performance', name: 'Align — Always-On Performance',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-align',
    audiences: ['lulu-yogis', 'lulu-everyday', 'lulu-members'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'instagram', 'facebook', 'ttd'], geos: ['national'], budgetMultiplier: 1.20,
    plannedBudget: 8_200_000, revPerConvRange: [110, 198], cvrModifier: 1.30, cplCalibration: 0.80, revTrend: 0.0006 },
  { id: 'lulu-genz-tiktok', name: 'Gen-Z — TikTok Entry Acquisition',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-womens',
    audiences: ['lulu-genz'], objective: 'conversion', status: 'live',
    channels: ['tiktok', 'instagram', 'google-search'], geos: ['national', 'bc'], budgetMultiplier: 0.95,
    plannedBudget: 5_200_000, revPerConvRange: [96, 176], cvrModifier: 1.20, cplCalibration: 0.78, revTrend: 0.0006 },
  { id: 'lulu-winback', name: 'Lapsed — 90-Day Win-Back',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-accessories',
    audiences: ['lulu-lapsed'], objective: 'retention', status: 'live',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.70,
    plannedBudget: 2_800_000, revPerConvRange: [104, 188], cvrModifier: 1.25, cplCalibration: 0.82, revTrend: 0.0005 },

  // ── TIER 3 — COMMUNITY & RETAIL ──
  { id: 'lulu-membership-community', name: 'Membership — Community & Studio Sign-Ups',
    enterprise: 'lululemon', division: 'tier-3', agency: 'lulu-community', productLine: 'lulu-membership',
    audiences: ['lulu-members', 'lulu-yogis'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'google-search', 'facebook'], geos: ['ontario', 'bc'], budgetMultiplier: 0.65,
    plannedBudget: 2_600_000, revPerConvRange: [60, 130], cvrModifier: 1.15, cplCalibration: 0.84, revTrend: 0.0005 },
  { id: 'lulu-runners-local', name: 'Run Club — Local Community Activation',
    enterprise: 'lululemon', division: 'tier-3', agency: 'lulu-community', productLine: 'lulu-footwear',
    audiences: ['lulu-runners', 'lulu-members'], objective: 'consideration', status: 'paused',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['ontario', 'alberta'], budgetMultiplier: 0.60,
    plannedBudget: 2_200_000, revPerConvRange: [130, 236], cvrModifier: 1.00, cplCalibration: 0.76, revTrend: 0.0006 },
];

export const LULULEMON_NEWS: NewsItem[] = [
  { id: 'news-lulu-footwear-momentum', title: 'Athletic-Footwear Demand Among Women Tracking Up in Canada — Newcomer Brands Taking Share from Incumbents',
    source: 'Retail Insider', date: '2026-05-06', tags: ['competitors', 'macro'], urgency: 'high', regions: ['national'],
    summary: 'Women\'s athletic-footwear demand is rising in Canada with newer entrants capturing share, as shoppers diversify beyond the two incumbent megabrands.',
    whyItMatters: 'A direct tailwind for the Footwear launch — the category is expanding precisely as the flight is live. STRATIS is correlating the demand lift against Footwear consideration; see the linked recommendation.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-mens-share', title: "Men's Activewear Outpacing Women's Growth Rate for Third Straight Quarter",
    source: 'NPD Group Canada', date: '2026-05-02', tags: ['macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: "Men's activewear continues to grow faster than women's off a smaller base, with versatility and on/off-court wear driving the expansion.",
    whyItMatters: "Validates the Men's growth thesis. STRATIS flags that Men's is under-weighted relative to its growth rate versus the established Women's business — a portfolio allocation signal.",
    enterprises: ['lululemon'] },
  { id: 'news-lulu-tiktok-shop', title: 'TikTok Shop Canada Expands — Apparel Conversion Rates Beating Benchmark in Early Cohorts',
    source: 'Glossy', date: '2026-05-04', tags: ['social', 'launch'], urgency: 'high', regions: ['national'],
    summary: 'TikTok Shop expanded availability in Canada, with early apparel sellers reporting conversion rates above platform benchmark among Gen-Z cohorts.',
    whyItMatters: 'A new lower-funnel surface exactly where the Gen-Z acquisition flight already concentrates attention. STRATIS is watching for a shoppable-format CVR lift to justify a test allocation.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-cotton-cost', title: 'Technical-Fabric Input Costs Ease as Synthetic Supply Normalizes',
    source: 'Sourcing Journal', date: '2026-04-27', tags: ['macro'], urgency: 'low', regions: ['national'],
    summary: 'Synthetic technical-fabric input costs eased as supply normalized, modestly relieving cost pressure on premium activewear lines.',
    whyItMatters: 'A small margin tailwind that widens room for full-price selling. Tracked at the brand level; no media reallocation required.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-resale-growth', title: 'Branded Resale & Trade-In Programs Drive Loyalty Lift Across Premium Apparel',
    source: 'Business of Fashion', date: '2026-04-21', tags: ['macro', 'partnerships'], urgency: 'medium', regions: ['national'],
    summary: 'Premium apparel brands report that resale and trade-in programs are lifting member retention and repeat purchase, especially among younger cohorts.',
    whyItMatters: 'A retention lever adjacent to the Membership and Win-Back flights. A structural signal STRATIS is correlating against lapsed-purchaser recovery.',
    enterprises: ['lululemon'] },
];

export const LULULEMON_RADAR_PINS = ['news-lulu-footwear-momentum', 'news-lulu-mens-share', 'news-lulu-tiktok-shop'];

export const LULULEMON_INSIGHTS: Insight[] = [
  {
    id: 'ins-lulu-01-mens-allocation', createdAt: todayISO,
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'brand',
    channels: ['instagram', 'tiktok', 'ctv'],
    title: "Men's Is Growing Faster Than Women's for a Third Quarter — but Receives a Third of the Media Weight",
    summary: "Across the live portfolio, Men's activewear is compounding faster than the established Women's business, yet Women's still absorbs the large majority of brand and performance weight by legacy default. STRATIS holds growth rate against share-of-investment across every category at once and finds Men's structurally under-funded relative to its trajectory. A deliberate re-weight toward Men's — funded from over-delivered Women's brand weight, not new budget — backs the fastest-growing line where it can compound.",
    evidence: [
      "Men's growth rate outpaces Women's for three consecutive quarters",
      "Men's receives roughly a third of combined brand + performance weight",
      'Allocation reflects legacy default, not current trajectory',
      'Women\'s brand weight shows diminishing marginal reach at current levels',
    ],
    confidence: 0.84,
    impactEstimate: "Re-weighting toward Men's from over-delivered Women's brand weight funds the fastest-growing line without new budget.",
    recommendedAction: "Shift a measured share of over-delivered Women's brand weight into Men's to match its growth trajectory.",
    status: 'new',
    linkedNewsId: 'news-lulu-mens-share',
    actionSteps: [
      { id: 's1', title: "Re-weight toward Men's", subtitle: 'FUND FROM OVER-DELIVERED WOMEN\'S WEIGHT', type: 'budget', completed: false },
      { id: 's2', title: 'Hold net brand reach', subtitle: 'NO NEW BUDGET REQUIRED', type: 'budget', completed: false },
      { id: 's3', title: 'Track growth-vs-share continuously', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-02-footwear-tailwind', createdAt: at(1, '08:30:00'),
    enterprise: 'lululemon', category: 'competitive-macro', scope: 'product', productLine: 'lulu-footwear',
    channels: ['tiktok', 'instagram', 'ttd'],
    title: 'The Footwear Category Is Expanding and Incumbents Are Ceding Share — Scale the Launch Now While the Window Is Open',
    summary: "Women's athletic-footwear demand is rising and newer brands are taking share from the two incumbents — the exact moment a challenger launch compounds. The Footwear flight is performing above blended portfolio CVR but is capped below the spend level the demand can absorb. Lifting the budget cap while the category is expanding and incumbents are soft captures share that hardens once the window closes.",
    evidence: [
      'Women\'s footwear demand rising; incumbents ceding share to newer brands',
      'Footwear flight CVR is above blended portfolio average',
      'Current budget cap sits below absorbable demand',
      'Challenger share captured now hardens after the window closes',
    ],
    confidence: 0.82,
    impactEstimate: 'Lifting the Footwear cap during category expansion captures durable share at above-average CVR.',
    recommendedAction: 'Raise the Footwear launch budget cap to meet absorbable demand while incumbents are soft.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Raise the Footwear budget cap', subtitle: 'MEET ABSORBABLE DEMAND', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate on highest-CVR placements', subtitle: 'TIKTOK + IG', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-03-tiktok-shop', createdAt: at(2, '10:30:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'product', productLine: 'lulu-womens',
    channels: ['tiktok', 'instagram'],
    title: 'Gen-Z Attention Is Already on TikTok but Conversion Happens Two Clicks Away — TikTok Shop Closes the Gap',
    summary: 'The Gen-Z acquisition flight drives strong TikTok engagement, but conversion is handed off to a separate site visit, leaking intent at the exact moment it peaks. TikTok Shop is now live in Canada with early apparel CVR above benchmark. Routing a test slice of the Gen-Z flight through the shoppable format keeps the purchase in the attention moment and is measurable against the current site-handoff path within a few weeks.',
    evidence: [
      'Gen-Z flight drives strong TikTok engagement; conversion is off-platform',
      'Intent leaks during the site handoff',
      'TikTok Shop Canada early apparel CVR is above benchmark',
      'A test slice is cleanly measurable vs the current path',
    ],
    confidence: 0.78,
    impactEstimate: 'A shoppable-format test keeps Gen-Z conversion in the attention moment and quantifies the lift vs the site handoff.',
    recommendedAction: 'Route a measured test slice of the Gen-Z flight through TikTok Shop and read CVR against the site-handoff path.',
    status: 'new',
    linkedNewsId: 'news-lulu-tiktok-shop',
    actionSteps: [
      { id: 's1', title: 'Allocate a test slice to TikTok Shop', subtitle: 'GEN-Z FLIGHT', type: 'budget', completed: false },
      { id: 's2', title: 'Measure CVR vs site handoff', subtitle: 'READ IN 3–4 WEEKS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-04-align-overlap', createdAt: at(4, '13:15:00'),
    enterprise: 'lululemon', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'ttd'],
    title: 'The Always-On Align Flight and the Member Win-Back Are Bidding on the Same Lapsed Members — Paying Twice to Reach Them',
    summary: 'Align performance and the 90-day Win-Back both target recently-lapsed members in the same auctions, so the portfolio pays a premium to reach a person both flights already own. STRATIS measures meaningful overlap in the lapsed-member pool. Suppressing Win-Back audiences from the always-on Align flight (and vice versa) removes the internal auction competition and lets each flight do the job it is funded for.',
    evidence: [
      'Align always-on and Win-Back overlap on recently-lapsed members',
      'Both bid in the same auctions, inflating CPMs against each other',
      'No cross-flight audience suppression is configured',
      'Suppression removes internal competition with no reach loss',
    ],
    confidence: 0.77,
    impactEstimate: 'Cross-suppressing the two flights eliminates double-paying for lapsed members and lowers blended CPM.',
    recommendedAction: 'Configure cross-flight audience suppression between the Align always-on flight and the Win-Back.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Suppress Win-Back audiences from Align', subtitle: 'AND VICE VERSA', type: 'targeting', completed: false },
      { id: 's2', title: 'Re-read blended CPM', subtitle: 'CONFIRM THE RECOVERY', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-lulu-05-creative-geo', createdAt: at(6, '09:00:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-mens',
    channels: ['instagram', 'tiktok'],
    title: "The 'Beyond the Studio' Men's Cut Wins in BC and Stalls in Ontario — Same Creative, Different Market Fit",
    summary: "The Men's brand cut delivers strong engagement and CVR in BC but materially underperforms in Ontario, where on/off-court versatility messaging tests better than the studio-led story. This is a market-fit gap, not a creative-quality one. Serving the versatility variant to Ontario while holding the studio-led cut in BC matches message to market and lifts the weaker geo without touching the winning one.",
    evidence: [
      "Men's studio-led cut over-performs in BC, under-performs in Ontario",
      'Ontario tests better on on/off-court versatility messaging',
      'Gap is market-fit, not creative quality',
      'A geo-split serves each market its best-fit message',
    ],
    confidence: 0.79,
    impactEstimate: 'A geo-targeted creative split lifts the weaker Ontario market without disturbing the winning BC delivery.',
    recommendedAction: "Serve the versatility variant in Ontario and hold the studio-led cut in BC for the Men's flight.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Serve the versatility variant in Ontario', subtitle: 'BEST-FIT MESSAGE', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the studio-led cut in BC', subtitle: 'ALREADY WINNING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-06-agency-arbitrage', createdAt: at(9, '11:30:00'),
    enterprise: 'lululemon', category: 'agency-arbitrage', scope: 'brand',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'Community & Retail Drives the Highest Member-Sign-Up-per-Dollar — but Its Playbook Never Reaches the National Flights',
    summary: 'The Tier 3 Community & Retail team converts member sign-ups at a lower cost than the national flights, driven by event-tied, locally-relevant creative and run-club social proof. The national Membership and acquisition flights rely on generic brand assets. Lifting the community playbook\'s social-proof and event-tied mechanics into national flights scales a proven sign-up efficiency rather than leaving it confined to local activation.',
    evidence: [
      'Community & Retail member-sign-up cost is below the national flights',
      'Advantage traces to event-tied creative + run-club social proof',
      'National flights use generic brand assets for sign-ups',
      'The community mechanic is replicable at national scale',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the community sign-up mechanic into national flights lowers blended member-acquisition cost.',
    recommendedAction: 'Adopt the Community & Retail social-proof and event-tied sign-up mechanics in the national Membership flights.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the community sign-up mechanic', subtitle: 'SOCIAL PROOF + EVENT-TIED', type: 'targeting', completed: false },
      { id: 's2', title: 'Scale into national Membership flights', subtitle: 'REPLACE GENERIC ASSETS', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-07-align-pacing', createdAt: at(3, '10:10:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'product', productLine: 'lulu-align',
    channels: ['google-search', 'instagram'],
    title: "Align's Always-On Search Paces Flat by Day but Demand Concentrates on Weekends",
    summary: 'The Align always-on flight holds spend constant across the week, but Align intent peaks Friday through Sunday and troughs midweek. Flat pacing therefore overspends on low-intent weekdays and under-delivers the Saturday peak. Shifting to demand-weighted day-parting captures the weekend surge at the same total budget and trims wasted midweek delivery.',
    evidence: [
      'Align demand peaks Fri–Sun and troughs Tuesday',
      'Flat pacing holds spend constant across all days',
      'Midweek delivery converts below the weekend',
      'Same budget, mis-timed against demand',
    ],
    confidence: 0.76,
    impactEstimate: 'Demand-weighted day-parting captures the weekend peak and recovers wasted midweek spend at no added budget.',
    recommendedAction: 'Switch the Align always-on flight to demand-weighted day-parting, front-loading Fri–Sun.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Adopt demand-weighted day-parting', subtitle: 'FRONT-LOAD FRI–SUN', type: 'scheduling', completed: false },
      { id: 's2', title: 'Trim low-intent midweek delivery', subtitle: 'SAME TOTAL BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-08-growth-engines', createdAt: at(8, '09:30:00'),
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'instagram', 'tiktok'],
    title: "Footwear and Men's Are the Two Fastest-Growing Categories yet Together Carry a Minority of Brand Weight",
    summary: "The portfolio's two fastest-growing categories — Footwear and Men's — receive less combined brand weight than the established Women's and Align lines, an allocation anchored to current revenue rather than trajectory. Tilting brand weight toward the growth engines backs where the business is heading, funded from the mature lines' over-delivered reach rather than new budget.",
    evidence: [
      "Footwear and Men's are the two fastest-growing categories",
      'Together they carry a minority of brand weight',
      "Women's and Align hold the majority by legacy revenue share",
      'Mature-line brand reach shows diminishing marginal return',
    ],
    confidence: 0.79,
    impactEstimate: 'Tilting weight toward the growth engines compounds the categories with the steepest trajectory at no new budget.',
    recommendedAction: "Shift a measured share of mature-line brand weight into Footwear and Men's.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: "Tilt brand weight to Footwear + Men's", subtitle: 'BACK THE GROWTH ENGINES', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered mature lines', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-09-home-market-overindex', createdAt: at(5, '08:45:00'),
    enterprise: 'lululemon', category: 'national-regional', scope: 'brand',
    channels: ['instagram', 'tiktok', 'ooh'],
    title: 'The Brand Over-Invests in Its Saturated BC Home Market While Ontario and Quebec Carry the Steepest Untapped Growth',
    summary: "National brand weight skews heavily toward BC — the founding home market — where awareness is already saturated and incremental reach is expensive. STRATIS holds market saturation against growth rate across every geo at once and finds Ontario and Quebec compounding faster off lower awareness, yet receiving proportionally thinner weight. Re-balancing a measured share of BC's diminishing-return weight into Ontario and Quebec backs the markets with the most room to run, without lifting national budget.",
    evidence: [
      'BC carries disproportionate national brand weight versus its share of growth',
      'BC awareness is saturated; incremental reach there is the most expensive',
      'Ontario and Quebec compound faster off lower awareness bases',
      "Re-balancing funds high-growth geos from BC's diminishing returns",
    ],
    confidence: 0.81,
    impactEstimate: "Shifting saturated BC weight into Ontario and Quebec backs the steepest-growth geos at no new national budget.",
    recommendedAction: 'Re-balance a measured share of BC brand weight into Ontario and Quebec where headroom is largest.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Trim saturated BC brand weight', subtitle: 'DIMINISHING REACH', type: 'budget', completed: false },
      { id: 's2', title: 'Fund Ontario + Quebec growth', subtitle: 'LOWER AWARENESS, MORE HEADROOM', type: 'budget', completed: false },
      { id: 's3', title: 'Track saturation-vs-growth by geo', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-10-store-halo', createdAt: at(7, '11:05:00'),
    enterprise: 'lululemon', category: 'national-regional', scope: 'brand',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'New-Store DMAs Show a Measurable Online-Order Halo for Eight Weeks — but Media There Stays at National Default Weight',
    summary: 'In DMAs around recent store openings, online orders lift above the national baseline for roughly eight weeks as physical presence seeds local demand. STRATIS correlates store-opening calendars against geo-level order velocity and finds the halo is real but unsupported — media in those DMAs holds at flat national weight rather than leaning into the window. A timed local pulse layered over each opening compounds the physical halo with paid reach while the lift is live.',
    evidence: [
      'Online orders lift above baseline in new-store DMAs for ~8 weeks',
      'The halo decays after the opening window closes',
      'Media in those DMAs holds at flat national weight',
      'Store-opening calendar is a leading indicator STRATIS already tracks',
    ],
    confidence: 0.76,
    impactEstimate: 'A timed local media pulse over each store opening compounds the physical halo while order velocity is elevated.',
    recommendedAction: 'Layer a timed local media pulse over each new-store DMA for the eight-week halo window.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Pulse media in new-store DMAs', subtitle: '8-WEEK HALO WINDOW', type: 'scheduling', completed: false },
      { id: 's2', title: 'Weight to opening calendar', subtitle: 'LEAD THE LIFT', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-11-ctv-vs-social', createdAt: at(10, '09:20:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ctv', 'instagram', 'tiktok'],
    title: "CTV Delivers Brand Reach at a Lower Incremental Cost Than Social Above the Frequency Cap — yet the Split Stays Fixed",
    summary: "On the always-on brand layer, social reach is efficient up to its frequency cap but turns expensive past it, while CTV continues adding incremental reach more cheaply at the margin. STRATIS reads the cost-per-incremental-reach curve across both surfaces and finds the brand split is held at a fixed ratio rather than set at the efficient crossover. Shifting marginal brand dollars from saturated social frequency into CTV holds total reach while lowering blended cost.",
    evidence: [
      'Social reach is efficient up to its frequency cap, expensive past it',
      'CTV adds incremental reach more cheaply at the margin',
      'Brand split is held at a fixed ratio, not the efficient crossover',
      'Cost-per-incremental-reach curve points to a CTV tilt',
    ],
    confidence: 0.78,
    impactEstimate: 'Moving marginal brand spend from saturated social frequency into CTV holds reach at a lower blended cost.',
    recommendedAction: 'Shift marginal brand dollars from over-frequencied social into CTV up to the efficient crossover.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap social at the efficient frequency', subtitle: 'STOP OVER-FREQUENCY', type: 'bidding', completed: false },
      { id: 's2', title: 'Shift the margin into CTV', subtitle: 'CHEAPER INCREMENTAL REACH', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-12-accessories-attach', createdAt: at(11, '10:40:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'product', productLine: 'lulu-accessories',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'Bags & Accessories Buyers Carry the Highest Basket-Attach Rate but the Line Is Funded Like a Standalone Conversion Play',
    summary: 'Accessories rarely sell alone — orders that include a bag or accessory carry a materially higher AOV because the item attaches to an apparel basket. STRATIS reads attach behaviour across the order log and finds Accessories funded as a standalone conversion line, optimizing to its own low item price rather than to the basket it builds. Re-pointing the flight at basket-builder placements alongside apparel captures the AOV lift the line actually drives instead of its standalone item value.',
    evidence: [
      'Orders with an accessory attached carry a higher AOV',
      'Accessories rarely convert as a standalone purchase',
      'The flight optimizes to low item price, not basket value',
      'Re-pointing to basket-builder placements captures the attach lift',
    ],
    confidence: 0.75,
    impactEstimate: 'Optimizing Accessories to basket attach rather than standalone item value captures its true AOV contribution.',
    recommendedAction: 'Re-point the Accessories flight at basket-builder placements alongside apparel and optimize to AOV.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Optimize to basket attach, not item price', subtitle: 'AOV-WEIGHTED', type: 'bidding', completed: false },
      { id: 's2', title: 'Pair with apparel placements', subtitle: 'BASKET-BUILDER', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-13-footwear-creative', createdAt: at(12, '08:55:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-footwear',
    channels: ['tiktok', 'instagram', 'ctv'],
    title: 'The Footwear "On-Foot Run" Creative Out-Converts the Studio-Styling Cut by a Wide Margin — but Splits Spend Evenly',
    summary: "Inside the Footwear launch, the on-foot running creative — showing the shoe in motion — converts well above the studio-styling cut, yet the flight splits impressions roughly evenly between them. STRATIS reads creative-level CVR against the expanding category demand and finds the launch diluting its best asset against a clear laggard. Concentrating spend on the proven on-foot cut while the footwear category is expanding scales the winning message exactly when demand can absorb it.",
    evidence: [
      'On-foot running creative converts well above the studio-styling cut',
      'The flight splits impressions roughly evenly between the two',
      'Spend is diluted against a clear creative laggard',
      'Category demand is expanding — the moment to scale the winner',
    ],
    confidence: 0.8,
    impactEstimate: 'Concentrating spend on the proven on-foot cut scales the winning message into expanding footwear demand.',
    recommendedAction: 'Shift Footwear impressions onto the on-foot running creative and retire the studio-styling laggard.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Concentrate spend on the on-foot cut', subtitle: 'PROVEN WINNER', type: 'creative', completed: false },
      { id: 's2', title: 'Retire the studio-styling laggard', subtitle: 'STOP DILUTING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-14-winback-creative', createdAt: at(13, '13:30:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-accessories',
    channels: ['facebook', 'instagram', 'google-search'],
    title: 'The Win-Back Leans on a Generic Discount Message When "What\'s New Since You Left" Recovers Lapsed Members at a Lower Cost',
    summary: "The 90-day Win-Back relies on a generic promo creative, but lapsed members respond materially better to a product-news angle — what has launched since their last order — than to a price cut. STRATIS reads recovery cost by creative angle and finds the discount message both cheaper-looking and less effective, eroding margin on members who would return for newness. Leading the Win-Back with a 'what's new' angle recovers more members at a lower cost and protects full-price selling.",
    evidence: [
      'Lapsed members respond better to a product-news angle than a discount',
      'The current Win-Back leans on a generic promo creative',
      'The discount angle recovers fewer members and erodes margin',
      "A 'what's new since you left' cut lowers recovery cost",
    ],
    confidence: 0.77,
    impactEstimate: "Leading the Win-Back with a product-news angle recovers more lapsed members at a lower cost and protects margin.",
    recommendedAction: "Replace the generic discount creative with a 'what's new since you left' product-news angle.",
    status: 'new',
    linkedNewsId: 'news-lulu-resale-growth',
    actionSteps: [
      { id: 's1', title: "Lead with a 'what's new' angle", subtitle: 'PRODUCT NEWS, NOT PRICE', type: 'creative', completed: false },
      { id: 's2', title: 'Retire the generic discount cut', subtitle: 'PROTECT MARGIN', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-15-membership-ltv', createdAt: at(14, '09:10:00'),
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'product', productLine: 'lulu-membership',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'Members Carry Far Higher Repeat-Order LTV Than One-Time Buyers, yet the Mix Funds Acquisition Over Member-Deepening',
    summary: 'A signed-up member repeat-orders at a multiple of a one-time buyer, and resale and trade-in programs are lifting that retention further across premium apparel. STRATIS holds member LTV against the acquisition-versus-deepening split and finds the portfolio funding net-new acquisition while under-investing in converting and retaining members — the cohort with the steepest lifetime value. Tilting a measured share toward member sign-up and deepening backs the highest-LTV cohort rather than chasing lower-value one-time orders.',
    evidence: [
      'Members repeat-order at a multiple of one-time buyers',
      'Resale and trade-in programs are lifting member retention further',
      'The mix funds net-new acquisition over member-deepening',
      'Member LTV is the steepest lifetime-value cohort in the portfolio',
    ],
    confidence: 0.82,
    impactEstimate: 'Tilting spend toward member sign-up and deepening backs the highest-LTV cohort over lower-value one-time orders.',
    recommendedAction: 'Shift a measured share of acquisition spend into member sign-up and deepening flights.',
    status: 'new',
    linkedNewsId: 'news-lulu-resale-growth',
    actionSteps: [
      { id: 's1', title: 'Tilt the mix toward member-deepening', subtitle: 'HIGHEST-LTV COHORT', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from one-time acquisition', subtitle: 'LOWER LIFETIME VALUE', type: 'budget', completed: false },
      { id: 's3', title: 'Track LTV by cohort', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-16-mens-tilt', createdAt: at(15, '10:25:00'),
    enterprise: 'lululemon', category: 'competitive-macro', scope: 'product', productLine: 'lulu-mens',
    channels: ['instagram', 'tiktok', 'google-search', 'ttd'],
    title: "Men's Activewear Is Outgrowing the Category for a Third Quarter on Versatility — but the Men's Flight Still Leads With the Studio Story",
    summary: "Men's activewear is compounding off versatility and on/off-court wear, the third straight quarter of category outperformance, and the macro tailwind is broadening the addressable buyer. STRATIS correlates the category growth signal against the live Men's flight and finds it still led by a studio-led consideration story that lags the versatility angle now driving the market. Re-pointing the Men's flight at the versatility narrative aligns the message with where the category is actually expanding.",
    evidence: [
      "Men's activewear outgrows the category for a third straight quarter",
      'Versatility and on/off-court wear drive the expansion',
      "The live Men's flight still leads with a studio-led story",
      'The versatility angle matches where the category is growing',
    ],
    confidence: 0.8,
    impactEstimate: "Aligning the Men's flight to the versatility narrative matches the message to the category's growth driver.",
    recommendedAction: "Re-point the Men's flight to lead with the versatility / on-off-court narrative driving category growth.",
    status: 'new',
    linkedNewsId: 'news-lulu-mens-share',
    actionSteps: [
      { id: 's1', title: 'Lead with the versatility narrative', subtitle: 'ON/OFF-COURT WEAR', type: 'creative', completed: false },
      { id: 's2', title: 'Match weight to category growth', subtitle: 'THIRD-QUARTER TAILWIND', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-17-runclub-funnel', createdAt: at(16, '11:50:00'),
    enterprise: 'lululemon', category: 'audience-overlap', scope: 'product', productLine: 'lulu-footwear',
    channels: ['instagram', 'facebook', 'tiktok'],
    title: 'Run-Club Community Members Convert to Footwear at a High Rate — but the Paused Local Activation Never Hands Them to the Footwear Launch',
    summary: "Run-club community members are a primed footwear audience — they convert to Footwear well above cold prospects — yet the Run Club local activation is paused and the Footwear launch sources audiences cold. STRATIS reads the overlap between community engagement and footwear conversion and finds a warm funnel left disconnected. Restarting the community activation as a feeder and seeding the Footwear launch with run-club audiences turns a proven affinity into a lower-cost footwear conversion path.",
    evidence: [
      'Run-club community members convert to Footwear above cold prospects',
      'The Run Club local activation is currently paused',
      'The Footwear launch sources audiences cold, not from community',
      'A warm community-to-footwear funnel is left disconnected',
    ],
    confidence: 0.76,
    impactEstimate: 'Feeding run-club community audiences into the Footwear launch opens a lower-cost, higher-intent conversion path.',
    recommendedAction: 'Restart the Run Club activation as a feeder and seed the Footwear launch with run-club audiences.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Restart Run Club as a feeder', subtitle: 'WARM THE FUNNEL', type: 'targeting', completed: false },
      { id: 's2', title: 'Seed Footwear with run-club audiences', subtitle: 'HIGHER-INTENT, LOWER-COST', type: 'targeting', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const LULULEMON_VISUALS: Record<string, InsightVisual> = {
  'ins-lulu-01-mens-allocation': {
    kind: 'bar', xKey: 'line', series: ['growth', 'share'],
    yTitle: 'Growth rate % · investment share %',
    config: { growth: { label: 'Growth rate', color: TEAL }, share: { label: 'Share of investment', color: PURPLE } },
    data: [
      { line: "Men's", growth: 14, share: 33 },
      { line: "Women's", growth: 6, share: 67 },
    ],
    caption: "Men's grows 2× faster but receives a third of the weight",
  },
  'ins-lulu-02-footwear-tailwind': {
    kind: 'line', xKey: 'month', series: ['demand', 'incumbent'],
    yTitle: 'Indexed to 100',
    config: { demand: { label: "Women's footwear demand", color: TEAL }, incumbent: { label: 'Incumbent share', color: RED } },
    data: [
      { month: 'Jan', demand: 100, incumbent: 100 }, { month: 'Feb', demand: 106, incumbent: 97 },
      { month: 'Mar', demand: 113, incumbent: 94 }, { month: 'Apr', demand: 119, incumbent: 90 },
      { month: 'May', demand: 127, incumbent: 86 },
    ],
    caption: 'Category expanding as incumbents cede share — the window to scale',
  },
  'ins-lulu-03-tiktok-shop': {
    kind: 'bar', xKey: 'path', series: ['cvr'], perBarColor: true,
    yTitle: 'Conversion rate (index)',
    config: { cvr: { label: 'CVR index' } },
    data: [
      { path: 'Site handoff', cvr: 100, fill: MUTED },
      { path: 'TikTok Shop', cvr: 168, fill: TEAL },
    ],
    caption: 'Keeping the purchase in-app converts Gen-Z above the site handoff',
  },
  'ins-lulu-04-align-overlap': {
    kind: 'bar', xKey: 'state', series: ['cpm'], perBarColor: true,
    yTitle: 'Blended CPM ($)',
    config: { cpm: { label: 'Blended CPM' } },
    data: [
      { state: 'Overlapping', cpm: 14.2, fill: RED },
      { state: 'Cross-suppressed', cpm: 11.1, fill: TEAL },
    ],
    caption: 'Align and Win-Back bid the same lapsed members — suppression lowers CPM',
  },
  'ins-lulu-05-creative-geo': {
    kind: 'bar', xKey: 'geo', series: ['studio', 'versatility'],
    yTitle: 'CVR index',
    config: { studio: { label: 'Studio-led cut', color: BLUE }, versatility: { label: 'Versatility variant', color: TEAL } },
    data: [
      { geo: 'BC', studio: 128, versatility: 110 },
      { geo: 'Ontario', studio: 84, versatility: 116 },
    ],
    caption: "Men's studio cut wins BC, stalls Ontario — versatility fits ON",
  },
  'ins-lulu-06-agency-arbitrage': {
    kind: 'bar', xKey: 'team', series: ['cost'], perBarColor: true,
    yTitle: 'Member sign-up cost ($)',
    config: { cost: { label: 'Cost per sign-up' } },
    data: [
      { team: 'Community & Retail', cost: 18, fill: TEAL },
      { team: 'National', cost: 27, fill: RED },
    ],
    caption: 'Community sign-up cost beats national — the local mechanic should scale',
  },
  'ins-lulu-07-align-pacing': {
    kind: 'line', xKey: 'day', series: ['demand', 'pacing'],
    yTitle: 'Indexed to 100',
    config: { demand: { label: 'Align demand', color: TEAL }, pacing: { label: 'Flat pacing', color: MUTED } },
    data: [
      { day: 'Mon', demand: 88, pacing: 100 }, { day: 'Tue', demand: 84, pacing: 100 },
      { day: 'Wed', demand: 90, pacing: 100 }, { day: 'Thu', demand: 102, pacing: 100 },
      { day: 'Fri', demand: 121, pacing: 100 }, { day: 'Sat', demand: 142, pacing: 100 },
      { day: 'Sun', demand: 119, pacing: 100 },
    ],
    caption: 'Demand peaks on weekends — flat pacing overspends midweek',
  },
  'ins-lulu-08-growth-engines': {
    kind: 'bar', xKey: 'category', series: ['growth', 'weight'],
    yTitle: 'Growth % · brand weight %',
    config: { growth: { label: 'Growth rate', color: TEAL }, weight: { label: 'Brand weight', color: PURPLE } },
    data: [
      { category: 'Footwear', growth: 22, weight: 14 },
      { category: "Men's", growth: 14, weight: 12 },
      { category: 'Align', growth: 8, weight: 26 },
      { category: "Women's", growth: 6, weight: 31 },
    ],
    caption: "Footwear & Men's grow fastest yet carry a minority of brand weight",
  },
  'ins-lulu-09-home-market-overindex': {
    kind: 'scatter', xKey: 'saturation', series: ['growth'],
    xName: 'Awareness saturation %', yName: 'Growth rate %', perBarColor: true,
    config: { growth: { label: 'Geo' } },
    legend: [
      { label: 'Over-funded (BC)', color: RED },
      { label: 'Under-funded growth geos', color: TEAL },
    ],
    data: [
      { saturation: 88, growth: 6, fill: RED, name: 'BC' },
      { saturation: 61, growth: 15, fill: TEAL, name: 'Ontario' },
      { saturation: 54, growth: 17, fill: TEAL, name: 'Quebec' },
      { saturation: 67, growth: 11, fill: TEAL, name: 'Alberta' },
    ],
    caption: 'Saturated BC over-funded; Ontario & Quebec hold the growth headroom',
  },
  'ins-lulu-10-store-halo': {
    kind: 'line', xKey: 'week', series: ['halo', 'baseline'],
    yTitle: 'Online orders (indexed)',
    config: { halo: { label: 'New-store DMA orders', color: TEAL }, baseline: { label: 'National baseline', color: MUTED } },
    data: [
      { week: 'W1', halo: 138, baseline: 100 }, { week: 'W2', halo: 134, baseline: 100 },
      { week: 'W3', halo: 129, baseline: 100 }, { week: 'W4', halo: 123, baseline: 100 },
      { week: 'W5', halo: 117, baseline: 100 }, { week: 'W6', halo: 111, baseline: 100 },
      { week: 'W7', halo: 105, baseline: 100 }, { week: 'W8', halo: 101, baseline: 100 },
    ],
    refLines: [{ axis: 'x', value: 'W8', label: 'Halo decays', color: GRID }],
    caption: 'Store-opening DMAs lift orders for ~8 weeks — media stays flat',
  },
  'ins-lulu-11-ctv-vs-social': {
    kind: 'line', xKey: 'reach', series: ['social', 'ctv'],
    yTitle: 'Cost per incremental reach point ($)',
    config: { social: { label: 'Social', color: RED }, ctv: { label: 'CTV', color: TEAL } },
    data: [
      { reach: '40%', social: 4.1, ctv: 6.0 }, { reach: '50%', social: 4.8, ctv: 6.1 },
      { reach: '60%', social: 6.2, ctv: 6.3 }, { reach: '70%', social: 9.4, ctv: 6.6 },
      { reach: '80%', social: 14.8, ctv: 7.1 },
    ],
    refLines: [{ axis: 'x', value: '60%', label: 'Efficient crossover', color: GRID }],
    caption: 'Past the frequency cap, CTV adds reach more cheaply than social',
  },
  'ins-lulu-12-accessories-attach': {
    kind: 'bar', xKey: 'order', series: ['aov'], perBarColor: true,
    yTitle: 'Average order value ($)',
    config: { aov: { label: 'AOV' } },
    data: [
      { order: 'No accessory', aov: 132, fill: MUTED },
      { order: 'Accessory attached', aov: 198, fill: TEAL },
    ],
    refLines: [{ axis: 'y', value: 132, label: 'Standalone baseline', color: RED }],
    caption: 'Attaching an accessory lifts AOV — fund the basket, not the item',
  },
  'ins-lulu-13-footwear-creative': {
    kind: 'bar', xKey: 'creative', series: ['cvr', 'impressions'],
    yTitle: 'CVR index · impression share %',
    config: { cvr: { label: 'CVR index', color: TEAL }, impressions: { label: 'Impression share', color: PURPLE } },
    data: [
      { creative: 'On-foot run', cvr: 152, impressions: 50 },
      { creative: 'Studio styling', cvr: 91, impressions: 50 },
    ],
    caption: 'On-foot run out-converts studio cut — yet spend splits evenly',
  },
  'ins-lulu-14-winback-creative': {
    kind: 'bar', xKey: 'angle', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per recovered member ($)',
    config: { cost: { label: 'Recovery cost' } },
    data: [
      { angle: 'Generic discount', cost: 41, fill: RED },
      { angle: "What's new", cost: 29, fill: TEAL },
    ],
    caption: "'What's new' recovers lapsed members cheaper than a discount",
  },
  'ins-lulu-15-membership-ltv': {
    kind: 'bar', xKey: 'cohort', series: ['ltv'], perBarColor: true,
    yTitle: '12-month repeat LTV ($)',
    config: { ltv: { label: 'Repeat LTV' } },
    data: [
      { cohort: 'One-time buyer', ltv: 164, fill: MUTED },
      { cohort: 'Signed-up member', ltv: 612, fill: GOLD },
    ],
    caption: 'Members repeat-order at a multiple of one-time buyer LTV',
  },
  'ins-lulu-16-mens-tilt': {
    kind: 'line', xKey: 'quarter', series: ['mens', 'category'],
    yTitle: 'Growth rate %',
    config: { mens: { label: "Men's activewear", color: TEAL }, category: { label: 'Category average', color: MUTED } },
    data: [
      { quarter: 'Q1', mens: 11, category: 7 }, { quarter: 'Q2', mens: 13, category: 7 },
      { quarter: 'Q3', mens: 15, category: 8 },
    ],
    caption: "Men's outgrows the category three quarters on versatility",
  },
  'ins-lulu-17-runclub-funnel': {
    kind: 'bar', xKey: 'source', series: ['cvr'], perBarColor: true,
    yTitle: 'Footwear CVR index',
    config: { cvr: { label: 'Footwear CVR' } },
    data: [
      { source: 'Cold prospect', cvr: 100, fill: MUTED },
      { source: 'Run-club member', cvr: 173, fill: TEAL },
    ],
    caption: 'Run-club members convert to footwear far above cold prospects',
  },
};
