// ===========================================================================
// lululemon (slug) → FreshCo — Discount Grocery banner (Empire / Sobeys)
// Representative campaign data + a full insight list + market news.
// Value-led discount grocery (Ontario + West); "conversions" are baskets /
// transactions, revenue is attributed sales, headline KPI is ROAS. Main
// competitors: No Frills, Food Basics, Walmart. Illustrative demo figures
// grounded in the FreshCo value categories, shopper audiences, and a
// creative / performance-media / store-community structure.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, PURPLE, MUTED, GOLD, GRID } from '../insight-visual-types';

export const LULULEMON_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — BRAND (FreshCo Creative) ──
  { id: 'lulu-womens-brand', name: 'Fresh & Produce — Everyday Low Price Brand Hero',
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-womens',
    audiences: ['lulu-yogis', 'lulu-everyday'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'instagram', 'tiktok', 'ooh'], geos: ['national'], budgetMultiplier: 1.30,
    plannedBudget: 9_600_000, revPerConvRange: [128, 240], cvrModifier: 1.15, cplCalibration: 0.72, revTrend: 0.0005 },
  { id: 'lulu-mens-grow', name: 'Meat & Value Packs — Stock-Up & Save Growth',
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-mens',
    audiences: ['lulu-mens-perf', 'lulu-everyday'], objective: 'consideration', status: 'live',
    channels: ['instagram', 'tiktok', 'google-search', 'ttd'], geos: ['national', 'ontario'], budgetMultiplier: 1.05,
    plannedBudget: 6_800_000, revPerConvRange: [118, 220], cvrModifier: 1.10, cplCalibration: 0.74, revTrend: 0.0006 },
  { id: 'lulu-footwear-launch', name: 'World Foods — New Aisles Launch',
    enterprise: 'lululemon', division: 'tier-1', agency: 'lulu-inhouse', productLine: 'lulu-footwear',
    audiences: ['lulu-runners', 'lulu-genz'], objective: 'awareness', status: 'live',
    channels: ['tiktok', 'instagram', 'ctv', 'ttd'], geos: ['national'], budgetMultiplier: 1.15,
    plannedBudget: 7_400_000, revPerConvRange: [140, 250], cvrModifier: 1.05, cplCalibration: 0.70, revTrend: 0.0007 },

  // ── TIER 2 — PERFORMANCE MEDIA (FreshCo Performance Media) ──
  { id: 'lulu-align-performance', name: 'Weekly Price Drops — Always-On Performance',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-align',
    audiences: ['lulu-yogis', 'lulu-everyday', 'lulu-members'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'instagram', 'facebook', 'ttd'], geos: ['national'], budgetMultiplier: 1.20,
    plannedBudget: 8_200_000, revPerConvRange: [110, 198], cvrModifier: 1.30, cplCalibration: 0.80, revTrend: 0.0006 },
  { id: 'lulu-genz-tiktok', name: 'Young Value Seekers — TikTok Basket Acquisition',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-womens',
    audiences: ['lulu-genz'], objective: 'conversion', status: 'live',
    channels: ['tiktok', 'instagram', 'google-search'], geos: ['national', 'bc'], budgetMultiplier: 0.95,
    plannedBudget: 5_200_000, revPerConvRange: [96, 176], cvrModifier: 1.20, cplCalibration: 0.78, revTrend: 0.0006 },
  { id: 'lulu-winback', name: 'Conquest No Frills — 90-Day Win-Back',
    enterprise: 'lululemon', division: 'tier-2', agency: 'lulu-performance', productLine: 'lulu-accessories',
    audiences: ['lulu-lapsed'], objective: 'retention', status: 'live',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.70,
    plannedBudget: 2_800_000, revPerConvRange: [104, 188], cvrModifier: 1.25, cplCalibration: 0.82, revTrend: 0.0005 },

  // ── TIER 3 — STORE & COMMUNITY (FreshCo Store & Community) ──
  { id: 'lulu-membership-community', name: 'App & Scene+ Offers — Sign-Up Drive',
    enterprise: 'lululemon', division: 'tier-3', agency: 'lulu-community', productLine: 'lulu-membership',
    audiences: ['lulu-members', 'lulu-yogis'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'google-search', 'facebook'], geos: ['ontario', 'bc'], budgetMultiplier: 0.65,
    plannedBudget: 2_600_000, revPerConvRange: [60, 130], cvrModifier: 1.15, cplCalibration: 0.84, revTrend: 0.0005 },
  { id: 'lulu-runners-local', name: 'World Foods — Local Community Activation',
    enterprise: 'lululemon', division: 'tier-3', agency: 'lulu-community', productLine: 'lulu-footwear',
    audiences: ['lulu-runners', 'lulu-members'], objective: 'consideration', status: 'paused',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['ontario', 'alberta'], budgetMultiplier: 0.60,
    plannedBudget: 2_200_000, revPerConvRange: [130, 236], cvrModifier: 1.00, cplCalibration: 0.76, revTrend: 0.0006 },
];

export const LULULEMON_NEWS: NewsItem[] = [
  { id: 'news-lulu-footwear-momentum', title: 'World-Foods Aisle Demand Surging in Canadian Discount Grocery — Newcomer Households Driving Multicultural Basket Growth',
    source: 'Retail Insider', date: '2026-05-06', tags: ['grocery', 'macro'], urgency: 'high', regions: ['national'],
    summary: 'Demand for World Foods / multicultural grocery is rising fast in the discount channel as newcomer households shop value banners, expanding the category well beyond legacy centre-store staples.',
    whyItMatters: 'A direct tailwind for the World Foods launch — the category is expanding precisely as the flight is live. STRATIS is correlating the demand lift against World Foods basket conversion; see the linked recommendation.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-mens-share', title: 'Meat & Value-Pack Volume Outpacing Centre-Store Growth for Third Straight Quarter as Shoppers Stock Up',
    source: 'Canadian Grocer', date: '2026-05-02', tags: ['value', 'macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'Family-size meat and value-pack volume keeps growing faster than centre-store packaged goods as cost-conscious households shift to bulk stock-up trips to stretch budgets.',
    whyItMatters: 'Validates the Meat & Value Packs growth thesis. STRATIS flags that Meat is under-weighted relative to its growth rate versus the established Fresh & Produce category — a portfolio allocation signal.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-tiktok-shop', title: 'No Frills Launches Aggressive "Hauler" Price-Drop Value Event — Discount Channel Bracing for Share Battle',
    source: 'The Globe and Mail', date: '2026-05-04', tags: ['competitors', 'value'], urgency: 'high', regions: ['national'],
    summary: 'Loblaw\'s No Frills kicked off an aggressive multi-week "Hauler" price-drop event, deep-cutting flyer staples and pushing PC Optimum offers to pull stock-up trips across Ontario and the West.',
    whyItMatters: 'A direct value-channel threat landing exactly where the Weekly Price Drops and Young Value Seeker flights concentrate. STRATIS recommends a measured, surgical counter on the highest-traffic staples rather than a blanket price match.',
    competitor: 'No Frills',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-cotton-cost', title: 'Wholesale Produce & Protein Input Costs Ease as Supply Normalizes',
    source: 'Statistics Canada', date: '2026-04-27', tags: ['macro'], urgency: 'low', regions: ['national'],
    summary: 'Wholesale produce and protein input costs eased as supply normalized, modestly relieving cost pressure on flyer-staple pricing in the discount channel.',
    whyItMatters: 'A small margin tailwind that widens room for sharper hot-buy pricing. Tracked at the banner level; no media reallocation required.',
    enterprises: ['lululemon'] },
  { id: 'news-lulu-resale-growth', title: 'Digital-Flyer & App-Offer Adoption Driving Loyalty Lift Across Discount Grocery',
    source: 'Grocery Business', date: '2026-04-21', tags: ['loyalty', 'partnerships'], urgency: 'medium', regions: ['national'],
    summary: 'Discount banners report that digital flyers and personalized app / Scene+ offers are lifting trip frequency and basket size, especially among younger and newcomer value shoppers.',
    whyItMatters: 'A retention lever adjacent to the App & Scene+ Offers and Win-Back flights. A structural signal STRATIS is correlating against lapsed-shopper recovery.',
    enterprises: ['lululemon'] },
];

export const LULULEMON_RADAR_PINS = ['news-lulu-footwear-momentum', 'news-lulu-mens-share', 'news-lulu-tiktok-shop'];

export const LULULEMON_INSIGHTS: Insight[] = [
  {
    id: 'ins-lulu-01-mens-allocation', createdAt: todayISO,
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'brand',
    channels: ['instagram', 'tiktok', 'ctv'],
    title: 'Meat & Value Packs Is Growing Faster Than Fresh & Produce for a Third Quarter — but Receives a Third of the Media Weight',
    summary: "Across the live portfolio, Meat & Value Packs is compounding faster than the established Fresh & Produce category, yet Fresh still absorbs the large majority of brand and performance weight by legacy default. STRATIS holds growth rate against share-of-investment across every category at once and finds Meat structurally under-funded relative to its trajectory. A deliberate re-weight toward Meat & Value Packs — funded from over-delivered Fresh & Produce weight, not new budget — backs the fastest-growing category where it can compound ROAS.",
    evidence: [
      'Meat & Value Packs growth rate outpaces Fresh & Produce for three consecutive quarters',
      'Meat receives roughly a third of combined brand + performance weight',
      'Allocation reflects legacy default, not current trajectory',
      'Fresh & Produce brand weight shows diminishing marginal reach at current levels',
    ],
    confidence: 0.84,
    impactEstimate: 'Re-weighting toward Meat & Value Packs from over-delivered Fresh weight funds the fastest-growing category without new budget.',
    recommendedAction: 'Shift a measured share of over-delivered Fresh & Produce weight into Meat & Value Packs to match its growth trajectory.',
    status: 'new',
    linkedNewsId: 'news-lulu-mens-share',
    actionSteps: [
      { id: 's1', title: 'Re-weight toward Meat & Value Packs', subtitle: 'FUND FROM OVER-DELIVERED FRESH WEIGHT', type: 'budget', completed: false },
      { id: 's2', title: 'Hold net brand reach', subtitle: 'NO NEW BUDGET REQUIRED', type: 'budget', completed: false },
      { id: 's3', title: 'Track growth-vs-share continuously', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-02-footwear-tailwind', createdAt: at(1, '08:30:00'),
    enterprise: 'lululemon', category: 'competitive-macro', scope: 'product', productLine: 'lulu-footwear',
    channels: ['tiktok', 'instagram', 'ttd'],
    title: 'The World Foods Aisle Is Expanding and Newcomer Households Are Driving It — Scale the Launch Now While the Window Is Open',
    summary: "Multicultural / World Foods demand is rising as newcomer households move into the discount channel — the exact moment a value banner can claim the basket. The World Foods flight is delivering above blended portfolio ROAS but is capped below the spend level the demand can absorb. Lifting the budget cap while the category is expanding captures basket share that hardens once these households settle into a primary store.",
    evidence: [
      'World Foods demand rising; newcomer households driving multicultural baskets',
      'World Foods flight ROAS is above blended portfolio average',
      'Current budget cap sits below absorbable demand',
      'Primary-store share captured now hardens after the window closes',
    ],
    confidence: 0.82,
    impactEstimate: 'Lifting the World Foods cap during category expansion captures durable basket share at above-average ROAS.',
    recommendedAction: 'Raise the World Foods launch budget cap to meet absorbable demand while the category is expanding.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Raise the World Foods budget cap', subtitle: 'MEET ABSORBABLE DEMAND', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate on highest-ROAS placements', subtitle: 'TIKTOK + IG', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-03-tiktok-shop', createdAt: at(2, '10:30:00'),
    enterprise: 'lululemon', category: 'competitive-macro', scope: 'product', productLine: 'lulu-womens',
    channels: ['tiktok', 'instagram'],
    title: 'No Frills Just Launched a "Hauler" Price-Drop Event — Counter Surgically on High-Traffic Staples, Not With a Blanket Match',
    summary: 'No Frills opened an aggressive multi-week "Hauler" price-drop event across Ontario and the West, deep-cutting flyer staples exactly where the Weekly Price Drops and Young Value Seeker flights live. A blanket price match would burn margin everywhere; STRATIS reads which staples actually drive switching and finds the threat concentrated on a short list of high-traffic items. Counter surgically on those staples and amplify them through the digital flyer and app offers, measurable against the event window within a couple of weeks.',
    evidence: [
      'No Frills "Hauler" event deep-cuts flyer staples in Ontario and the West',
      'Threat concentrates on a short list of high-traffic switching items',
      'A blanket price match would erode margin across the whole basket',
      'A surgical counter is cleanly measurable vs the event window',
    ],
    confidence: 0.78,
    impactEstimate: 'A surgical staple-level counter defends switching baskets without the margin bleed of a blanket price match.',
    recommendedAction: 'Counter the No Frills "Hauler" event on high-traffic switching staples via the digital flyer and app offers, not a blanket match.',
    status: 'new',
    linkedNewsId: 'news-lulu-tiktok-shop',
    actionSteps: [
      { id: 's1', title: 'Counter on high-traffic staples only', subtitle: 'SURGICAL, NOT BLANKET', type: 'budget', completed: false },
      { id: 's2', title: 'Measure vs the event window', subtitle: 'READ IN 2–3 WEEKS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-04-align-overlap', createdAt: at(4, '13:15:00'),
    enterprise: 'lululemon', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'ttd'],
    title: 'The Always-On Weekly Price Drops Flight and the No-Frills Win-Back Are Bidding on the Same Lapsed Shoppers — Paying Twice to Reach Them',
    summary: 'Weekly Price Drops and the 90-day Win-Back both target recently-lapsed value shoppers in the same auctions, so the banner pays a premium to reach a person both flights already own. STRATIS measures meaningful overlap in the lapsed-shopper pool. Suppressing Win-Back audiences from the always-on Price Drops flight (and vice versa) removes the internal auction competition and lets each flight do the job it is funded for.',
    evidence: [
      'Weekly Price Drops always-on and Win-Back overlap on recently-lapsed shoppers',
      'Both bid in the same auctions, inflating CPMs against each other',
      'No cross-flight audience suppression is configured',
      'Suppression removes internal competition with no reach loss',
    ],
    confidence: 0.77,
    impactEstimate: 'Cross-suppressing the two flights eliminates double-paying for lapsed shoppers and lowers blended CPM.',
    recommendedAction: 'Configure cross-flight audience suppression between the Weekly Price Drops always-on flight and the Win-Back.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Suppress Win-Back audiences from Price Drops', subtitle: 'AND VICE VERSA', type: 'targeting', completed: false },
      { id: 's2', title: 'Re-read blended CPM', subtitle: 'CONFIRM THE RECOVERY', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-lulu-05-creative-geo', createdAt: at(6, '09:00:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-mens',
    channels: ['instagram', 'tiktok'],
    title: "The 'Stock-Up & Save' Meat Cut Wins in the West and Stalls in Ontario — Same Creative, Different Market Fit",
    summary: "The Meat & Value Packs brand cut delivers strong engagement and ROAS in the West but materially underperforms in Ontario, where a price-per-kilo 'beat the flyer' message tests better than the family stock-up story. This is a market-fit gap, not a creative-quality one. Serving the price-comparison variant to Ontario while holding the stock-up cut in the West matches message to market and lifts the weaker geo without touching the winning one.",
    evidence: [
      'Meat stock-up cut over-performs in the West, under-performs in Ontario',
      'Ontario tests better on price-per-kilo / beat-the-flyer messaging',
      'Gap is market-fit, not creative quality',
      'A geo-split serves each market its best-fit message',
    ],
    confidence: 0.79,
    impactEstimate: 'A geo-targeted creative split lifts the weaker Ontario market without disturbing the winning West delivery.',
    recommendedAction: 'Serve the price-comparison variant in Ontario and hold the stock-up cut in the West for the Meat flight.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Serve the price-comparison variant in Ontario', subtitle: 'BEST-FIT MESSAGE', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the stock-up cut in the West', subtitle: 'ALREADY WINNING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-06-agency-arbitrage', createdAt: at(9, '11:30:00'),
    enterprise: 'lululemon', category: 'agency-arbitrage', scope: 'brand',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'Store & Community Drives the Lowest App-Sign-Up Cost per Dollar — but Its Playbook Never Reaches the National Flights',
    summary: 'The Tier 3 Store & Community team registers app / Scene+ sign-ups at a lower cost than the national flights, driven by store-event-tied, locally-relevant creative and in-aisle social proof. The national App & Scene+ Offers and acquisition flights rely on generic brand assets. Lifting the community playbook\'s social-proof and store-event mechanics into national flights scales a proven sign-up efficiency rather than leaving it confined to local activation.',
    evidence: [
      'Store & Community app-sign-up cost is below the national flights',
      'Advantage traces to store-event creative + in-aisle social proof',
      'National flights use generic brand assets for sign-ups',
      'The community mechanic is replicable at national scale',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the community sign-up mechanic into national flights lowers blended app-acquisition cost.',
    recommendedAction: 'Adopt the Store & Community social-proof and store-event sign-up mechanics in the national App & Scene+ Offers flights.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the community sign-up mechanic', subtitle: 'SOCIAL PROOF + STORE-EVENT', type: 'targeting', completed: false },
      { id: 's2', title: 'Scale into national App & Offer flights', subtitle: 'REPLACE GENERIC ASSETS', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-07-align-pacing', createdAt: at(3, '10:10:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'product', productLine: 'lulu-align',
    channels: ['google-search', 'instagram'],
    title: "Weekly Price Drops' Always-On Search Paces Flat by Day but Stock-Up Demand Concentrates on the Weekend Flyer-Drop",
    summary: 'The Weekly Price Drops always-on flight holds spend constant across the week, but value-shopper intent peaks Thursday through Sunday around the new flyer and big stock-up trips, and troughs midweek. Flat pacing therefore overspends on low-intent weekdays and under-delivers the Saturday peak. Shifting to demand-weighted day-parting captures the weekend surge at the same total budget and trims wasted midweek delivery.',
    evidence: [
      'Price-drop demand peaks Thu–Sun around the flyer drop and troughs Tuesday',
      'Flat pacing holds spend constant across all days',
      'Midweek delivery converts below the weekend',
      'Same budget, mis-timed against demand',
    ],
    confidence: 0.76,
    impactEstimate: 'Demand-weighted day-parting captures the weekend stock-up peak and recovers wasted midweek spend at no added budget.',
    recommendedAction: 'Switch the Weekly Price Drops always-on flight to demand-weighted day-parting, front-loading Thu–Sun.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Adopt demand-weighted day-parting', subtitle: 'FRONT-LOAD THU–SUN', type: 'scheduling', completed: false },
      { id: 's2', title: 'Trim low-intent midweek delivery', subtitle: 'SAME TOTAL BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-08-growth-engines', createdAt: at(8, '09:30:00'),
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'instagram', 'tiktok'],
    title: 'World Foods and Meat & Value Packs Are the Two Fastest-Growing Categories yet Together Carry a Minority of Brand Weight',
    summary: "The portfolio's two fastest-growing categories — World Foods and Meat & Value Packs — receive less combined brand weight than the established Fresh & Produce and Weekly Price Drops lines, an allocation anchored to current sales rather than trajectory. Tilting brand weight toward the growth engines backs where the basket is heading, funded from the mature lines' over-delivered reach rather than new budget.",
    evidence: [
      'World Foods and Meat & Value Packs are the two fastest-growing categories',
      'Together they carry a minority of brand weight',
      'Fresh & Produce and Weekly Price Drops hold the majority by legacy sales share',
      'Mature-line brand reach shows diminishing marginal return',
    ],
    confidence: 0.79,
    impactEstimate: 'Tilting weight toward the growth engines compounds the categories with the steepest trajectory at no new budget.',
    recommendedAction: 'Shift a measured share of mature-line brand weight into World Foods and Meat & Value Packs.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt brand weight to World Foods + Meat', subtitle: 'BACK THE GROWTH ENGINES', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered mature lines', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-09-home-market-overindex', createdAt: at(5, '08:45:00'),
    enterprise: 'lululemon', category: 'national-regional', scope: 'brand',
    channels: ['instagram', 'tiktok', 'ooh'],
    title: 'Ontario Marketing Is Delivering Materially Lower ROAS Than the National Benchmark — the Widest Gap in the Portfolio — While the West Beats It on the Same Budget',
    summary: "National brand weight skews heavily toward Ontario, yet Ontario is returning the lowest ROAS in the banner while the West beats the national benchmark on the same per-dollar budget. STRATIS holds ROAS against media weight across every geo at once and finds Ontario over-funded against its efficiency, with the West and Alberta under-weighted relative to the returns they generate. Re-balancing a measured share of Ontario's lowest-ROAS weight into the West and Alberta backs the markets actually returning the basket, without lifting national budget.",
    evidence: [
      'Ontario returns the lowest ROAS in the banner — the widest efficiency gap in the portfolio',
      'The West beats the national ROAS benchmark on the same per-dollar budget',
      'Ontario carries disproportionate national brand weight versus its efficiency',
      "Re-balancing funds high-ROAS geos from Ontario's diminishing returns",
    ],
    confidence: 0.81,
    impactEstimate: "Shifting low-ROAS Ontario weight into the West and Alberta backs the highest-returning geos at no new national budget.",
    recommendedAction: 'Re-balance a measured share of Ontario brand weight into the West and Alberta where ROAS is strongest.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Trim low-ROAS Ontario brand weight', subtitle: 'WIDEST EFFICIENCY GAP', type: 'budget', completed: false },
      { id: 's2', title: 'Fund West + Alberta', subtitle: 'BEAT THE BENCHMARK, MORE HEADROOM', type: 'budget', completed: false },
      { id: 's3', title: 'Track ROAS-vs-weight by geo', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-10-store-halo', createdAt: at(7, '11:05:00'),
    enterprise: 'lululemon', category: 'national-regional', scope: 'brand',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'New-Store Trade Areas Show a Measurable Basket Halo for Eight Weeks — but Media There Stays at National Default Weight',
    summary: 'In trade areas around recent store openings, transactions and baskets lift above the national baseline for roughly eight weeks as a new value store seeds local switching. STRATIS correlates store-opening calendars against trade-area basket velocity and finds the halo is real but unsupported — media in those areas holds at flat national weight rather than leaning into the window. A timed local pulse layered over each opening compounds the physical halo with paid reach while the lift is live.',
    evidence: [
      'Baskets lift above baseline in new-store trade areas for ~8 weeks',
      'The halo decays after the opening window closes',
      'Media in those trade areas holds at flat national weight',
      'Store-opening calendar is a leading indicator STRATIS already tracks',
    ],
    confidence: 0.76,
    impactEstimate: 'A timed local media pulse over each store opening compounds the physical halo while basket velocity is elevated.',
    recommendedAction: 'Layer a timed local media pulse over each new-store trade area for the eight-week halo window.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Pulse media in new-store trade areas', subtitle: '8-WEEK HALO WINDOW', type: 'scheduling', completed: false },
      { id: 's2', title: 'Weight to opening calendar', subtitle: 'LEAD THE LIFT', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-11-ctv-vs-social', createdAt: at(10, '09:20:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ctv', 'instagram', 'tiktok'],
    title: "CTV Delivers Brand Reach at a Lower Incremental Cost Than Social Above the Frequency Cap — yet the Split Stays Fixed",
    summary: "On the always-on brand layer, social reach is efficient up to its frequency cap but turns expensive past it, while CTV continues adding incremental reach more cheaply at the margin. STRATIS reads the cost-per-incremental-reach curve across both surfaces and finds the brand split is held at a fixed ratio rather than set at the efficient crossover. Shifting marginal brand dollars from saturated social frequency into CTV holds total reach while lowering blended cost.",
    evidence: [
      'Social reach is efficient up to its frequency cap, expensive past it',
      'CTV adds incremental reach more cheaply at the margin',
      'Brand split is held at a fixed ratio, not the efficient crossover',
      'Cost-per-incremental-reach curve points to a CTV tilt',
    ],
    confidence: 0.78,
    impactEstimate: 'Moving marginal brand spend from saturated social frequency into CTV holds reach at a lower blended cost.',
    recommendedAction: 'Shift marginal brand dollars from over-frequencied social into CTV up to the efficient crossover.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap social at the efficient frequency', subtitle: 'STOP OVER-FREQUENCY', type: 'bidding', completed: false },
      { id: 's2', title: 'Shift the margin into CTV', subtitle: 'CHEAPER INCREMENTAL REACH', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-12-accessories-attach', createdAt: at(11, '10:40:00'),
    enterprise: 'lululemon', category: 'tactical-efficiency', scope: 'product', productLine: 'lulu-accessories',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'Centre-Store Value Items Carry the Highest Basket-Attach Rate but the Line Is Funded Like a Standalone Hot-Buy',
    summary: 'Centre-Store Value items rarely fill a trip alone — baskets that include a centre-store hot-buy carry a materially higher total value because the item attaches to a fresh / meat shop. STRATIS reads attach behaviour across the transaction log and finds Centre-Store Value funded as a standalone conversion line, optimizing to its own low unit price rather than to the basket it builds. Re-pointing the flight at basket-builder placements alongside fresh and meat captures the basket lift the line actually drives instead of its standalone item value.',
    evidence: [
      'Baskets with a centre-store value item attached carry a higher total value',
      'Centre-Store Value items rarely anchor a standalone trip',
      'The flight optimizes to low unit price, not basket value',
      'Re-pointing to basket-builder placements captures the attach lift',
    ],
    confidence: 0.75,
    impactEstimate: 'Optimizing Centre-Store Value to basket attach rather than standalone unit value captures its true basket contribution.',
    recommendedAction: 'Re-point the Centre-Store Value flight at basket-builder placements alongside fresh and meat and optimize to basket value.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Optimize to basket attach, not unit price', subtitle: 'BASKET-VALUE-WEIGHTED', type: 'bidding', completed: false },
      { id: 's2', title: 'Pair with fresh & meat placements', subtitle: 'BASKET-BUILDER', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-lulu-13-footwear-creative', createdAt: at(12, '08:55:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-footwear',
    channels: ['tiktok', 'instagram', 'ctv'],
    title: 'The World Foods "Real Shelf Haul" Creative Out-Converts the Recipe-Styling Cut by a Wide Margin — but Splits Spend Evenly',
    summary: "Inside the World Foods launch, the real-shelf haul creative — showing the actual multicultural range and prices on shelf — converts well above the recipe-styling cut, yet the flight splits impressions roughly evenly between them. STRATIS reads creative-level ROAS against the expanding category demand and finds the launch diluting its best asset against a clear laggard. Concentrating spend on the proven real-shelf cut while the World Foods category is expanding scales the winning message exactly when demand can absorb it.",
    evidence: [
      'Real-shelf haul creative converts well above the recipe-styling cut',
      'The flight splits impressions roughly evenly between the two',
      'Spend is diluted against a clear creative laggard',
      'Category demand is expanding — the moment to scale the winner',
    ],
    confidence: 0.8,
    impactEstimate: 'Concentrating spend on the proven real-shelf cut scales the winning message into expanding World Foods demand.',
    recommendedAction: 'Shift World Foods impressions onto the real-shelf haul creative and retire the recipe-styling laggard.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Concentrate spend on the real-shelf cut', subtitle: 'PROVEN WINNER', type: 'creative', completed: false },
      { id: 's2', title: 'Retire the recipe-styling laggard', subtitle: 'STOP DILUTING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-14-winback-creative', createdAt: at(13, '13:30:00'),
    enterprise: 'lululemon', category: 'creative-performance', scope: 'product', productLine: 'lulu-accessories',
    channels: ['facebook', 'instagram', 'google-search'],
    title: 'The No-Frills Win-Back Leans on a Generic Coupon When "See This Week\'s Price Drops" Recovers Lapsed Shoppers at a Lower Cost',
    summary: "The 90-day Win-Back relies on a generic coupon creative, but lapsed value shoppers respond materially better to a live price-proof angle — this week's actual price drops and beat-the-flyer comparisons — than to a one-off coupon. STRATIS reads recovery cost by creative angle and finds the coupon message both cheaper-looking and less effective, eroding margin on shoppers who would return for everyday value. Leading the Win-Back with a 'this week's price drops' angle recovers more shoppers at a lower cost and protects everyday-low-price positioning.",
    evidence: [
      'Lapsed shoppers respond better to a live price-proof angle than a coupon',
      'The current Win-Back leans on a generic coupon creative',
      'The coupon angle recovers fewer shoppers and erodes margin',
      "A 'see this week's price drops' cut lowers recovery cost",
    ],
    confidence: 0.77,
    impactEstimate: "Leading the Win-Back with a live price-proof angle recovers more lapsed shoppers at a lower cost and protects margin.",
    recommendedAction: "Replace the generic coupon creative with a 'see this week's price drops' price-proof angle.",
    status: 'new',
    linkedNewsId: 'news-lulu-resale-growth',
    actionSteps: [
      { id: 's1', title: "Lead with a 'this week's price drops' angle", subtitle: 'PRICE PROOF, NOT A COUPON', type: 'creative', completed: false },
      { id: 's2', title: 'Retire the generic coupon cut', subtitle: 'PROTECT MARGIN', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-lulu-15-membership-ltv', createdAt: at(14, '09:10:00'),
    enterprise: 'lululemon', category: 'strategic-opener', scope: 'product', productLine: 'lulu-membership',
    channels: ['instagram', 'google-search', 'facebook'],
    title: 'App & Scene+ Members Carry Far Higher Repeat-Trip Value Than One-Time Shoppers, yet the Mix Funds Acquisition Over Member-Deepening',
    summary: 'A signed-up app / Scene+ member shops at a multiple of a one-time shopper, and digital-flyer and personalized offers are lifting that trip frequency further across discount grocery. STRATIS holds member value against the acquisition-versus-deepening split and finds the banner funding net-new acquisition while under-investing in converting and retaining members — the cohort with the steepest lifetime value. Tilting a measured share toward app sign-up and offer-deepening backs the highest-value cohort rather than chasing lower-value one-time baskets.',
    evidence: [
      'App / Scene+ members repeat-shop at a multiple of one-time shoppers',
      'Digital flyer and personalized offers are lifting trip frequency further',
      'The mix funds net-new acquisition over member-deepening',
      'Member value is the steepest lifetime-value cohort in the portfolio',
    ],
    confidence: 0.82,
    impactEstimate: 'Tilting spend toward app sign-up and offer-deepening backs the highest-value cohort over lower-value one-time baskets.',
    recommendedAction: 'Shift a measured share of acquisition spend into app / Scene+ sign-up and offer-deepening flights.',
    status: 'new',
    linkedNewsId: 'news-lulu-resale-growth',
    actionSteps: [
      { id: 's1', title: 'Tilt the mix toward member-deepening', subtitle: 'HIGHEST-VALUE COHORT', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from one-time acquisition', subtitle: 'LOWER LIFETIME VALUE', type: 'budget', completed: false },
      { id: 's3', title: 'Track value by cohort', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-lulu-16-mens-tilt', createdAt: at(15, '10:25:00'),
    enterprise: 'lululemon', category: 'competitive-macro', scope: 'product', productLine: 'lulu-mens',
    channels: ['instagram', 'tiktok', 'google-search', 'ttd'],
    title: "Meat & Value Packs Is Outgrowing the Store for a Third Quarter on Stock-Up Trips — but the Flight Still Leads With a Single-Item Deal Story",
    summary: "Family-size meat and value packs are compounding off bulk stock-up behaviour, the third straight quarter of category outperformance, and the macro value tailwind is broadening the stock-up shopper. STRATIS correlates the category growth signal against the live Meat flight and finds it still led by a single-item deal story that lags the stock-up / cost-per-meal angle now driving the category. Re-pointing the Meat flight at the stock-up narrative aligns the message with where the category is actually expanding.",
    evidence: [
      'Meat & Value Packs outgrows the store for a third straight quarter',
      'Bulk stock-up and cost-per-meal behaviour drive the expansion',
      'The live Meat flight still leads with a single-item deal story',
      'The stock-up angle matches where the category is growing',
    ],
    confidence: 0.8,
    impactEstimate: "Aligning the Meat flight to the stock-up narrative matches the message to the category's growth driver.",
    recommendedAction: "Re-point the Meat flight to lead with the stock-up / cost-per-meal narrative driving category growth.",
    status: 'new',
    linkedNewsId: 'news-lulu-mens-share',
    actionSteps: [
      { id: 's1', title: 'Lead with the stock-up narrative', subtitle: 'COST-PER-MEAL VALUE', type: 'creative', completed: false },
      { id: 's2', title: 'Match weight to category growth', subtitle: 'THIRD-QUARTER TAILWIND', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-lulu-17-runclub-funnel', createdAt: at(16, '11:50:00'),
    enterprise: 'lululemon', category: 'audience-overlap', scope: 'product', productLine: 'lulu-footwear',
    channels: ['instagram', 'facebook', 'tiktok'],
    title: 'Newcomer Community Shoppers Convert to World Foods at a High Rate — but the Paused Local Activation Never Hands Them to the World Foods Launch',
    summary: "Newcomer community shoppers are a primed World Foods audience — they convert to the aisle well above cold prospects — yet the local community activation is paused and the World Foods launch sources audiences cold. STRATIS reads the overlap between community engagement and World Foods conversion and finds a warm funnel left disconnected. Restarting the community activation as a feeder and seeding the World Foods launch with newcomer-community audiences turns a proven affinity into a lower-cost basket conversion path.",
    evidence: [
      'Newcomer community shoppers convert to World Foods above cold prospects',
      'The local community activation is currently paused',
      'The World Foods launch sources audiences cold, not from community',
      'A warm community-to-World-Foods funnel is left disconnected',
    ],
    confidence: 0.76,
    impactEstimate: 'Feeding newcomer-community audiences into the World Foods launch opens a lower-cost, higher-intent conversion path.',
    recommendedAction: 'Restart the local community activation as a feeder and seed the World Foods launch with newcomer-community audiences.',
    status: 'new',
    linkedNewsId: 'news-lulu-footwear-momentum',
    actionSteps: [
      { id: 's1', title: 'Restart community activation as a feeder', subtitle: 'WARM THE FUNNEL', type: 'targeting', completed: false },
      { id: 's2', title: 'Seed World Foods with community audiences', subtitle: 'HIGHER-INTENT, LOWER-COST', type: 'targeting', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const LULULEMON_VISUALS: Record<string, InsightVisual> = {
  'ins-lulu-01-mens-allocation': {
    kind: 'bar', xKey: 'line', series: ['growth', 'share'],
    yTitle: 'Growth rate % · investment share %',
    config: { growth: { label: 'Growth rate', color: TEAL }, share: { label: 'Share of investment', color: PURPLE } },
    data: [
      { line: 'Meat & Value', growth: 14, share: 33 },
      { line: 'Fresh & Produce', growth: 6, share: 67 },
    ],
    caption: 'Meat grows 2× faster but receives a third of the weight',
  },
  'ins-lulu-02-footwear-tailwind': {
    kind: 'line', xKey: 'month', series: ['demand', 'incumbent'],
    yTitle: 'Indexed to 100',
    config: { demand: { label: 'World Foods demand', color: TEAL }, incumbent: { label: 'Legacy centre-store share', color: RED } },
    data: [
      { month: 'Jan', demand: 100, incumbent: 100 }, { month: 'Feb', demand: 106, incumbent: 97 },
      { month: 'Mar', demand: 113, incumbent: 94 }, { month: 'Apr', demand: 119, incumbent: 90 },
      { month: 'May', demand: 127, incumbent: 86 },
    ],
    caption: 'World Foods expanding as legacy staples soften — the window to scale',
  },
  'ins-lulu-03-tiktok-shop': {
    kind: 'bar', xKey: 'path', series: ['cvr'], perBarColor: true,
    yTitle: 'Margin retained (index)',
    config: { cvr: { label: 'Margin retained index' } },
    data: [
      { path: 'Blanket price match', cvr: 100, fill: MUTED },
      { path: 'Surgical staple counter', cvr: 168, fill: TEAL },
    ],
    caption: 'A surgical staple counter defends baskets without the blanket-match margin bleed',
  },
  'ins-lulu-04-align-overlap': {
    kind: 'bar', xKey: 'state', series: ['cpm'], perBarColor: true,
    yTitle: 'Blended CPM ($)',
    config: { cpm: { label: 'Blended CPM' } },
    data: [
      { state: 'Overlapping', cpm: 14.2, fill: RED },
      { state: 'Cross-suppressed', cpm: 11.1, fill: TEAL },
    ],
    caption: 'Price Drops and Win-Back bid the same lapsed shoppers — suppression lowers CPM',
  },
  'ins-lulu-05-creative-geo': {
    kind: 'bar', xKey: 'geo', series: ['studio', 'versatility'],
    yTitle: 'ROAS index',
    config: { studio: { label: 'Stock-up cut', color: BLUE }, versatility: { label: 'Price-comparison variant', color: TEAL } },
    data: [
      { geo: 'West', studio: 128, versatility: 110 },
      { geo: 'Ontario', studio: 84, versatility: 116 },
    ],
    caption: 'Meat stock-up cut wins West, stalls Ontario — price-comparison fits ON',
  },
  'ins-lulu-06-agency-arbitrage': {
    kind: 'bar', xKey: 'team', series: ['cost'], perBarColor: true,
    yTitle: 'App sign-up cost ($)',
    config: { cost: { label: 'Cost per sign-up' } },
    data: [
      { team: 'Store & Community', cost: 18, fill: TEAL },
      { team: 'National', cost: 27, fill: RED },
    ],
    caption: 'Community sign-up cost beats national — the local mechanic should scale',
  },
  'ins-lulu-07-align-pacing': {
    kind: 'line', xKey: 'day', series: ['demand', 'pacing'],
    yTitle: 'Indexed to 100',
    config: { demand: { label: 'Price-drop demand', color: TEAL }, pacing: { label: 'Flat pacing', color: MUTED } },
    data: [
      { day: 'Mon', demand: 88, pacing: 100 }, { day: 'Tue', demand: 84, pacing: 100 },
      { day: 'Wed', demand: 90, pacing: 100 }, { day: 'Thu', demand: 102, pacing: 100 },
      { day: 'Fri', demand: 121, pacing: 100 }, { day: 'Sat', demand: 142, pacing: 100 },
      { day: 'Sun', demand: 119, pacing: 100 },
    ],
    caption: 'Demand peaks on the weekend flyer-drop — flat pacing overspends midweek',
  },
  'ins-lulu-08-growth-engines': {
    kind: 'bar', xKey: 'category', series: ['growth', 'weight'],
    yTitle: 'Growth % · brand weight %',
    config: { growth: { label: 'Growth rate', color: TEAL }, weight: { label: 'Brand weight', color: PURPLE } },
    data: [
      { category: 'World Foods', growth: 22, weight: 14 },
      { category: 'Meat & Value', growth: 14, weight: 12 },
      { category: 'Price Drops', growth: 8, weight: 26 },
      { category: 'Fresh & Produce', growth: 6, weight: 31 },
    ],
    caption: 'World Foods & Meat grow fastest yet carry a minority of brand weight',
  },
  'ins-lulu-09-home-market-overindex': {
    kind: 'scatter', xKey: 'saturation', series: ['growth'],
    xName: 'Brand weight share %', yName: 'ROAS index', perBarColor: true,
    config: { growth: { label: 'Geo' } },
    legend: [
      { label: 'Over-funded, low ROAS (Ontario)', color: RED },
      { label: 'Under-funded, high ROAS geos', color: TEAL },
    ],
    data: [
      { saturation: 88, growth: 6, fill: RED, name: 'Ontario' },
      { saturation: 61, growth: 15, fill: TEAL, name: 'West' },
      { saturation: 54, growth: 17, fill: TEAL, name: 'Alberta' },
      { saturation: 67, growth: 11, fill: TEAL, name: 'Quebec' },
    ],
    caption: 'Over-funded Ontario returns low ROAS; West & Alberta beat the benchmark',
  },
  'ins-lulu-10-store-halo': {
    kind: 'line', xKey: 'week', series: ['halo', 'baseline'],
    yTitle: 'Baskets (indexed)',
    config: { halo: { label: 'New-store trade-area baskets', color: TEAL }, baseline: { label: 'National baseline', color: MUTED } },
    data: [
      { week: 'W1', halo: 138, baseline: 100 }, { week: 'W2', halo: 134, baseline: 100 },
      { week: 'W3', halo: 129, baseline: 100 }, { week: 'W4', halo: 123, baseline: 100 },
      { week: 'W5', halo: 117, baseline: 100 }, { week: 'W6', halo: 111, baseline: 100 },
      { week: 'W7', halo: 105, baseline: 100 }, { week: 'W8', halo: 101, baseline: 100 },
    ],
    refLines: [{ axis: 'x', value: 'W8', label: 'Halo decays', color: GRID }],
    caption: 'Store-opening trade areas lift baskets for ~8 weeks — media stays flat',
  },
  'ins-lulu-11-ctv-vs-social': {
    kind: 'line', xKey: 'reach', series: ['social', 'ctv'],
    yTitle: 'Cost per incremental reach point ($)',
    config: { social: { label: 'Social', color: RED }, ctv: { label: 'CTV', color: TEAL } },
    data: [
      { reach: '40%', social: 4.1, ctv: 6.0 }, { reach: '50%', social: 4.8, ctv: 6.1 },
      { reach: '60%', social: 6.2, ctv: 6.3 }, { reach: '70%', social: 9.4, ctv: 6.6 },
      { reach: '80%', social: 14.8, ctv: 7.1 },
    ],
    refLines: [{ axis: 'x', value: '60%', label: 'Efficient crossover', color: GRID }],
    caption: 'Past the frequency cap, CTV adds reach more cheaply than social',
  },
  'ins-lulu-12-accessories-attach': {
    kind: 'bar', xKey: 'order', series: ['aov'], perBarColor: true,
    yTitle: 'Average basket value ($)',
    config: { aov: { label: 'Basket value' } },
    data: [
      { order: 'No centre-store item', aov: 132, fill: MUTED },
      { order: 'Centre-store item attached', aov: 198, fill: TEAL },
    ],
    refLines: [{ axis: 'y', value: 132, label: 'Standalone baseline', color: RED }],
    caption: 'Attaching a centre-store value item lifts the basket — fund the basket, not the item',
  },
  'ins-lulu-13-footwear-creative': {
    kind: 'bar', xKey: 'creative', series: ['cvr', 'impressions'],
    yTitle: 'ROAS index · impression share %',
    config: { cvr: { label: 'ROAS index', color: TEAL }, impressions: { label: 'Impression share', color: PURPLE } },
    data: [
      { creative: 'Real-shelf haul', cvr: 152, impressions: 50 },
      { creative: 'Recipe styling', cvr: 91, impressions: 50 },
    ],
    caption: 'Real-shelf haul out-converts recipe cut — yet spend splits evenly',
  },
  'ins-lulu-14-winback-creative': {
    kind: 'bar', xKey: 'angle', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per recovered shopper ($)',
    config: { cost: { label: 'Recovery cost' } },
    data: [
      { angle: 'Generic coupon', cost: 41, fill: RED },
      { angle: "This week's price drops", cost: 29, fill: TEAL },
    ],
    caption: "'This week's price drops' recovers lapsed shoppers cheaper than a coupon",
  },
  'ins-lulu-15-membership-ltv': {
    kind: 'bar', xKey: 'cohort', series: ['ltv'], perBarColor: true,
    yTitle: '12-month repeat value ($)',
    config: { ltv: { label: 'Repeat value' } },
    data: [
      { cohort: 'One-time shopper', ltv: 164, fill: MUTED },
      { cohort: 'App / Scene+ member', ltv: 612, fill: GOLD },
    ],
    caption: 'App / Scene+ members repeat-shop at a multiple of one-time shopper value',
  },
  'ins-lulu-16-mens-tilt': {
    kind: 'line', xKey: 'quarter', series: ['mens', 'category'],
    yTitle: 'Growth rate %',
    config: { mens: { label: 'Meat & Value Packs', color: TEAL }, category: { label: 'Store average', color: MUTED } },
    data: [
      { quarter: 'Q1', mens: 11, category: 7 }, { quarter: 'Q2', mens: 13, category: 7 },
      { quarter: 'Q3', mens: 15, category: 8 },
    ],
    caption: 'Meat outgrows the store three quarters on stock-up trips',
  },
  'ins-lulu-17-runclub-funnel': {
    kind: 'bar', xKey: 'source', series: ['cvr'], perBarColor: true,
    yTitle: 'World Foods CVR index',
    config: { cvr: { label: 'World Foods CVR' } },
    data: [
      { source: 'Cold prospect', cvr: 100, fill: MUTED },
      { source: 'Community shopper', cvr: 173, fill: TEAL },
    ],
    caption: 'Newcomer-community shoppers convert to World Foods far above cold prospects',
  },
};
