// ===========================================================================
// IGA — Québec full-service grocery banner (Sobeys / Empire)
// Representative campaign data + a full insight list + market news.
// Franchised Québec network + IGA West; French-language, Québec-sourced/local
// angle is central. KPI = ROAS; loyalty = Scene+; e-commerce = Voilà par IGA;
// own brands = Compliments / Panache. Main Québec competitors: Metro / Maxi /
// Super C (Metro uses "Moi" loyalty, NOT Scene+). Illustrative demo figures
// grounded in the real portfolio, audiences, and agency roster.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, PURPLE, GOLD, MUTED, GRID } from '../insight-visual-types';

export const MOLSON_COORS_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (IGA Creative / Sid Lee) ──
  { id: 'mc-coorslight-summer', name: 'Fresh & Produce — Summer Local Harvest Hero',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-coors-light',
    audiences: ['mc-lda-young', 'mc-value-mainstream'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'tiktok', 'spotify'], geos: ['national'], budgetMultiplier: 1.65,
    plannedBudget: 13_400_000, revPerConvRange: [48, 120], cvrModifier: 0.75, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-canadian-hockey', name: 'Boucherie — Grillades & Fête Nationale',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-molson-canadian',
    audiences: ['mc-sports-fans', 'mc-value-mainstream'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'facebook', 'instagram'], geos: ['national', 'ontario'], budgetMultiplier: 1.40,
    plannedBudget: 9_800_000, revPerConvRange: [44, 110], cvrModifier: 0.80, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-bluemoon-premium', name: 'Prepared Foods — Repas Prêts & Premium Occasions',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-blue-moon',
    audiences: ['mc-craft-curious'], objective: 'consideration', status: 'live',
    channels: ['instagram', 'ctv', 'ttd', 'spotify'], geos: ['national', 'bc'], budgetMultiplier: 0.95,
    plannedBudget: 5_200_000, revPerConvRange: [70, 160], cvrModifier: 0.90, cplCalibration: 0.55, revTrend: 0.0003 },

  // ── TIER 2 — REGIONAL / MEDIA (IGA Media / Touché) ──
  { id: 'mc-vizzy-flavor', name: 'Rachelle-Béry — Organic & Natural Push',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-vizzy',
    audiences: ['mc-seltzer-flavor', 'mc-lda-young'], objective: 'consideration', status: 'live',
    channels: ['tiktok', 'instagram', 'ttd', 'spotify'], geos: ['national', 'ontario'], budgetMultiplier: 1.10,
    plannedBudget: 6_600_000, revPerConvRange: [52, 130], cvrModifier: 0.95, cplCalibration: 0.55, revTrend: 0.0004 },
  { id: 'mc-millerlite-value', name: 'Boulangerie — Fresh-Baked Daily Value',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-miller-lite',
    audiences: ['mc-light-loyalists', 'mc-value-mainstream'], objective: 'consideration', status: 'live',
    channels: ['facebook', 'instagram', 'ooh'], geos: ['alberta', 'ontario'], budgetMultiplier: 0.85,
    plannedBudget: 4_200_000, revPerConvRange: [42, 104], cvrModifier: 0.85, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-coorslight-nba', name: 'Fresh & Produce — Back-to-School Co-Shop Surround',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-coors-light',
    audiences: ['mc-sports-fans', 'mc-lda-young'], objective: 'awareness', status: 'scheduled',
    channels: ['ctv', 'tiktok', 'spotify'], geos: ['national'], budgetMultiplier: 1.00,
    plannedBudget: 5_800_000, revPerConvRange: [48, 118], cvrModifier: 0.78, cplCalibration: 0.50, revTrend: 0.0003 },

  // ── TIER 3 — MARCHAND & LOCAL ──
  { id: 'mc-banquet-onpremise', name: 'Centre-Store — Marchand Flyer & In-Store Activation',
    enterprise: 'molson-coors', division: 'tier-3', agency: 'mc-field', productLine: 'mc-coors-banquet',
    audiences: ['mc-value-mainstream', 'mc-craft-curious'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['alberta', 'bc'], budgetMultiplier: 0.70,
    plannedBudget: 2_800_000, revPerConvRange: [40, 96], cvrModifier: 1.00, cplCalibration: 0.55, revTrend: 0.0003 },
  { id: 'mc-vizzy-retail-promo', name: 'Rachelle-Béry — Aisle Display & Scene+ Offer Redemption',
    enterprise: 'molson-coors', division: 'tier-3', agency: 'mc-field', productLine: 'mc-vizzy',
    audiences: ['mc-seltzer-flavor', 'mc-value-mainstream'], objective: 'conversion', status: 'live',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['ontario'], budgetMultiplier: 0.65,
    plannedBudget: 2_400_000, revPerConvRange: [50, 124], cvrModifier: 1.05, cplCalibration: 0.58, revTrend: 0.0004 },
];

export const MOLSON_COORS_NEWS: NewsItem[] = [
  { id: 'news-mc-nhl-playoffs', title: 'Fête Nationale & Summer BBQ Season Arrives Early in Québec — Grocery Basket Tracking Up Double Digits',
    source: 'La Presse', date: '2026-05-06', tags: ['grocery', 'sponsorships'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'With warm weather arriving early ahead of the Saint-Jean-Baptiste long weekend, grilling, fresh-produce and prepared-foods baskets are pacing well above last year, lifting CTV and social inventory demand during the run-up.',
    whyItMatters: 'IGA Boucherie and Fresh & Produce over-index with Québec grilling occasions. STRATIS flags a short, high-demand window where the Back-to-School Co-Shop Surround and grilling weight should be pulled forward before CTV CPMs spike.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-seltzer-category', title: 'Organic & Natural Grocery Returns to Growth in Québec — Local Sourcing Driving the Rebound',
    source: 'Nielsen Canada', date: '2026-05-03', tags: ['grocery', 'macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'Nielsen reports the Québec organic and natural-grocery category returned to volume growth, led by locally-sourced and lower-additive SKUs after two flat years.',
    whyItMatters: 'A tailwind for Rachelle-Béry precisely as the Organic & Natural push is live. STRATIS is correlating the category lift against Rachelle-Béry consideration and Scene+ offer redemption — see the linked recommendation.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-aluminum-tariff', title: 'Packaging & Freight Input Costs Rise on New Tariff Schedule — Margin Pressure Across Grocery',
    source: 'The Globe and Mail', date: '2026-04-30', tags: ['macro'], urgency: 'medium', regions: ['national'],
    summary: 'A revised tariff schedule lifted packaging and freight input costs, pressuring centre-store margins across the grocery industry heading into peak summer season.',
    whyItMatters: 'Margin pressure raises the bar on media efficiency for the summer flights. STRATIS is watching cost-per-reach-point to protect working-media ratio and ROAS as budgets tighten.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-abi-bud-light', title: 'Metro Lifts Québec Summer Flyer Spend ~15% — Heaviest Value Push in Three Years',
    source: 'Marketing Magazine', date: '2026-05-01', tags: ['competitors'], urgency: 'high', competitor: 'Metro',
    regions: ['national'], summary: 'Metro confirmed a ~15% increase in Québec summer media weight with a national CTV and OOH-led value plan beginning this month, anchored by its "Moi" loyalty program.',
    whyItMatters: 'Direct share-of-voice pressure on IGA Fresh & Produce and Boulangerie in the Québec value segment. Watch for CTV and OOH share-of-voice compression in the same markets.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-na-beer-growth', title: 'Voilà par IGA E-Commerce Posts Fourth Straight Year of Double-Digit Order Growth in Québec',
    source: 'Nielsen Canada', date: '2026-04-24', tags: ['macro', 'launch'], urgency: 'medium', regions: ['national'],
    summary: 'Online grocery via Voilà par IGA continued double-digit order growth, broadening beyond early adopters into mainstream weekly-shop and summer occasions.',
    whyItMatters: 'A structural channel shift adjacent to the core in-store business. Tracked at the brand level as a portfolio-whitespace signal; no active reallocation required yet.',
    enterprises: ['molson-coors'] },
];

export const MOLSON_COORS_RADAR_PINS = ['news-mc-nhl-playoffs', 'news-mc-seltzer-category', 'news-mc-abi-bud-light'];

export const MOLSON_COORS_INSIGHTS: Insight[] = [
  {
    id: 'ins-mc-01-portfolio-frequency', createdAt: todayISO,
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'ooh', 'instagram', 'tiktok'],
    title: 'Fresh & Produce, Boucherie and Boulangerie Are All Chasing the Same Québec Family Shopper in the Same Weekly-Shop Windows — Combined Frequency Hits 22x a Week',
    summary: "Three fresh departments target overlapping family-household and value-shopper audiences during the same CTV weekly-shop windows, with no portfolio-level cap. Deduped, the average reached Québec shopper sees ~22 IGA exposures a week — past the point where additional weight builds the banner rather than any single department. A portfolio cap and a clearer department-role split (Produce = local harvest, Boucherie = grilling, Boulangerie = fresh-baked daily) recovers wasted weight and sharpens each department's distinctiveness.",
    evidence: [
      'Deduped across the three fresh departments: ~22 exposures/week to the average reached family shopper',
      'Heaviest overlap is in shared CTV weekly-shop windows',
      'No portfolio-level frequency cap across departments',
      'Department roles are blurring where audiences and windows collide',
    ],
    confidence: 0.85,
    impactEstimate: 'A portfolio cap plus a sharper department-role split recovers over-delivered weight and improves per-department distinctiveness with no loss of banner reach.',
    recommendedAction: 'Set a portfolio-level frequency cap across the fresh departments and enforce a distinct department-role split in shared windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set a portfolio frequency cap', subtitle: 'ACROSS FRESH DEPARTMENTS', type: 'bidding', completed: false },
      { id: 's2', title: 'Enforce a distinct department-role split', subtitle: 'PRODUCE / GRILLING / BAKED', type: 'creative', completed: false },
      { id: 's3', title: 'Monitor combined shopper frequency', subtitle: 'STRATIS DEDUPES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-02-playoff-window', createdAt: at(1, '08:30:00'),
    enterprise: 'molson-coors', category: 'competitive-macro', scope: 'product', productLine: 'mc-coors-light',
    channels: ['ctv', 'tiktok', 'spotify'],
    title: 'Pull the Back-to-School Co-Shop Surround Forward Now — CTV CPMs Will Spike Before the Scheduled Start',
    summary: 'With warm weather and the Fête Nationale long weekend arriving early, grilling and fresh-produce demand is already pacing double digits ahead of last year, and CTV CPMs in summer-shop windows rise sharply once competitors set their flyer flights. The Co-Shop Surround is currently scheduled to start after that inflection. Pulling it forward locks lower CPMs and captures the shopper while basket intent peaks rather than after rivals have crowded in.',
    evidence: [
      'Summer-shop demand pacing double digits above last year',
      'CTV summer-window CPMs spike once competitor flyer flights set',
      'The Surround is scheduled to start after that inflection',
      'Competitor value weight is rising into the same windows',
    ],
    confidence: 0.83,
    impactEstimate: 'Advancing the flight locks lower CTV CPMs and captures peak summer-shop attention before rivals crowd the window.',
    recommendedAction: 'Advance the Back-to-School Co-Shop Surround to start before the competitor-driven CPM spike.',
    status: 'new',
    linkedNewsId: 'news-mc-nhl-playoffs',
    actionSteps: [
      { id: 's1', title: 'Advance the Surround start date', subtitle: 'BEFORE CPM SPIKE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Lock CTV inventory now', subtitle: 'SUMMER-SHOP WINDOWS', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-03-vizzy-tailwind', createdAt: at(3, '10:00:00'),
    enterprise: 'molson-coors', category: 'national-regional', scope: 'product', productLine: 'mc-vizzy',
    channels: ['tiktok', 'instagram', 'ttd'],
    title: 'The Organic & Natural Rebound Is Strongest in Ontario — Rachelle-Béry Weight Is Spread Evenly and Missing the Lift',
    summary: 'Nielsen shows the organic and natural-grocery rebound concentrated in Ontario locally-sourced SKUs, exactly Rachelle-Béry\'s positioning, but the Organic & Natural flight paces national-even and under-indexes Ontario relative to where category demand is actually growing. Re-weighting toward Ontario rides a confirmed category tailwind into Rachelle-Béry\'s strongest segment rather than spreading the same budget thin.',
    evidence: [
      'Category rebound is concentrated in Ontario, led by locally-sourced SKUs',
      'Rachelle-Béry Organic & Natural flight paces national-even',
      'Ontario is under-weighted relative to category growth',
      'Rachelle-Béry positioning matches the growing sub-segment',
    ],
    confidence: 0.80,
    impactEstimate: 'Re-weighting Rachelle-Béry toward Ontario rides a confirmed category tailwind into its strongest segment at the same budget.',
    recommendedAction: 'Re-weight the Rachelle-Béry Organic & Natural flight toward Ontario to match the concentrated category rebound.',
    status: 'new',
    linkedNewsId: 'news-mc-seltzer-category',
    actionSteps: [
      { id: 's1', title: 'Re-weight Rachelle-Béry toward Ontario', subtitle: 'MATCH CATEGORY GROWTH', type: 'budget', completed: false },
      { id: 's2', title: 'Lead with locally-sourced creative', subtitle: 'STRONGEST SUB-SEGMENT', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-04-creative-fatigue', createdAt: at(5, '12:30:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-coors-light',
    channels: ['tiktok', 'instagram'],
    title: 'The "Local Harvest" Hero Cut Is Fatiguing on TikTok Three Weeks Early — Completion Is Down Despite Rising Spend',
    summary: 'On TikTok, the Fresh & Produce hero cut\'s 3-second-view and completion rates have declined for two straight weeks while spend rose — the classic fatigue signature on a fast-cycling platform. The same cut still performs on CTV, so this is a platform-specific creative-wear issue, not a banner one. A short-form refresh or a rotation of existing alternates restores efficiency without touching the CTV buy.',
    evidence: [
      'TikTok 3s-view and completion rates down two consecutive weeks',
      'Spend rose over the same window — efficiency falling',
      'The same cut still performs on CTV',
      'Platform-specific wear, not a banner-level problem',
    ],
    confidence: 0.82,
    impactEstimate: 'A short-form refresh restores TikTok efficiency before fatigue spreads, with no change to the CTV buy.',
    recommendedAction: 'Refresh or rotate the Fresh & Produce short-form creative on TikTok; leave the CTV cut in place.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Rotate in fresh short-form cuts', subtitle: 'TIKTOK ONLY', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the CTV cut', subtitle: 'STILL PERFORMING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-05-channel-efficiency', createdAt: at(7, '09:30:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ooh', 'ctv', 'spotify'],
    title: 'OOH Is Absorbing 18% of Summer Budget at the Portfolio\'s Weakest Cost-per-Reach-Point — With Margin Pressure, That Ratio Has to Tighten',
    summary: 'Across the summer flights, OOH is delivering the portfolio\'s highest cost-per-incremental-reach-point while CTV and audio deliver more reach per dollar against the same shoppers. With packaging and freight costs squeezing margin, the working-media bar is higher this year. Shifting a portion of OOH weight into CTV and audio holds reach while improving the cost-per-reach-point — without abandoning the high-impact OOH placements that anchor the campaign.',
    evidence: [
      'OOH carries ~18% of summer budget at the weakest cost-per-reach-point',
      'CTV and audio deliver more incremental reach per dollar to the same shoppers',
      'Margin pressure from input costs raises the working-media bar',
      'A partial shift preserves anchor OOH placements',
    ],
    confidence: 0.76,
    impactEstimate: 'Shifting a portion of OOH into CTV and audio holds reach at a lower cost-per-reach-point, protecting working-media ratio and ROAS under margin pressure.',
    recommendedAction: 'Reallocate a portion of summer OOH weight into CTV and audio while retaining anchor OOH placements.',
    status: 'new',
    linkedNewsId: 'news-mc-aluminum-tariff',
    actionSteps: [
      { id: 's1', title: 'Shift a portion of OOH into CTV + audio', subtitle: 'HOLD REACH, LOWER CPRP', type: 'budget', completed: false },
      { id: 's2', title: 'Retain anchor OOH placements', subtitle: 'HIGH-IMPACT ONLY', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-06-agency-arbitrage', createdAt: at(10, '11:00:00'),
    enterprise: 'molson-coors', category: 'agency-arbitrage', scope: 'brand',
    channels: ['instagram', 'facebook', 'google-search'],
    title: 'Marchand & Local Is Driving Higher Redemption-per-Dollar Than National Promo — the Local Offer Mechanic Should Scale Up',
    summary: 'The Tier 3 Marchand & Local team\'s aisle-display and Scene+ offer-redemption mechanic is delivering more redemptions per media dollar than national promo activity on the same categories, because the offer is tied to a local store purchase moment. Rachelle-Béry and Centre-Store both show it. Lifting the local offer mechanic into national consideration flights — where the purchase moment can be replicated — scales a proven efficiency rather than leaving it siloed at the marchand level.',
    evidence: [
      'Marchand & Local redemption-per-dollar exceeds national promo on the same categories',
      'Advantage traces to a locally-tied store purchase-moment offer',
      'Pattern holds on both Rachelle-Béry and Centre-Store',
      'National flights do not currently use the local offer mechanic',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the marchand offer mechanic into national flights improves redemption efficiency on the same categories.',
    recommendedAction: 'Adopt the Marchand & Local offer-redemption mechanic in national consideration flights where the purchase moment replicates.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the marchand offer mechanic', subtitle: 'PURCHASE-MOMENT TIED', type: 'targeting', completed: false },
      { id: 's2', title: 'Scale into national flights', subtitle: 'RACHELLE-BÉRY + CENTRE-STORE FIRST', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-07-sports-overlap', createdAt: at(3, '09:20:00'),
    enterprise: 'molson-coors', category: 'audience-overlap', scope: 'brand',
    channels: ['ctv', 'tiktok', 'facebook'],
    title: 'Fresh & Produce and Boucherie Share ~40% of Their Summer-Grilling Shopper Reach — Deduping Extends Combined Reach',
    summary: 'The two flagship fresh departments reach the same summer-grilling family shopper about 40% of the time, so a large slice of their combined weight buys overlapping reach rather than incremental shoppers. Deduping the grilling-shopper audience across the two flights and reallocating the recovered weight extends combined unique reach with no new budget — and lets each department keep its own role in the summer-shop window.',
    evidence: [
      '~40% of grilling-shopper reach is shared between the two departments',
      'Overlap concentrates in shared CTV summer-shop windows',
      'No cross-department dedupe exists on the grilling-shopper audience',
      'Recovered weight converts directly to unique reach',
    ],
    confidence: 0.77,
    impactEstimate: 'Deduping the shared grilling-shopper audience converts overlapping weight into incremental unique reach.',
    recommendedAction: 'Dedupe the grilling-shopper audience across Fresh & Produce and Boucherie and reallocate recovered weight to unique reach.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Dedupe the shared grilling-shopper audience', subtitle: 'PRODUCE × BOUCHERIE', type: 'targeting', completed: false },
      { id: 's2', title: 'Reallocate recovered weight to unique reach', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-08-bluemoon-underreach', createdAt: at(8, '11:15:00'),
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'product', productLine: 'mc-blue-moon',
    channels: ['instagram', 'ctv', 'ttd'],
    title: 'Prepared Foods Earns the Highest Margin per Basket but Carries the Smallest Media Share in the Portfolio',
    summary: "Premium Prepared Foods contributes more margin per basket than the core fresh departments, yet it receives the least media weight — a mix skewed by volume rather than profit. Rebalancing a measured share of weight toward Prepared Foods' ready-meal and premium-occasion moments backs the portfolio's highest-margin category where incremental delivery earns the most.",
    evidence: [
      'Prepared Foods margin per basket indexes highest in the portfolio',
      'It carries the smallest media share of the active departments',
      'Weight is allocated by volume, not margin contribution',
      'Premium meal occasions are under-reached at current weight',
    ],
    confidence: 0.75,
    impactEstimate: 'Tilting weight toward the highest-margin category earns more profit per incremental impression than volume-led allocation.',
    recommendedAction: "Rebalance a measured share of portfolio weight toward Prepared Foods' premium meal occasions.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt weight toward Prepared Foods occasions', subtitle: 'MARGIN-LED, NOT VOLUME-LED', type: 'budget', completed: false },
      { id: 's2', title: 'Hold core fresh-department reach', subtitle: 'MEASURED SHIFT', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-09-budlight-sov', createdAt: at(2, '08:45:00'),
    enterprise: 'molson-coors', category: 'competitive-macro', scope: 'product', productLine: 'mc-coors-light',
    channels: ['ctv', 'ooh'],
    title: 'Metro\'s ~15% Summer Spend Lift Is Compressing IGA Share-of-Voice in CTV and OOH — the Gap Opens in the Exact Québec Markets That Matter',
    summary: 'Metro\'s heaviest Québec value push in three years lands on the same CTV and OOH inventory IGA Fresh & Produce depends on, and STRATIS is already measuring share-of-voice compression in the contested markets. Because the pressure is concentrated in CTV and OOH rather than spread evenly, a like-for-like budget match would overpay; a surgical defense that protects SOV in the highest-value summer-shop and commuter windows holds the banner\'s position at a fraction of the cost. Only a portfolio view catches that the squeeze is channel- and window-specific rather than province-flat.',
    evidence: [
      'Metro summer media weight up ~15%, concentrated in CTV and OOH',
      'IGA SOV compressing in the contested Québec markets',
      'Pressure is window-specific — summer-shop and commuter windows hardest hit',
      'A flat budget match would overpay versus a surgical SOV defense',
    ],
    confidence: 0.81,
    impactEstimate: 'A targeted SOV defense in the contested CTV and OOH windows holds IGA\'s position without matching the full competitive spend.',
    recommendedAction: 'Defend IGA SOV surgically in the contested CTV and OOH windows rather than matching total competitive spend.',
    status: 'new',
    linkedNewsId: 'news-mc-abi-bud-light',
    actionSteps: [
      { id: 's1', title: 'Concentrate defense in contested windows', subtitle: 'SUMMER-SHOP + COMMUTER', type: 'bidding', completed: false },
      { id: 's2', title: 'Hold non-contested weight flat', subtitle: 'NO FLAT MATCH', type: 'budget', completed: false },
      { id: 's3', title: 'Track SOV against Metro weekly', subtitle: 'STRATIS MEASURES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-10-na-whitespace', createdAt: at(4, '10:20:00'),
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'spotify', 'instagram'],
    title: 'Voilà par IGA E-Commerce Has Posted Four Years of Double-Digit Order Growth Into Weekly-Shop Occasions the Portfolio Already Owns — and Carries Almost No Brand Media Weight',
    summary: 'Online grocery via Voilà par IGA keeps compounding double digits, and its growth is moving into the exact weekly-shop and summer occasions where Fresh & Produce and Boucherie already command attention. The portfolio currently puts almost no brand media weight against the e-commerce occasion, leaving a structural whitespace adjacent to assets it already owns. A measured test against existing weekly-shop and summer audiences validates the channel at low risk before competitors define online grocery in Québec.',
    evidence: [
      'Voilà par IGA orders up double digits four straight years',
      'Growth is broadening into mainstream weekly-shop and summer occasions',
      'Those occasions overlap Fresh & Produce and Boucherie audiences',
      'Almost no portfolio brand media weight against the e-commerce occasion today',
    ],
    confidence: 0.73,
    impactEstimate: 'A low-risk test against owned weekly-shop and summer audiences validates the e-commerce occasion before rivals define it.',
    recommendedAction: 'Run a measured Voilà par IGA occasion test against existing weekly-shop and summer audiences before committing budget.',
    status: 'new',
    linkedNewsId: 'news-mc-na-beer-growth',
    actionSteps: [
      { id: 's1', title: 'Stand up a Voilà occasion test', subtitle: 'OWNED AUDIENCES FIRST', type: 'targeting', completed: false },
      { id: 's2', title: 'Cap spend at validation level', subtitle: 'LOW-RISK READ', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-11-spotify-vs-ctv', createdAt: at(6, '09:10:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'brand',
    channels: ['spotify', 'ctv'],
    title: 'Spotify Is Delivering Incremental Reach Against Young Foodies 25–39 at Roughly Half the Cost of CTV — Audio Is Carrying Frequency CTV Is Paying a Premium For',
    summary: 'Against the Young Foodies 25–39 audience, Spotify audio is adding incremental reach at about half CTV\'s cost-per-point, and a meaningful slice of CTV impressions is now buying frequency on shoppers audio already covers. Because audio and video are planned in separate silos, no one sees the overlap; STRATIS reads them together. Shifting incremental-reach goals to audio while keeping CTV for high-attention storytelling lowers blended cost-per-reach-point without cutting total reach.',
    evidence: [
      'Spotify cost-per-reach-point on Young Foodies 25–39 runs ~50% of CTV\'s',
      'A share of CTV impressions duplicates reach audio already holds',
      'Audio and video are planned in separate silos',
      'Blended cost-per-reach-point falls when audio carries incremental reach',
    ],
    confidence: 0.78,
    impactEstimate: 'Letting audio carry incremental reach against young-foodie audiences lowers blended cost-per-reach-point while CTV keeps the storytelling role.',
    recommendedAction: 'Shift incremental-reach goals against Young Foodies 25–39 to Spotify and reserve CTV for high-attention storytelling.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Move incremental-reach goals to audio', subtitle: 'YOUNG FOODIES 25–39', type: 'budget', completed: false },
      { id: 's2', title: 'Reserve CTV for high-attention story', subtitle: 'STORYTELLING ROLE', type: 'creative', completed: false },
      { id: 's3', title: 'Plan audio and video together', subtitle: 'DEDUPE THE SILO', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-mc-12-coviewing-cap', createdAt: at(5, '13:40:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'product', productLine: 'mc-molson-canadian',
    channels: ['ctv'],
    title: 'CTV Frequency Caps Are Set Per-Device, but Family Co-Viewing Means Two-Plus Shoppers Watch Each Impression — Real Per-Person Frequency Is Running ~1.8x Above Plan',
    summary: 'Boucherie\'s CTV caps are enforced at the device level, yet prime-time grilling-season programming is watched by households, not individuals — co-viewing multiplies the people behind each impression. STRATIS applies a co-viewing factor and finds true per-person frequency running about 1.8x the planned cap during summer-evening windows, quietly over-delivering weight the plan thinks it is holding back. Adjusting the device cap by the co-viewing factor restores the intended per-person frequency and frees impressions for incremental reach.',
    evidence: [
      'CTV caps enforced per-device, not per-person',
      'Prime-time grilling-season programming averages 2+ co-viewers per screen',
      'True per-person frequency running ~1.8x the planned cap',
      'Over-delivery is invisible without a co-viewing adjustment',
    ],
    confidence: 0.79,
    impactEstimate: 'Adjusting the device cap by the co-viewing factor restores planned per-person frequency and frees impressions for incremental reach.',
    recommendedAction: 'Lower the per-device CTV cap by the co-viewing factor to restore intended per-person frequency in summer-evening windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Apply a co-viewing factor to CTV caps', subtitle: '~1.8x ADJUSTMENT', type: 'bidding', completed: false },
      { id: 's2', title: 'Redeploy freed impressions to reach', subtitle: 'SUMMER-EVENING WINDOWS', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-13-onpremise-retail', createdAt: at(9, '11:30:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'product', productLine: 'mc-coors-banquet',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'Centre-Store Spends Evenly Across Online and In-Store Offers, but Redemption Lands Almost 2-to-1 in the In-Store Aisle Moment',
    summary: 'Centre-Store\'s marchand budget splits roughly evenly between online (Voilà) and in-store aisle offers, yet offer redemption concentrates nearly 2-to-1 in the in-store moment, where the marchand\'s local relevance cue and the aisle purchase decision line up. Online messaging is working harder for a smaller return. Tilting the offer split toward in-store — and timing weight to peak weekend shop windows — lifts redemption efficiency without new budget.',
    evidence: [
      'Marchand budget splits roughly 50/50 in-store vs online',
      'Redemption concentrates nearly 2-to-1 in the in-store aisle moment',
      'In-store aligns with the local-relevance cue and aisle purchase decision',
      'Online spend returns less redemption per dollar',
    ],
    confidence: 0.74,
    impactEstimate: 'Tilting the offer split toward in-store and peak weekend windows lifts redemption efficiency at the same budget.',
    recommendedAction: 'Rebalance Centre-Store marchand weight toward in-store offers and peak weekend-shop windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt the offer split to in-store', subtitle: 'AISLE MOMENT WINS', type: 'budget', completed: false },
      { id: 's2', title: 'Time weight to weekend-shop windows', subtitle: 'PURCHASE DECISION', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-14-vizzy-flavor-rank', createdAt: at(7, '14:05:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-vizzy',
    channels: ['tiktok', 'instagram'],
    title: 'Rachelle-Béry\'s Organic Categories Run Equal Creative Weight, but Three Categories Drive the Consideration Lift While Two Are Quietly Diluting the Flight',
    summary: 'Rachelle-Béry rotates its organic-category creative at roughly equal weight, but consideration lift is concentrated in the top three categories while two underperformers sit below the flight average and drag blended efficiency. On a fast platform like TikTok, equal rotation hides the spread. Reweighting impressions toward the winning categories — and retiring or reshooting the laggards — sharpens the whole flight just as the organic category tailwind builds.',
    evidence: [
      'Organic-category creative rotates at roughly equal weight',
      'Top three categories carry the consideration lift',
      'Two categories sit below flight-average and dilute blended efficiency',
      'Equal rotation masks the per-category spread on TikTok',
    ],
    confidence: 0.80,
    impactEstimate: 'Reweighting toward the winning categories and retiring laggards lifts blended consideration efficiency at the same spend.',
    recommendedAction: 'Reweight Rachelle-Béry impressions toward the top-performing organic categories and retire or reshoot the laggards.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Reweight to winning organic categories', subtitle: 'TOP THREE', type: 'creative', completed: false },
      { id: 's2', title: 'Retire or reshoot the laggards', subtitle: 'BELOW FLIGHT AVG', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-15-quebec-heritage', createdAt: at(11, '10:45:00'),
    enterprise: 'molson-coors', category: 'national-regional', scope: 'product', productLine: 'mc-molson-canadian',
    channels: ['facebook', 'instagram', 'ctv'],
    title: 'Boucherie\'s Québec-Sourced Message Over-Indexes in Québec, but the Flight Runs the National "Grillades" Cut There — a Local French Creative Fit Is Being Left on the Table',
    summary: 'In Québec, IGA\'s Québec-sourced and local-butcher cues resonate well above the national average, yet the Boucherie grilling flight serves the same national creative into the market with no local adaptation. STRATIS sees the banner-affinity gap between Québec and national that a generic cut leaves unrealized. A French-language, Québec-sourced variant tuned to the province lifts resonance where the banner is already strong, without disturbing the national grilling narrative.',
    evidence: [
      'Québec-sourced and local-butcher cues over-index in Québec',
      'The national grilling cut runs unchanged in-market',
      'Québec banner affinity exceeds the national average',
      'No French-language Québec-sourced variant currently in rotation',
    ],
    confidence: 0.76,
    impactEstimate: 'A Québec-tuned French-language Québec-sourced variant lifts resonance where the banner is strongest, without disturbing the national narrative.',
    recommendedAction: 'Run a Québec-specific French-language Québec-sourced cut for Boucherie alongside the national grilling flight.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Produce a Québec-sourced variant', subtitle: 'FRENCH-LANGUAGE, LOCAL CUE', type: 'creative', completed: false },
      { id: 's2', title: 'Serve it only in Québec', subtitle: 'HOLD NATIONAL CUT ELSEWHERE', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-mc-16-millerlite-wear', createdAt: at(8, '12:50:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-miller-lite',
    channels: ['facebook', 'instagram'],
    title: 'Boulangerie\'s Fresh-Baked Value Message Is Wearing in Alberta but Still Fresh in Ontario — One National Creative Calendar Is Masking Two Different Fatigue Curves',
    summary: 'Boulangerie runs a single fresh-baked value-message creative on one national rotation, but the Alberta market — where the flight launched earlier and runs heavier — is showing clear message wear while Ontario is still building. A national calendar treats them as one curve and refreshes too late for Alberta and too early for Ontario. Splitting the refresh cadence by market restores Alberta efficiency now and lets Ontario keep compounding on the proven cut.',
    evidence: [
      'Single fresh-baked value-message creative on one national rotation',
      'Alberta launched earlier and runs heavier — showing message wear',
      'Ontario response is still building on the same cut',
      'A national calendar refreshes too late for AB, too early for ON',
    ],
    confidence: 0.78,
    impactEstimate: 'Splitting refresh cadence by market restores Alberta efficiency while letting Ontario keep compounding on the proven creative.',
    recommendedAction: 'Split the Boulangerie value-message refresh cadence by market — refresh Alberta now, hold Ontario.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Refresh the Alberta value cut now', subtitle: 'WEAR DETECTED', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the Ontario cut', subtitle: 'STILL BUILDING', type: 'creative', completed: false },
      { id: 's3', title: 'Split refresh cadence by market', subtitle: 'TWO CURVES, NOT ONE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-17-craft-crossshop', createdAt: at(13, '09:55:00'),
    enterprise: 'molson-coors', category: 'audience-overlap', scope: 'product', productLine: 'mc-blue-moon',
    channels: ['instagram', 'ttd', 'spotify'],
    title: 'Québec-Sourced Seekers Who Buy Prepared Foods Cross-Shop Rachelle-Béry at Nearly Twice the Portfolio Rate — but the Two Categories Never Sequence Their Messaging',
    summary: 'STRATIS finds that Québec-sourced seekers who buy Prepared Foods cross-shop Rachelle-Béry at almost double the portfolio-average rate, sharing a local, premium-occasion mindset. Yet the two categories plan in separate silos and never sequence their messaging, so the portfolio pays twice to reach one receptive audience rather than warming it once and handing it across. A shared Québec-sourced segment with sequenced creative turns the overlap into a portfolio-level cross-sell instead of duplicated spend.',
    evidence: [
      'Prepared Foods Québec-sourced buyers cross-shop Rachelle-Béry at ~1.9x the portfolio rate',
      'Both categories index on local, premium-occasion mindset',
      'The two flights plan in separate silos with no sequencing',
      'The shared audience is reached and paid for twice',
    ],
    confidence: 0.75,
    impactEstimate: 'A shared Québec-sourced segment with sequenced creative converts duplicated spend into a portfolio cross-sell.',
    recommendedAction: 'Build a shared Québec-sourced segment and sequence Prepared Foods and Rachelle-Béry messaging instead of buying the audience twice.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Build a shared Québec-sourced segment', subtitle: 'PREPARED FOODS × RACHELLE-BÉRY', type: 'targeting', completed: false },
      { id: 's2', title: 'Sequence the two categories\' messaging', subtitle: 'WARM ONCE, HAND ACROSS', type: 'creative', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const MOLSON_COORS_VISUALS: Record<string, InsightVisual> = {
  'ins-mc-01-portfolio-frequency': {
    kind: 'bar', xKey: 'brand', series: ['freq'], perBarColor: true,
    yTitle: 'Weekly frequency (family shopper)',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { brand: 'Fresh & Produce', freq: 9, fill: MUTED },
      { brand: 'Boucherie', freq: 8, fill: MUTED },
      { brand: 'Boulangerie', freq: 6, fill: MUTED },
      { brand: 'Combined', freq: 22, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 12, label: 'Effective max ~12', color: TEAL }],
    caption: 'Three fresh departments buy the same shopper — combined exposure hits 22×/week',
  },
  'ins-mc-02-playoff-window': {
    kind: 'line', xKey: 'week', series: ['cpm'],
    yTitle: 'CTV summer-window CPM ($)',
    config: { cpm: { label: 'CTV CPM', color: RED } },
    data: [
      { week: 'W1', cpm: 28 }, { week: 'W2', cpm: 29 }, { week: 'W3', cpm: 31 },
      { week: 'W4', cpm: 38 }, { week: 'W5', cpm: 44 }, { week: 'W6', cpm: 46 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'Competitor flyers set', color: GRID }],
    caption: 'CTV CPMs spike once competitor flyers set — the surround is scheduled after',
  },
  'ins-mc-03-vizzy-tailwind': {
    kind: 'bar', xKey: 'region', series: ['growth', 'budget'],
    yTitle: 'Category growth % · budget share %',
    config: { growth: { label: 'Organic category growth', color: TEAL }, budget: { label: 'Rachelle-Béry budget share', color: PURPLE } },
    data: [
      { region: 'ON', growth: 18, budget: 25 },
      { region: 'QC', growth: 9, budget: 25 },
      { region: 'AB', growth: 7, budget: 25 },
      { region: 'BC', growth: 6, budget: 25 },
    ],
    caption: 'Rebound concentrates in Ontario — Rachelle-Béry weight is spread flat',
  },
  'ins-mc-04-creative-fatigue': {
    kind: 'line', xKey: 'week', series: ['completion', 'spend'],
    yTitle: 'Indexed to 100',
    config: { completion: { label: 'TikTok completion', color: RED }, spend: { label: 'Spend', color: BLUE } },
    data: [
      { week: 'W1', completion: 100, spend: 100 }, { week: 'W2', completion: 98, spend: 104 },
      { week: 'W3', completion: 94, spend: 109 }, { week: 'W4', completion: 90, spend: 114 },
      { week: 'W5', completion: 88, spend: 118 },
    ],
    caption: 'Completion falls while spend rises — fatigue before peak season',
  },
  'ins-mc-05-channel-efficiency': {
    kind: 'bar', xKey: 'channel', series: ['cprp'], perBarColor: true,
    yTitle: 'Cost per reach-point ($K)',
    config: { cprp: { label: 'Cost per reach-point' } },
    data: [
      { channel: 'OOH', cprp: 14, fill: RED },
      { channel: 'Social', cprp: 9, fill: MUTED },
      { channel: 'CTV', cprp: 8, fill: TEAL },
      { channel: 'Audio', cprp: 7, fill: TEAL },
    ],
    caption: 'OOH carries 18% of budget at the weakest cost-per-reach-point',
  },
  'ins-mc-06-agency-arbitrage': {
    kind: 'bar', xKey: 'brand', series: ['national', 'field'],
    yTitle: 'Redemptions per $ (index)',
    config: { national: { label: 'National promo', color: RED }, field: { label: 'Marchand & Local', color: TEAL } },
    data: [
      { brand: 'Rachelle-Béry', national: 100, field: 158 },
      { brand: 'Centre-Store', national: 100, field: 141 },
    ],
    caption: 'Marchand redemption-per-dollar beats national promo on the same categories',
  },
  'ins-mc-07-sports-overlap': {
    kind: 'pie', nameKey: 'seg', valueKey: 'share', series: ['share'],
    config: { shared: { label: 'Shared reach', color: RED }, unique: { label: 'Unique reach', color: TEAL } },
    legend: [{ label: 'Shared grilling-shopper reach', color: RED }, { label: 'Unique reach', color: TEAL }],
    data: [{ seg: 'shared', share: 40, fill: RED }, { seg: 'unique', share: 60, fill: TEAL }],
    caption: 'Fresh & Produce & Boucherie share ~40% of grilling-shopper reach',
  },
  'ins-mc-08-bluemoon-underreach': {
    kind: 'bar', xKey: 'brand', series: ['margin', 'media'],
    yTitle: 'Margin per basket · media share',
    config: { margin: { label: 'Margin per basket (index)', color: GOLD }, media: { label: 'Media share %', color: PURPLE } },
    data: [
      { brand: 'Fresh & Produce', margin: 100, media: 34 },
      { brand: 'Boucherie', margin: 104, media: 25 },
      { brand: 'Prepared Foods', margin: 138, media: 11 },
      { brand: 'Rachelle-Béry', margin: 122, media: 16 },
    ],
    caption: 'Prepared Foods earns the most margin per basket but carries the least weight',
  },
  'ins-mc-09-budlight-sov': {
    kind: 'bar', xKey: 'window', series: ['coors', 'bud'],
    yTitle: 'Share of voice %',
    config: { coors: { label: 'IGA SOV', color: TEAL }, bud: { label: 'Metro SOV', color: RED } },
    data: [
      { window: 'Summer-shop CTV', coors: 38, bud: 44 },
      { window: 'Commuter OOH', coors: 41, bud: 46 },
      { window: 'General CTV', coors: 49, bud: 38 },
      { window: 'Social', coors: 52, bud: 33 },
    ],
    caption: 'Metro\'s lift compresses IGA SOV in summer-shop + commuter windows',
  },
  'ins-mc-10-na-whitespace': {
    kind: 'line', xKey: 'year', series: ['growth'],
    yTitle: 'Voilà par IGA order growth %',
    config: { growth: { label: 'Channel growth', color: TEAL } },
    data: [
      { year: 'Y1', growth: 11 }, { year: 'Y2', growth: 13 },
      { year: 'Y3', growth: 12 }, { year: 'Y4', growth: 15 },
    ],
    refLines: [{ axis: 'y', value: 0, label: 'Brand weight: ~0', color: RED }],
    caption: 'Four years of double-digit Voilà order growth — almost no brand media weight',
  },
  'ins-mc-11-spotify-vs-ctv': {
    kind: 'bar', xKey: 'channel', series: ['cprp'], perBarColor: true,
    yTitle: 'Cost per reach-point on Young Foodies 25–39 ($K)',
    config: { cprp: { label: 'Cost per reach-point' } },
    data: [
      { channel: 'CTV', cprp: 12, fill: RED },
      { channel: 'Spotify', cprp: 6, fill: TEAL },
    ],
    refLines: [{ axis: 'y', value: 9, label: 'Blended target', color: GRID }],
    caption: 'Audio adds incremental young-foodie reach at ~half CTV\'s cost-per-point',
  },
  'ins-mc-12-coviewing-cap': {
    kind: 'bar', xKey: 'metric', series: ['freq'], perBarColor: true,
    yTitle: 'Frequency in summer-evening windows',
    config: { freq: { label: 'Frequency' } },
    data: [
      { metric: 'Planned (device)', freq: 5.0, fill: TEAL },
      { metric: 'True (per-person)', freq: 9.0, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 5, label: 'Intended cap', color: GRID }],
    caption: 'Co-viewing pushes true per-person frequency ~1.8x above the device cap',
  },
  'ins-mc-13-onpremise-retail': {
    kind: 'bar', xKey: 'occasion', series: ['budget', 'redemption'],
    yTitle: 'Budget share % · redemption share %',
    config: { budget: { label: 'Budget share', color: PURPLE }, redemption: { label: 'Redemption share', color: TEAL } },
    data: [
      { occasion: 'In-store', budget: 50, redemption: 64 },
      { occasion: 'Online', budget: 50, redemption: 36 },
    ],
    caption: 'Even budget split, but redemption lands nearly 2-to-1 in-store',
  },
  'ins-mc-14-vizzy-flavor-rank': {
    kind: 'bar', xKey: 'flavor', series: ['lift'], perBarColor: true,
    yTitle: 'Consideration lift (index)',
    config: { lift: { label: 'Consideration lift' } },
    data: [
      { flavor: 'Fresh Produce', lift: 134, fill: TEAL },
      { flavor: 'Pantry Staples', lift: 121, fill: TEAL },
      { flavor: 'Dairy & Eggs', lift: 112, fill: TEAL },
      { flavor: 'Frozen', lift: 86, fill: RED },
      { flavor: 'Snacks', lift: 79, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Flight average', color: GRID }],
    caption: 'Three categories carry the lift; two sit below average and dilute the flight',
  },
  'ins-mc-15-quebec-heritage': {
    kind: 'bar', xKey: 'market', series: ['affinity'], perBarColor: true,
    yTitle: 'Québec-sourced message affinity (index)',
    config: { affinity: { label: 'Québec-sourced affinity' } },
    data: [
      { market: 'Quebec', affinity: 128, fill: BLUE },
      { market: 'National', affinity: 100, fill: MUTED },
      { market: 'Ontario', affinity: 96, fill: MUTED },
      { market: 'Alberta', affinity: 91, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'National avg', color: GRID }],
    caption: 'Québec-sourced over-indexes in Québec, yet the national cut runs there unchanged',
  },
  'ins-mc-16-millerlite-wear': {
    kind: 'line', xKey: 'week', series: ['alberta', 'ontario'],
    yTitle: 'Value-message engagement (indexed)',
    config: { alberta: { label: 'Alberta', color: RED }, ontario: { label: 'Ontario', color: TEAL } },
    data: [
      { week: 'W1', alberta: 100, ontario: 92 },
      { week: 'W2', alberta: 97, ontario: 96 },
      { week: 'W3', alberta: 91, ontario: 100 },
      { week: 'W4', alberta: 84, ontario: 103 },
      { week: 'W5', alberta: 79, ontario: 105 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'Curves diverge', color: GRID }],
    caption: 'One national cut hides two curves — Alberta wears as Ontario builds',
  },
  'ins-mc-17-craft-crossshop': {
    kind: 'scatter', xKey: 'x', series: ['y'], xName: 'Prepared Foods affinity (index)', yName: 'Rachelle-Béry cross-shop rate (index)',
    perBarColor: true,
    config: { y: { label: 'Cross-shop rate' } },
    legend: [{ label: 'Québec-sourced (Prepared Foods buyers)', color: PURPLE }, { label: 'Portfolio average', color: MUTED }],
    data: [
      { x: 142, y: 190, fill: PURPLE, name: 'Québec-sourced' },
      { x: 118, y: 152, fill: PURPLE, name: 'Premium-occasion' },
      { x: 100, y: 100, fill: MUTED, name: 'Portfolio avg' },
      { x: 88, y: 84, fill: MUTED, name: 'Value-shopper' },
    ],
    caption: 'Prepared Foods Québec-sourced buyers cross-shop Rachelle-Béry at ~1.9x portfolio rate',
  },
};
