// ===========================================================================
// Molson Coors — CPG / Beverage client instance
// Representative campaign data + a full insight list + market news.
// Brand-led, awareness-heavy media; "conversions" proxy promo/offer redemptions
// and store-locator actions. Illustrative demo figures grounded in the real
// portfolio, audiences, and agency roster.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, PURPLE, GOLD, MUTED, GRID } from '../insight-visual-types';

export const MOLSON_COORS_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (Rethink) ──
  { id: 'mc-coorslight-summer', name: 'Coors Light — Made to Chill Summer Hero',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-coors-light',
    audiences: ['mc-lda-young', 'mc-value-mainstream'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'tiktok', 'spotify'], geos: ['national'], budgetMultiplier: 1.65,
    plannedBudget: 13_400_000, revPerConvRange: [48, 120], cvrModifier: 0.75, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-canadian-hockey', name: 'Molson Canadian — Hockey & The North',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-molson-canadian',
    audiences: ['mc-sports-fans', 'mc-value-mainstream'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'facebook', 'instagram'], geos: ['national', 'ontario'], budgetMultiplier: 1.40,
    plannedBudget: 9_800_000, revPerConvRange: [44, 110], cvrModifier: 0.80, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-bluemoon-premium', name: 'Blue Moon — Brunch & Premium Occasions',
    enterprise: 'molson-coors', division: 'tier-1', agency: 'mc-rethink', productLine: 'mc-blue-moon',
    audiences: ['mc-craft-curious'], objective: 'consideration', status: 'live',
    channels: ['instagram', 'ctv', 'ttd', 'spotify'], geos: ['national', 'bc'], budgetMultiplier: 0.95,
    plannedBudget: 5_200_000, revPerConvRange: [70, 160], cvrModifier: 0.90, cplCalibration: 0.55, revTrend: 0.0003 },

  // ── TIER 2 — REGIONAL / MEDIA (MediaCom) ──
  { id: 'mc-vizzy-flavor', name: 'Vizzy — Flavor-Forward Seltzer Push',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-vizzy',
    audiences: ['mc-seltzer-flavor', 'mc-lda-young'], objective: 'consideration', status: 'live',
    channels: ['tiktok', 'instagram', 'ttd', 'spotify'], geos: ['national', 'ontario'], budgetMultiplier: 1.10,
    plannedBudget: 6_600_000, revPerConvRange: [52, 130], cvrModifier: 0.95, cplCalibration: 0.55, revTrend: 0.0004 },
  { id: 'mc-millerlite-value', name: 'Miller Lite — Original Light Value',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-miller-lite',
    audiences: ['mc-light-loyalists', 'mc-value-mainstream'], objective: 'consideration', status: 'live',
    channels: ['facebook', 'instagram', 'ooh'], geos: ['alberta', 'ontario'], budgetMultiplier: 0.85,
    plannedBudget: 4_200_000, revPerConvRange: [42, 104], cvrModifier: 0.85, cplCalibration: 0.50, revTrend: 0.0002 },
  { id: 'mc-coorslight-nba', name: 'Coors Light — Playoff Co-Viewing Surround',
    enterprise: 'molson-coors', division: 'tier-2', agency: 'mc-mediacom', productLine: 'mc-coors-light',
    audiences: ['mc-sports-fans', 'mc-lda-young'], objective: 'awareness', status: 'scheduled',
    channels: ['ctv', 'tiktok', 'spotify'], geos: ['national'], budgetMultiplier: 1.00,
    plannedBudget: 5_800_000, revPerConvRange: [48, 118], cvrModifier: 0.78, cplCalibration: 0.50, revTrend: 0.0003 },

  // ── TIER 3 — FIELD & ON-PREMISE ──
  { id: 'mc-banquet-onpremise', name: 'Coors Banquet — On-Premise & Bar Activation',
    enterprise: 'molson-coors', division: 'tier-3', agency: 'mc-field', productLine: 'mc-coors-banquet',
    audiences: ['mc-value-mainstream', 'mc-craft-curious'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['alberta', 'bc'], budgetMultiplier: 0.70,
    plannedBudget: 2_800_000, revPerConvRange: [40, 96], cvrModifier: 1.00, cplCalibration: 0.55, revTrend: 0.0003 },
  { id: 'mc-vizzy-retail-promo', name: 'Vizzy — Retail Display & Offer Redemption',
    enterprise: 'molson-coors', division: 'tier-3', agency: 'mc-field', productLine: 'mc-vizzy',
    audiences: ['mc-seltzer-flavor', 'mc-value-mainstream'], objective: 'conversion', status: 'live',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['ontario'], budgetMultiplier: 0.65,
    plannedBudget: 2_400_000, revPerConvRange: [50, 124], cvrModifier: 1.05, cplCalibration: 0.58, revTrend: 0.0004 },
];

export const MOLSON_COORS_NEWS: NewsItem[] = [
  { id: 'news-mc-nhl-playoffs', title: 'NHL Confirms All Three Canadian Teams in Playoffs — Co-Viewing Audience Tracking Up Double Digits',
    source: 'Sportsnet', date: '2026-05-06', tags: ['sports', 'sponsorships'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'With three Canadian teams advancing, national playoff co-viewing is pacing well above last year, lifting CTV and social inventory demand during game windows.',
    whyItMatters: 'Molson Canadian and Coors Light over-index with playoff co-viewers. STRATIS flags a short, high-demand window where the Playoff Co-Viewing Surround should be pulled forward before CTV CPMs spike.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-seltzer-category', title: 'Hard-Seltzer Category Returns to Growth in Canada — Flavor-Forward SKUs Driving the Rebound',
    source: 'Nielsen Canada', date: '2026-05-03', tags: ['competitors', 'macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'Nielsen reports the Canadian hard-seltzer category returned to volume growth, led by flavor-forward and lower-sugar SKUs after two flat years.',
    whyItMatters: 'A tailwind for Vizzy precisely as the Flavor-Forward push is live. STRATIS is correlating the category lift against Vizzy consideration and retail redemption — see the linked recommendation.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-aluminum-tariff', title: 'Aluminum Input Costs Rise on New Tariff Schedule — Packaging Margin Pressure Across Beverage',
    source: 'The Globe and Mail', date: '2026-04-30', tags: ['macro'], urgency: 'medium', regions: ['national'],
    summary: 'A revised tariff schedule lifted aluminum input costs, pressuring can-packaging margins across the beverage industry heading into peak summer season.',
    whyItMatters: 'Margin pressure raises the bar on media efficiency for the summer flights. STRATIS is watching cost-per-reach-point to protect working-media ratio as budgets tighten.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-abi-bud-light', title: 'AB InBev Lifts Bud Light Summer Spend ~15% — Heaviest Light-Lager Push in Three Years',
    source: 'Marketing Magazine', date: '2026-05-01', tags: ['competitors'], urgency: 'high', competitor: 'AB InBev',
    regions: ['national'], summary: 'AB InBev confirmed a ~15% increase in Bud Light summer media weight with a national CTV and OOH-led plan beginning this month.',
    whyItMatters: 'Direct SOV pressure on Coors Light and Miller Lite in the light-lager segment. Watch for CTV and OOH share-of-voice compression in the same markets.',
    enterprises: ['molson-coors'] },
  { id: 'news-mc-na-beer-growth', title: 'Non-Alcoholic Beer Posts Fourth Straight Year of Double-Digit Growth in Canada',
    source: 'Nielsen Canada', date: '2026-04-24', tags: ['macro', 'launch'], urgency: 'medium', regions: ['national'],
    summary: 'Non-alcoholic beer continued double-digit growth, broadening beyond early adopters into mainstream summer and sport occasions.',
    whyItMatters: 'A structural occasion shift adjacent to the core portfolio. Tracked at the brand level as a portfolio-whitespace signal; no active reallocation required yet.',
    enterprises: ['molson-coors'] },
];

export const MOLSON_COORS_RADAR_PINS = ['news-mc-nhl-playoffs', 'news-mc-seltzer-category', 'news-mc-abi-bud-light'];

export const MOLSON_COORS_INSIGHTS: Insight[] = [
  {
    id: 'ins-mc-01-portfolio-frequency', createdAt: todayISO,
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'ooh', 'instagram', 'tiktok'],
    title: 'Coors Light, Molson Canadian and Miller Lite Are Buying the Same Sports Fan in the Same Game Windows — Combined Frequency Hits 22x a Week',
    summary: "Three light-lager brands target overlapping sports-fan and value-mainstream audiences during the same CTV game windows, with no portfolio-level cap. Deduped, the average reached fan sees ~22 Molson Coors exposures a week — past the point where additional weight builds the category rather than any single brand. A portfolio cap and a clearer brand-role split (Coors Light = chill, Canadian = hockey, Miller Lite = value) recovers wasted weight and sharpens each brand's distinctiveness.",
    evidence: [
      'Deduped across the three light-lager brands: ~22 exposures/week to the average reached sports fan',
      'Heaviest overlap is in shared CTV game windows',
      'No portfolio-level frequency cap across brands',
      'Brand roles are blurring where audiences and windows collide',
    ],
    confidence: 0.85,
    impactEstimate: 'A portfolio cap plus a sharper brand-role split recovers over-delivered weight and improves per-brand distinctiveness with no loss of category reach.',
    recommendedAction: 'Set a portfolio-level frequency cap across the light-lager brands and enforce a distinct brand-role split in shared windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set a portfolio frequency cap', subtitle: 'ACROSS LIGHT-LAGER BRANDS', type: 'bidding', completed: false },
      { id: 's2', title: 'Enforce a distinct brand-role split', subtitle: 'CHILL / HOCKEY / VALUE', type: 'creative', completed: false },
      { id: 's3', title: 'Monitor combined fan frequency', subtitle: 'STRATIS DEDUPES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-02-playoff-window', createdAt: at(1, '08:30:00'),
    enterprise: 'molson-coors', category: 'competitive-macro', scope: 'product', productLine: 'mc-coors-light',
    channels: ['ctv', 'tiktok', 'spotify'],
    title: 'Pull the Playoff Co-Viewing Surround Forward Now — CTV CPMs Will Spike Before the Scheduled Start',
    summary: 'With all three Canadian NHL teams advancing, co-viewing demand is already pacing double digits ahead of last year, and CTV CPMs in game windows rise sharply once the next round is set. The Playoff Co-Viewing Surround is currently scheduled to start after that inflection. Pulling it forward locks lower CPMs and captures the audience while attention peaks rather than after rivals have crowded in.',
    evidence: [
      'Playoff co-viewing pacing double digits above last year',
      'CTV game-window CPMs spike once the next round is confirmed',
      'The Surround is scheduled to start after that inflection',
      'Competitor light-lager weight is rising into the same windows',
    ],
    confidence: 0.83,
    impactEstimate: 'Advancing the flight locks lower CTV CPMs and captures peak co-viewing attention before rivals crowd the window.',
    recommendedAction: 'Advance the Playoff Co-Viewing Surround to start before the next-round CPM spike.',
    status: 'new',
    linkedNewsId: 'news-mc-nhl-playoffs',
    actionSteps: [
      { id: 's1', title: 'Advance the Surround start date', subtitle: 'BEFORE CPM SPIKE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Lock CTV inventory now', subtitle: 'GAME WINDOWS', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-03-vizzy-tailwind', createdAt: at(3, '10:00:00'),
    enterprise: 'molson-coors', category: 'national-regional', scope: 'product', productLine: 'mc-vizzy',
    channels: ['tiktok', 'instagram', 'ttd'],
    title: 'The Seltzer Category Rebound Is Strongest in Ontario — Vizzy Weight Is Spread Evenly and Missing the Lift',
    summary: 'Nielsen shows the hard-seltzer rebound concentrated in Ontario flavor-forward SKUs, exactly Vizzy\'s positioning, but the Flavor-Forward flight paces national-even and under-indexes Ontario relative to where category demand is actually growing. Re-weighting toward Ontario rides a confirmed category tailwind into Vizzy\'s strongest segment rather than spreading the same budget thin.',
    evidence: [
      'Category rebound is concentrated in Ontario, led by flavor-forward SKUs',
      'Vizzy Flavor-Forward flight paces national-even',
      'Ontario is under-weighted relative to category growth',
      'Vizzy positioning matches the growing sub-segment',
    ],
    confidence: 0.80,
    impactEstimate: 'Re-weighting Vizzy toward Ontario rides a confirmed category tailwind into its strongest segment at the same budget.',
    recommendedAction: 'Re-weight the Vizzy Flavor-Forward flight toward Ontario to match the concentrated category rebound.',
    status: 'new',
    linkedNewsId: 'news-mc-seltzer-category',
    actionSteps: [
      { id: 's1', title: 'Re-weight Vizzy toward Ontario', subtitle: 'MATCH CATEGORY GROWTH', type: 'budget', completed: false },
      { id: 's2', title: 'Lead with flavor-forward creative', subtitle: 'STRONGEST SUB-SEGMENT', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-04-creative-fatigue', createdAt: at(5, '12:30:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-coors-light',
    channels: ['tiktok', 'instagram'],
    title: 'The "Made to Chill" Hero Cut Is Fatiguing on TikTok Three Weeks Early — Completion Is Down Despite Rising Spend',
    summary: 'On TikTok, the Coors Light hero cut\'s 3-second-view and completion rates have declined for two straight weeks while spend rose — the classic fatigue signature on a fast-cycling platform. The same cut still performs on CTV, so this is a platform-specific creative-wear issue, not a brand one. A short-form refresh or a rotation of existing alternates restores efficiency without touching the CTV buy.',
    evidence: [
      'TikTok 3s-view and completion rates down two consecutive weeks',
      'Spend rose over the same window — efficiency falling',
      'The same cut still performs on CTV',
      'Platform-specific wear, not a brand-level problem',
    ],
    confidence: 0.82,
    impactEstimate: 'A short-form refresh restores TikTok efficiency before fatigue spreads, with no change to the CTV buy.',
    recommendedAction: 'Refresh or rotate the Coors Light short-form creative on TikTok; leave the CTV cut in place.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Rotate in fresh short-form cuts', subtitle: 'TIKTOK ONLY', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the CTV cut', subtitle: 'STILL PERFORMING', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-05-channel-efficiency', createdAt: at(7, '09:30:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ooh', 'ctv', 'spotify'],
    title: 'OOH Is Absorbing 18% of Summer Budget at the Portfolio\'s Weakest Cost-per-Reach-Point — With Aluminum Margin Pressure, That Ratio Has to Tighten',
    summary: 'Across the summer flights, OOH is delivering the portfolio\'s highest cost-per-incremental-reach-point while CTV and audio deliver more reach per dollar against the same audiences. With aluminum input costs squeezing margin, the working-media bar is higher this year. Shifting a portion of OOH weight into CTV and audio holds reach while improving the cost-per-reach-point — without abandoning the high-impact OOH placements that anchor the campaign.',
    evidence: [
      'OOH carries ~18% of summer budget at the weakest cost-per-reach-point',
      'CTV and audio deliver more incremental reach per dollar to the same audiences',
      'Aluminum margin pressure raises the working-media bar',
      'A partial shift preserves anchor OOH placements',
    ],
    confidence: 0.76,
    impactEstimate: 'Shifting a portion of OOH into CTV and audio holds reach at a lower cost-per-reach-point, protecting working-media ratio under margin pressure.',
    recommendedAction: 'Reallocate a portion of summer OOH weight into CTV and audio while retaining anchor OOH placements.',
    status: 'new',
    linkedNewsId: 'news-mc-aluminum-tariff',
    actionSteps: [
      { id: 's1', title: 'Shift a portion of OOH into CTV + audio', subtitle: 'HOLD REACH, LOWER CPRP', type: 'budget', completed: false },
      { id: 's2', title: 'Retain anchor OOH placements', subtitle: 'HIGH-IMPACT ONLY', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-06-agency-arbitrage', createdAt: at(10, '11:00:00'),
    enterprise: 'molson-coors', category: 'agency-arbitrage', scope: 'brand',
    channels: ['instagram', 'facebook', 'google-search'],
    title: 'Field & On-Premise Is Driving Higher Redemption-per-Dollar Than National Promo — the Local Offer Mechanic Should Scale Up',
    summary: 'The Tier 3 Field & On-Premise team\'s retail-display and offer-redemption mechanic is delivering more redemptions per media dollar than national promo activity on the same SKUs, because the offer is tied to a local purchase moment. Vizzy and Coors Banquet both show it. Lifting the local offer mechanic into national consideration flights — where the purchase moment can be replicated — scales a proven efficiency rather than leaving it siloed at the field level.',
    evidence: [
      'Field & On-Premise redemption-per-dollar exceeds national promo on the same SKUs',
      'Advantage traces to a locally-tied purchase-moment offer',
      'Pattern holds on both Vizzy and Coors Banquet',
      'National flights do not currently use the local offer mechanic',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the field offer mechanic into national flights improves redemption efficiency on the same SKUs.',
    recommendedAction: 'Adopt the Field & On-Premise offer-redemption mechanic in national consideration flights where the purchase moment replicates.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the field offer mechanic', subtitle: 'PURCHASE-MOMENT TIED', type: 'targeting', completed: false },
      { id: 's2', title: 'Scale into national flights', subtitle: 'VIZZY + BANQUET FIRST', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-07-sports-overlap', createdAt: at(3, '09:20:00'),
    enterprise: 'molson-coors', category: 'audience-overlap', scope: 'brand',
    channels: ['ctv', 'tiktok', 'facebook'],
    title: 'Coors Light and Molson Canadian Share ~40% of Their NHL Sports-Fan Reach — Deduping Extends Combined Reach',
    summary: 'The two flagship lagers reach the same playoff sports fan about 40% of the time, so a large slice of their combined weight buys overlapping reach rather than incremental fans. Deduping the sports-fan audience across the two flights and reallocating the recovered weight extends combined unique reach with no new budget — and lets each brand keep its own role in the game window.',
    evidence: [
      '~40% of sports-fan reach is shared between the two brands',
      'Overlap concentrates in shared CTV game windows',
      'No cross-brand dedupe exists on the sports-fan audience',
      'Recovered weight converts directly to unique reach',
    ],
    confidence: 0.77,
    impactEstimate: 'Deduping the shared sports-fan audience converts overlapping weight into incremental unique reach.',
    recommendedAction: 'Dedupe the sports-fan audience across Coors Light and Molson Canadian and reallocate recovered weight to unique reach.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Dedupe the shared sports-fan audience', subtitle: 'COORS LIGHT × MOLSON CANADIAN', type: 'targeting', completed: false },
      { id: 's2', title: 'Reallocate recovered weight to unique reach', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-08-bluemoon-underreach', createdAt: at(8, '11:15:00'),
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'product', productLine: 'mc-blue-moon',
    channels: ['instagram', 'ctv', 'ttd'],
    title: 'Blue Moon Earns the Highest Margin per Case but Carries the Smallest Media Share in the Portfolio',
    summary: "Premium Blue Moon contributes more margin per case than the core lagers, yet it receives the least media weight — a mix skewed by volume rather than profit. Rebalancing a measured share of weight toward Blue Moon's premium brunch and occasion moments backs the portfolio's highest-margin unit where incremental delivery earns the most.",
    evidence: [
      'Blue Moon margin per case indexes highest in the portfolio',
      'It carries the smallest media share of the active brands',
      'Weight is allocated by volume, not margin contribution',
      'Premium occasions are under-reached at current weight',
    ],
    confidence: 0.75,
    impactEstimate: 'Tilting weight toward the highest-margin brand earns more profit per incremental impression than volume-led allocation.',
    recommendedAction: "Rebalance a measured share of portfolio weight toward Blue Moon's premium occasions.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt weight toward Blue Moon premium occasions', subtitle: 'MARGIN-LED, NOT VOLUME-LED', type: 'budget', completed: false },
      { id: 's2', title: 'Hold core-lager reach', subtitle: 'MEASURED SHIFT', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-09-budlight-sov', createdAt: at(2, '08:45:00'),
    enterprise: 'molson-coors', category: 'competitive-macro', scope: 'product', productLine: 'mc-coors-light',
    channels: ['ctv', 'ooh'],
    title: 'Bud Light\'s ~15% Summer Spend Lift Is Compressing Coors Light Share-of-Voice in CTV and OOH — the Gap Opens in the Exact Markets That Matter',
    summary: 'AB InBev\'s heaviest light-lager push in three years lands on the same national CTV and OOH inventory Coors Light depends on, and STRATIS is already measuring share-of-voice compression in the contested markets. Because the pressure is concentrated in CTV and OOH rather than spread evenly, a like-for-like budget match would overpay; a surgical defense that protects SOV in the highest-value game and commuter windows holds the brand\'s position at a fraction of the cost. Only a portfolio view catches that the squeeze is channel- and window-specific rather than national-flat.',
    evidence: [
      'Bud Light summer media weight up ~15%, concentrated in CTV and OOH',
      'Coors Light SOV compressing in the contested national markets',
      'Pressure is window-specific — game and commuter windows hardest hit',
      'A flat budget match would overpay versus a surgical SOV defense',
    ],
    confidence: 0.81,
    impactEstimate: 'A targeted SOV defense in the contested CTV and OOH windows holds Coors Light\'s position without matching the full competitive spend.',
    recommendedAction: 'Defend Coors Light SOV surgically in the contested CTV and OOH windows rather than matching total competitive spend.',
    status: 'new',
    linkedNewsId: 'news-mc-abi-bud-light',
    actionSteps: [
      { id: 's1', title: 'Concentrate defense in contested windows', subtitle: 'GAME + COMMUTER', type: 'bidding', completed: false },
      { id: 's2', title: 'Hold non-contested weight flat', subtitle: 'NO FLAT MATCH', type: 'budget', completed: false },
      { id: 's3', title: 'Track SOV against Bud Light weekly', subtitle: 'STRATIS MEASURES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-10-na-whitespace', createdAt: at(4, '10:20:00'),
    enterprise: 'molson-coors', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'spotify', 'instagram'],
    title: 'Non-Alcoholic Beer Has Posted Four Years of Double-Digit Growth Into Summer and Sport Occasions the Portfolio Already Owns — and Carries Zero Media Weight',
    summary: 'Non-alcoholic beer keeps compounding double digits, and its growth is moving into the exact summer and sport co-viewing occasions where Coors Light and Molson Canadian already command attention. The portfolio currently puts no media weight against the occasion, leaving a structural whitespace adjacent to assets it already owns. A measured test against existing sport and summer audiences validates the occasion at low risk before competitors define the category in Canada.',
    evidence: [
      'Non-alcoholic beer up double digits four straight years',
      'Growth is broadening into mainstream summer and sport occasions',
      'Those occasions overlap Coors Light and Molson Canadian audiences',
      'Zero portfolio media weight against the occasion today',
    ],
    confidence: 0.73,
    impactEstimate: 'A low-risk test against owned sport and summer audiences validates the non-alcoholic occasion before rivals define it.',
    recommendedAction: 'Run a measured non-alcoholic occasion test against existing sport and summer audiences before committing budget.',
    status: 'new',
    linkedNewsId: 'news-mc-na-beer-growth',
    actionSteps: [
      { id: 's1', title: 'Stand up a non-alc occasion test', subtitle: 'OWNED AUDIENCES FIRST', type: 'targeting', completed: false },
      { id: 's2', title: 'Cap spend at validation level', subtitle: 'LOW-RISK READ', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-11-spotify-vs-ctv', createdAt: at(6, '09:10:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'brand',
    channels: ['spotify', 'ctv'],
    title: 'Spotify Is Delivering Incremental Reach Against LDA 21–34 at Roughly Half the Cost of CTV — Audio Is Carrying Frequency CTV Is Paying a Premium For',
    summary: 'Against the LDA 21–34 audience, Spotify audio is adding incremental reach at about half CTV\'s cost-per-point, and a meaningful slice of CTV impressions is now buying frequency on fans audio already covers. Because audio and video are planned in separate silos, no one sees the overlap; STRATIS reads them together. Shifting incremental-reach goals to audio while keeping CTV for high-attention storytelling lowers blended cost-per-reach-point without cutting total reach.',
    evidence: [
      'Spotify cost-per-reach-point on LDA 21–34 runs ~50% of CTV\'s',
      'A share of CTV impressions duplicates reach audio already holds',
      'Audio and video are planned in separate silos',
      'Blended cost-per-reach-point falls when audio carries incremental reach',
    ],
    confidence: 0.78,
    impactEstimate: 'Letting audio carry incremental reach against young-adult audiences lowers blended cost-per-reach-point while CTV keeps the storytelling role.',
    recommendedAction: 'Shift incremental-reach goals against LDA 21–34 to Spotify and reserve CTV for high-attention storytelling.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Move incremental-reach goals to audio', subtitle: 'LDA 21–34', type: 'budget', completed: false },
      { id: 's2', title: 'Reserve CTV for high-attention story', subtitle: 'STORYTELLING ROLE', type: 'creative', completed: false },
      { id: 's3', title: 'Plan audio and video together', subtitle: 'DEDUPE THE SILO', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-mc-12-coviewing-cap', createdAt: at(5, '13:40:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'product', productLine: 'mc-molson-canadian',
    channels: ['ctv'],
    title: 'CTV Frequency Caps Are Set Per-Device, but Playoff Co-Viewing Means Two-Plus Fans Watch Each Impression — Real Per-Person Frequency Is Running ~1.8x Above Plan',
    summary: 'Molson Canadian\'s CTV caps are enforced at the device level, yet playoff games are watched by households, not individuals — co-viewing multiplies the people behind each impression. STRATIS applies a co-viewing factor and finds true per-person frequency running about 1.8x the planned cap during game windows, quietly over-delivering weight the plan thinks it is holding back. Adjusting the device cap by the co-viewing factor restores the intended per-person frequency and frees impressions for incremental reach.',
    evidence: [
      'CTV caps enforced per-device, not per-person',
      'Playoff games average 2+ co-viewers per screen',
      'True per-person frequency running ~1.8x the planned cap',
      'Over-delivery is invisible without a co-viewing adjustment',
    ],
    confidence: 0.79,
    impactEstimate: 'Adjusting the device cap by the co-viewing factor restores planned per-person frequency and frees impressions for incremental reach.',
    recommendedAction: 'Lower the per-device CTV cap by the co-viewing factor to restore intended per-person frequency in game windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Apply a co-viewing factor to CTV caps', subtitle: '~1.8x ADJUSTMENT', type: 'bidding', completed: false },
      { id: 's2', title: 'Redeploy freed impressions to reach', subtitle: 'GAME WINDOWS', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-mc-13-onpremise-retail', createdAt: at(9, '11:30:00'),
    enterprise: 'molson-coors', category: 'tactical-efficiency', scope: 'product', productLine: 'mc-coors-banquet',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'Coors Banquet Spends Evenly Across On-Premise and Retail Occasions, but Redemption Lands Almost 2-to-1 in the On-Premise Bar Moment',
    summary: 'Coors Banquet\'s field budget splits roughly evenly between on-premise (bar) and retail occasions, yet offer redemption concentrates nearly 2-to-1 in the on-premise moment, where the brand\'s Western heritage cue and the bar purchase decision line up. Retail messaging is working harder for a smaller return. Tilting the occasion split toward on-premise — and timing weight to evening bar windows — lifts redemption efficiency without new budget.',
    evidence: [
      'Field budget splits roughly 50/50 on-premise vs retail',
      'Redemption concentrates nearly 2-to-1 in the on-premise bar moment',
      'On-premise aligns with the Western heritage cue and bar purchase decision',
      'Retail spend returns less redemption per dollar',
    ],
    confidence: 0.74,
    impactEstimate: 'Tilting the occasion split toward on-premise and evening bar windows lifts redemption efficiency at the same budget.',
    recommendedAction: 'Rebalance Coors Banquet field weight toward on-premise occasions and evening bar windows.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Tilt the occasion split to on-premise', subtitle: 'BAR MOMENT WINS', type: 'budget', completed: false },
      { id: 's2', title: 'Time weight to evening bar windows', subtitle: 'PURCHASE DECISION', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-14-vizzy-flavor-rank', createdAt: at(7, '14:05:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-vizzy',
    channels: ['tiktok', 'instagram'],
    title: 'Vizzy\'s Flavor SKUs Run Equal Creative Weight, but Three Flavors Drive the Consideration Lift While Two Are Quietly Diluting the Flight',
    summary: 'Vizzy rotates its flavor-SKU creative at roughly equal weight, but consideration lift is concentrated in the top three flavors while two underperformers sit below the flight average and drag blended efficiency. On a fast platform like TikTok, equal rotation hides the spread. Reweighting impressions toward the winning flavors — and retiring or reshooting the laggards — sharpens the whole flight just as the seltzer category tailwind builds.',
    evidence: [
      'Flavor-SKU creative rotates at roughly equal weight',
      'Top three flavors carry the consideration lift',
      'Two flavors sit below flight-average and dilute blended efficiency',
      'Equal rotation masks the per-flavor spread on TikTok',
    ],
    confidence: 0.80,
    impactEstimate: 'Reweighting toward the winning flavors and retiring laggards lifts blended consideration efficiency at the same spend.',
    recommendedAction: 'Reweight Vizzy impressions toward the top-performing flavor SKUs and retire or reshoot the laggards.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Reweight to winning flavor SKUs', subtitle: 'TOP THREE', type: 'creative', completed: false },
      { id: 's2', title: 'Retire or reshoot the laggards', subtitle: 'BELOW FLIGHT AVG', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-mc-15-quebec-heritage', createdAt: at(11, '10:45:00'),
    enterprise: 'molson-coors', category: 'national-regional', scope: 'product', productLine: 'mc-molson-canadian',
    channels: ['facebook', 'instagram', 'ctv'],
    title: 'Molson Canadian\'s Heritage Message Over-Indexes in Quebec, but the Flight Runs the National "Hockey & The North" Cut There — a Local Creative Fit Is Being Left on the Table',
    summary: 'In Quebec, Molson\'s heritage and local-brewing cues resonate well above the national average, yet the Hockey & The North flight serves the same national creative into the market with no local adaptation. STRATIS sees the brand-affinity gap between Quebec and national that a generic cut leaves unrealized. A French-language, heritage-led variant tuned to Quebec lifts resonance where the brand is already strong, without disturbing the national hockey narrative.',
    evidence: [
      'Heritage and local-brewing cues over-index in Quebec',
      'The national Hockey & The North cut runs unchanged in-market',
      'Quebec brand affinity exceeds the national average',
      'No French-language heritage variant currently in rotation',
    ],
    confidence: 0.76,
    impactEstimate: 'A Quebec-tuned French-language heritage variant lifts resonance where the brand is strongest, without disturbing the national narrative.',
    recommendedAction: 'Run a Quebec-specific French-language heritage cut for Molson Canadian alongside the national hockey flight.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Produce a Quebec heritage variant', subtitle: 'FRENCH-LANGUAGE, LOCAL CUE', type: 'creative', completed: false },
      { id: 's2', title: 'Serve it only in Quebec', subtitle: 'HOLD NATIONAL CUT ELSEWHERE', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-mc-16-millerlite-wear', createdAt: at(8, '12:50:00'),
    enterprise: 'molson-coors', category: 'creative-performance', scope: 'product', productLine: 'mc-miller-lite',
    channels: ['facebook', 'instagram'],
    title: 'Miller Lite\'s Value Message Is Wearing in Alberta but Still Fresh in Ontario — One National Creative Calendar Is Masking Two Different Fatigue Curves',
    summary: 'Miller Lite runs a single value-message creative on one national rotation, but the Alberta market — where the flight launched earlier and runs heavier — is showing clear message wear while Ontario is still building. A national calendar treats them as one curve and refreshes too late for Alberta and too early for Ontario. Splitting the refresh cadence by market restores Alberta efficiency now and lets Ontario keep compounding on the proven cut.',
    evidence: [
      'Single value-message creative on one national rotation',
      'Alberta launched earlier and runs heavier — showing message wear',
      'Ontario response is still building on the same cut',
      'A national calendar refreshes too late for AB, too early for ON',
    ],
    confidence: 0.78,
    impactEstimate: 'Splitting refresh cadence by market restores Alberta efficiency while letting Ontario keep compounding on the proven creative.',
    recommendedAction: 'Split the Miller Lite value-message refresh cadence by market — refresh Alberta now, hold Ontario.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Refresh the Alberta value cut now', subtitle: 'WEAR DETECTED', type: 'creative', completed: false },
      { id: 's2', title: 'Hold the Ontario cut', subtitle: 'STILL BUILDING', type: 'creative', completed: false },
      { id: 's3', title: 'Split refresh cadence by market', subtitle: 'TWO CURVES, NOT ONE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-mc-17-craft-crossshop', createdAt: at(13, '09:55:00'),
    enterprise: 'molson-coors', category: 'audience-overlap', scope: 'product', productLine: 'mc-blue-moon',
    channels: ['instagram', 'ttd', 'spotify'],
    title: 'Craft-Curious Drinkers Who Buy Blue Moon Cross-Shop Vizzy at Nearly Twice the Portfolio Rate — but the Two Brands Never Sequence Their Messaging',
    summary: 'STRATIS finds that craft-curious buyers of Blue Moon cross-shop Vizzy at almost double the portfolio-average rate, sharing a flavor-forward, premium-occasion mindset. Yet the two brands plan in separate silos and never sequence their messaging, so the portfolio pays twice to reach one receptive audience rather than warming it once and handing it across. A shared craft-curious segment with sequenced creative turns the overlap into a portfolio-level cross-sell instead of duplicated spend.',
    evidence: [
      'Blue Moon craft-curious buyers cross-shop Vizzy at ~1.9x the portfolio rate',
      'Both brands index on flavor-forward, premium-occasion mindset',
      'The two flights plan in separate silos with no sequencing',
      'The shared audience is reached and paid for twice',
    ],
    confidence: 0.75,
    impactEstimate: 'A shared craft-curious segment with sequenced creative converts duplicated spend into a portfolio cross-sell.',
    recommendedAction: 'Build a shared craft-curious segment and sequence Blue Moon and Vizzy messaging instead of buying the audience twice.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Build a shared craft-curious segment', subtitle: 'BLUE MOON × VIZZY', type: 'targeting', completed: false },
      { id: 's2', title: 'Sequence the two brands\' messaging', subtitle: 'WARM ONCE, HAND ACROSS', type: 'creative', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const MOLSON_COORS_VISUALS: Record<string, InsightVisual> = {
  'ins-mc-01-portfolio-frequency': {
    kind: 'bar', xKey: 'brand', series: ['freq'], perBarColor: true,
    yTitle: 'Weekly frequency (sports fan)',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { brand: 'Coors Light', freq: 9, fill: MUTED },
      { brand: 'Molson Canadian', freq: 8, fill: MUTED },
      { brand: 'Miller Lite', freq: 6, fill: MUTED },
      { brand: 'Combined', freq: 22, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 12, label: 'Effective max ~12', color: TEAL }],
    caption: 'Three light lagers buy the same fan — combined exposure hits 22×/week',
  },
  'ins-mc-02-playoff-window': {
    kind: 'line', xKey: 'week', series: ['cpm'],
    yTitle: 'CTV game-window CPM ($)',
    config: { cpm: { label: 'CTV CPM', color: RED } },
    data: [
      { week: 'W1', cpm: 28 }, { week: 'W2', cpm: 29 }, { week: 'W3', cpm: 31 },
      { week: 'W4', cpm: 38 }, { week: 'W5', cpm: 44 }, { week: 'W6', cpm: 46 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'Next round set', color: GRID }],
    caption: 'CTV CPMs spike once the round is set — the surround is scheduled after',
  },
  'ins-mc-03-vizzy-tailwind': {
    kind: 'bar', xKey: 'region', series: ['growth', 'budget'],
    yTitle: 'Category growth % · budget share %',
    config: { growth: { label: 'Seltzer category growth', color: TEAL }, budget: { label: 'Vizzy budget share', color: PURPLE } },
    data: [
      { region: 'ON', growth: 18, budget: 25 },
      { region: 'QC', growth: 9, budget: 25 },
      { region: 'AB', growth: 7, budget: 25 },
      { region: 'BC', growth: 6, budget: 25 },
    ],
    caption: 'Rebound concentrates in Ontario — Vizzy weight is spread flat',
  },
  'ins-mc-04-creative-fatigue': {
    kind: 'line', xKey: 'week', series: ['completion', 'spend'],
    yTitle: 'Indexed to 100',
    config: { completion: { label: 'TikTok completion', color: RED }, spend: { label: 'Spend', color: BLUE } },
    data: [
      { week: 'W1', completion: 100, spend: 100 }, { week: 'W2', completion: 98, spend: 104 },
      { week: 'W3', completion: 94, spend: 109 }, { week: 'W4', completion: 90, spend: 114 },
      { week: 'W5', completion: 88, spend: 118 },
    ],
    caption: 'Completion falls while spend rises — fatigue before peak season',
  },
  'ins-mc-05-channel-efficiency': {
    kind: 'bar', xKey: 'channel', series: ['cprp'], perBarColor: true,
    yTitle: 'Cost per reach-point ($K)',
    config: { cprp: { label: 'Cost per reach-point' } },
    data: [
      { channel: 'OOH', cprp: 14, fill: RED },
      { channel: 'Social', cprp: 9, fill: MUTED },
      { channel: 'CTV', cprp: 8, fill: TEAL },
      { channel: 'Audio', cprp: 7, fill: TEAL },
    ],
    caption: 'OOH carries 18% of budget at the weakest cost-per-reach-point',
  },
  'ins-mc-06-agency-arbitrage': {
    kind: 'bar', xKey: 'brand', series: ['national', 'field'],
    yTitle: 'Redemptions per $ (index)',
    config: { national: { label: 'National promo', color: RED }, field: { label: 'Field & On-Premise', color: TEAL } },
    data: [
      { brand: 'Vizzy', national: 100, field: 158 },
      { brand: 'Coors Banquet', national: 100, field: 141 },
    ],
    caption: 'Field redemption-per-dollar beats national promo on the same SKUs',
  },
  'ins-mc-07-sports-overlap': {
    kind: 'pie', nameKey: 'seg', valueKey: 'share', series: ['share'],
    config: { shared: { label: 'Shared reach', color: RED }, unique: { label: 'Unique reach', color: TEAL } },
    legend: [{ label: 'Shared sports-fan reach', color: RED }, { label: 'Unique reach', color: TEAL }],
    data: [{ seg: 'shared', share: 40, fill: RED }, { seg: 'unique', share: 60, fill: TEAL }],
    caption: 'Coors Light & Molson Canadian share ~40% of NHL fan reach',
  },
  'ins-mc-08-bluemoon-underreach': {
    kind: 'bar', xKey: 'brand', series: ['margin', 'media'],
    yTitle: 'Margin per case · media share',
    config: { margin: { label: 'Margin per case (index)', color: GOLD }, media: { label: 'Media share %', color: PURPLE } },
    data: [
      { brand: 'Coors Light', margin: 100, media: 34 },
      { brand: 'Molson Canadian', margin: 104, media: 25 },
      { brand: 'Blue Moon', margin: 138, media: 11 },
      { brand: 'Vizzy', margin: 122, media: 16 },
    ],
    caption: 'Blue Moon earns the most margin per case but carries the least weight',
  },
  'ins-mc-09-budlight-sov': {
    kind: 'bar', xKey: 'window', series: ['coors', 'bud'],
    yTitle: 'Share of voice %',
    config: { coors: { label: 'Coors Light SOV', color: TEAL }, bud: { label: 'Bud Light SOV', color: RED } },
    data: [
      { window: 'Game CTV', coors: 38, bud: 44 },
      { window: 'Commuter OOH', coors: 41, bud: 46 },
      { window: 'General CTV', coors: 49, bud: 38 },
      { window: 'Social', coors: 52, bud: 33 },
    ],
    caption: 'Bud Light\'s lift compresses Coors Light SOV in game + commuter windows',
  },
  'ins-mc-10-na-whitespace': {
    kind: 'line', xKey: 'year', series: ['growth'],
    yTitle: 'Non-alc beer volume growth %',
    config: { growth: { label: 'Category growth', color: TEAL } },
    data: [
      { year: 'Y1', growth: 11 }, { year: 'Y2', growth: 13 },
      { year: 'Y3', growth: 12 }, { year: 'Y4', growth: 15 },
    ],
    refLines: [{ axis: 'y', value: 0, label: 'Portfolio weight: 0', color: RED }],
    caption: 'Four years of double-digit non-alc growth — zero portfolio media weight',
  },
  'ins-mc-11-spotify-vs-ctv': {
    kind: 'bar', xKey: 'channel', series: ['cprp'], perBarColor: true,
    yTitle: 'Cost per reach-point on LDA 21–34 ($K)',
    config: { cprp: { label: 'Cost per reach-point' } },
    data: [
      { channel: 'CTV', cprp: 12, fill: RED },
      { channel: 'Spotify', cprp: 6, fill: TEAL },
    ],
    refLines: [{ axis: 'y', value: 9, label: 'Blended target', color: GRID }],
    caption: 'Audio adds incremental young-adult reach at ~half CTV\'s cost-per-point',
  },
  'ins-mc-12-coviewing-cap': {
    kind: 'bar', xKey: 'metric', series: ['freq'], perBarColor: true,
    yTitle: 'Frequency in game windows',
    config: { freq: { label: 'Frequency' } },
    data: [
      { metric: 'Planned (device)', freq: 5.0, fill: TEAL },
      { metric: 'True (per-person)', freq: 9.0, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 5, label: 'Intended cap', color: GRID }],
    caption: 'Co-viewing pushes true per-person frequency ~1.8x above the device cap',
  },
  'ins-mc-13-onpremise-retail': {
    kind: 'bar', xKey: 'occasion', series: ['budget', 'redemption'],
    yTitle: 'Budget share % · redemption share %',
    config: { budget: { label: 'Budget share', color: PURPLE }, redemption: { label: 'Redemption share', color: TEAL } },
    data: [
      { occasion: 'On-premise', budget: 50, redemption: 64 },
      { occasion: 'Retail', budget: 50, redemption: 36 },
    ],
    caption: 'Even budget split, but redemption lands nearly 2-to-1 on-premise',
  },
  'ins-mc-14-vizzy-flavor-rank': {
    kind: 'bar', xKey: 'flavor', series: ['lift'], perBarColor: true,
    yTitle: 'Consideration lift (index)',
    config: { lift: { label: 'Consideration lift' } },
    data: [
      { flavor: 'Blueberry', lift: 134, fill: TEAL },
      { flavor: 'Pineapple', lift: 121, fill: TEAL },
      { flavor: 'Black Cherry', lift: 112, fill: TEAL },
      { flavor: 'Watermelon', lift: 86, fill: RED },
      { flavor: 'Mango', lift: 79, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Flight average', color: GRID }],
    caption: 'Three flavors carry the lift; two sit below average and dilute the flight',
  },
  'ins-mc-15-quebec-heritage': {
    kind: 'bar', xKey: 'market', series: ['affinity'], perBarColor: true,
    yTitle: 'Heritage-message affinity (index)',
    config: { affinity: { label: 'Heritage affinity' } },
    data: [
      { market: 'Quebec', affinity: 128, fill: BLUE },
      { market: 'National', affinity: 100, fill: MUTED },
      { market: 'Ontario', affinity: 96, fill: MUTED },
      { market: 'Alberta', affinity: 91, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'National avg', color: GRID }],
    caption: 'Heritage over-indexes in Quebec, yet the national cut runs there unchanged',
  },
  'ins-mc-16-millerlite-wear': {
    kind: 'line', xKey: 'week', series: ['alberta', 'ontario'],
    yTitle: 'Value-message engagement (indexed)',
    config: { alberta: { label: 'Alberta', color: RED }, ontario: { label: 'Ontario', color: TEAL } },
    data: [
      { week: 'W1', alberta: 100, ontario: 92 },
      { week: 'W2', alberta: 97, ontario: 96 },
      { week: 'W3', alberta: 91, ontario: 100 },
      { week: 'W4', alberta: 84, ontario: 103 },
      { week: 'W5', alberta: 79, ontario: 105 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'Curves diverge', color: GRID }],
    caption: 'One national cut hides two curves — Alberta wears as Ontario builds',
  },
  'ins-mc-17-craft-crossshop': {
    kind: 'scatter', xKey: 'x', series: ['y'], xName: 'Blue Moon affinity (index)', yName: 'Vizzy cross-shop rate (index)',
    perBarColor: true,
    config: { y: { label: 'Cross-shop rate' } },
    legend: [{ label: 'Craft-curious (Blue Moon buyers)', color: PURPLE }, { label: 'Portfolio average', color: MUTED }],
    data: [
      { x: 142, y: 190, fill: PURPLE, name: 'Craft-curious' },
      { x: 118, y: 152, fill: PURPLE, name: 'Premium-occasion' },
      { x: 100, y: 100, fill: MUTED, name: 'Portfolio avg' },
      { x: 88, y: 84, fill: MUTED, name: 'Value-mainstream' },
    ],
    caption: 'Blue Moon craft-curious buyers cross-shop Vizzy at ~1.9x portfolio rate',
  },
};
