// ===========================================================================
// RBC (Royal Bank of Canada) — Financial Services client instance
// Representative campaign data + a full insight list + market news.
// Figures are illustrative (a demo dataset), grounded in RBC's real product
// lines, audiences, and agency roster.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, PURPLE, MUTED, GRID, BLUE, GOLD } from '../insight-visual-types';

export const RBC_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (BBDO Toronto) ──
  { id: 'rbc-everyday-brand', name: 'Everyday Banking — Ideas Worth Banking On',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-chequing',
    audiences: ['rbc-switchers', 'rbc-students'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'spotify'], geos: ['national'], budgetMultiplier: 1.70,
    plannedBudget: 14_800_000, revPerConvRange: [320, 720], cvrModifier: 0.95, cplCalibration: 0.70, revTrend: 0.0003 },
  { id: 'rbc-mortgages-spring', name: 'Mortgages — Spring Home-Buying Window',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-mortgages',
    audiences: ['rbc-first-home', 'rbc-mass-affluent'], objective: 'consideration', status: 'live',
    channels: ['google-search', 'facebook', 'instagram', 'ttd'], geos: ['national', 'ontario', 'bc'], budgetMultiplier: 1.55,
    plannedBudget: 12_200_000, revPerConvRange: [1_900, 3_300], cvrModifier: 1.15, cplCalibration: 0.85, revTrend: 0.0006 },
  { id: 'rbc-avion-conquest', name: 'Avion Rewards — Card Switcher Conquest',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-avion',
    audiences: ['rbc-switchers', 'rbc-mass-affluent'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'instagram', 'facebook', 'ttd'], geos: ['national'], budgetMultiplier: 1.20,
    plannedBudget: 8_600_000, revPerConvRange: [420, 920], cvrModifier: 1.25, cplCalibration: 0.80, revTrend: 0.0004 },

  // ── TIER 2 — REGIONAL / MEDIA (Initiative) ──
  { id: 'rbc-newcomers-arrive', name: 'Newcomers — Arrive & Bank in 3 Steps',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-newcomers',
    audiences: ['rbc-newcomers-aud', 'rbc-students'], objective: 'consideration', status: 'live',
    channels: ['facebook', 'instagram', 'google-search', 'tiktok'], geos: ['ontario', 'bc'], budgetMultiplier: 1.05,
    plannedBudget: 6_400_000, revPerConvRange: [360, 820], cvrModifier: 1.10, cplCalibration: 0.90, revTrend: 0.0005 },
  { id: 'rbc-wealth-affluent', name: 'Wealth & Investments — Mass-Affluent Always-On',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-wealth',
    audiences: ['rbc-mass-affluent'], objective: 'consideration', status: 'live',
    channels: ['linkedin', 'google-search', 'ttd', 'ctv'], geos: ['national', 'ontario'], budgetMultiplier: 1.00,
    plannedBudget: 7_800_000, revPerConvRange: [1_300, 2_700], cvrModifier: 1.05, cplCalibration: 0.75, revTrend: 0.0004 },
  { id: 'rbc-students-bts', name: 'Students — Back-to-School No-Fee Chequing',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-chequing',
    audiences: ['rbc-students'], objective: 'conversion', status: 'paused',
    channels: ['tiktok', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.85,
    plannedBudget: 3_900_000, revPerConvRange: [220, 560], cvrModifier: 1.20, cplCalibration: 0.95, revTrend: 0.0003 },

  // ── TIER 3 — BRANCH & LOCAL ──
  { id: 'rbc-smallbiz-local', name: 'Small Business — Local Advisor Booking',
    enterprise: 'rbc', division: 'tier-3', agency: 'rbc-branch', productLine: 'rbc-business',
    audiences: ['rbc-small-biz'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'facebook', 'linkedin'], geos: ['ontario', 'alberta'], budgetMultiplier: 0.80,
    plannedBudget: 3_200_000, revPerConvRange: [640, 1_480], cvrModifier: 1.00, cplCalibration: 0.88, revTrend: 0.0004 },
  { id: 'rbc-mortgage-renewal', name: 'Mortgage Renewal — Retention & Rate-Hold',
    enterprise: 'rbc', division: 'tier-3', agency: 'rbc-branch', productLine: 'rbc-mortgages',
    audiences: ['rbc-mass-affluent', 'rbc-first-home'], objective: 'retention', status: 'live',
    channels: ['google-search', 'facebook'], geos: ['national'], budgetMultiplier: 0.75,
    plannedBudget: 2_900_000, revPerConvRange: [1_500, 2_800], cvrModifier: 1.10, cplCalibration: 0.92, revTrend: 0.0005 },
];

export const RBC_NEWS: NewsItem[] = [
  { id: 'news-rbc-boc-rate-hold', title: 'Bank of Canada Holds Overnight Rate at 2.75% — Spring Mortgage Demand Expected to Firm',
    source: 'Bank of Canada', date: '2026-05-07', tags: ['macro'], urgency: 'high', regions: ['national'],
    summary: 'The Bank of Canada held its policy rate at 2.75% for a third consecutive decision, signalling a stable-to-easing path into the second half. Fixed-rate mortgage pricing has already begun to compress at the major banks.',
    whyItMatters: 'A stable rate removes the biggest hesitation for first-time buyers. STRATIS flags the Spring Home-Buying mortgage flight as the campaign most exposed to the demand shift — branded "mortgage rate" search is the leading indicator to watch.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-newcomer-targets', title: "Ottawa Confirms 2026 Immigration Levels — ~395K New Permanent Residents, Concentrated in ON & BC",
    source: 'IRCC', date: '2026-05-04', tags: ['macro', 'partnerships'], urgency: 'high', regions: ['ontario', 'bc'],
    summary: 'Immigration, Refugees and Citizenship Canada confirmed 2026 permanent-resident targets of roughly 395,000, with settlement concentrated in the Greater Toronto and Greater Vancouver areas.',
    whyItMatters: 'Newcomers open their first Canadian account within weeks of arrival — a narrow, high-LTV acquisition window. The Newcomers flight is regionally weighted to exactly where arrivals land; STRATIS is watching for under-served arrival cohorts.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-td-cashback-offer', title: 'TD Launches Aggressive $500 Chequing Cash-Bonus Offer — Heaviest Switcher Push in Two Years',
    source: 'The Globe and Mail', date: '2026-05-06', tags: ['competitors'], urgency: 'high', competitor: 'TD',
    regions: ['national'], summary: 'TD began a national $500 cash-bonus acquisition offer for new chequing accounts with direct-deposit conditions, backed by a heavy paid-search and social buy.',
    whyItMatters: 'A direct conquest threat to Everyday Banking and Avion switcher acquisition. STRATIS detected branded "RBC vs TD" comparison search rising in the days after launch — reported as correlation, see the linked recommendation.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-interac-fraud', title: 'Interac Reports Spike in E-Transfer Fraud — Banks Asked to Lead Consumer-Education Messaging',
    source: 'Interac', date: '2026-04-29', tags: ['macro', 'social'], urgency: 'medium', regions: ['national'],
    summary: 'Interac flagged a quarter-over-quarter rise in e-transfer fraud attempts and asked member institutions to amplify consumer-protection education.',
    whyItMatters: 'A brand-trust opportunity adjacent to the Everyday Banking platform — security leadership is a proven switcher driver. No spend reallocation required yet; tracked at the brand level.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-open-banking', title: 'Federal Consumer-Driven Banking Framework Finalized — Open-Banking Switching Goes Live 2027',
    source: 'Department of Finance Canada', date: '2026-04-22', tags: ['macro', 'launch'], urgency: 'medium', regions: ['national'],
    summary: 'The federal government finalized the consumer-driven banking (open banking) framework, with account-data portability obligations phasing in through 2027.',
    whyItMatters: 'Lowers switching friction industry-wide — raising the stakes on switcher conquest and retention simultaneously. A structural signal STRATIS is correlating against renewal and conquest performance.',
    enterprises: ['rbc'] },
];

export const RBC_RADAR_PINS = ['news-rbc-boc-rate-hold', 'news-rbc-td-cashback-offer', 'news-rbc-newcomer-targets'];

export const RBC_INSIGHTS: Insight[] = [
  {
    id: 'ins-rbc-01-frequency-cap', createdAt: todayISO,
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'ooh', 'instagram', 'ttd'],
    title: 'Across All Six Live Product Lines, the Average GTA Adult Sees an RBC Message 26x a Week — Most of It the Same Two Products',
    summary: 'Everyday Banking, Mortgages, Avion, and Wealth all buy the same mass-affluent GTA adult independently, and no cap exists across product lines. Deduped across every live RBC campaign, that person sees ~26 RBC exposures a week, heavily skewed to Everyday Banking and Mortgages — while Wealth and Small Business are under-delivered to the same reachable audience. A portfolio-level frequency cap pulls combined weight back to the effective range and frees impressions for the products being starved.',
    evidence: [
      'Deduped across all 8 live RBC campaigns: ~26 brand exposures/week to the average reached GTA adult',
      'Per-campaign caps are respected; no portfolio-level cap exists across product lines',
      '~60% of combined weight lands on Everyday Banking + Mortgages',
      'Wealth and Small Business reach <30% of the same addressable mass-affluent pool',
      'Visible only by deduping audiences across every product line at once',
    ],
    confidence: 0.86,
    impactEstimate: 'A portfolio-level frequency cap redeploys over-delivered Everyday Banking weight into under-reached Wealth and Small Business audiences with no loss of net reach.',
    recommendedAction: 'Set a portfolio-level frequency cap across all live RBC product lines and reallocate recovered weight to under-reached Wealth and Small Business audiences.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set a portfolio-level frequency cap', subtitle: 'ACROSS ALL LIVE PRODUCT LINES', type: 'bidding', completed: false },
      { id: 's2', title: 'Redeploy recovered weight to Wealth + Small Business', subtitle: 'PRESERVE NET REACH', type: 'budget', completed: false },
      { id: 's3', title: 'Monitor combined exposure continuously', subtitle: 'STRATIS DEDUPES + ENFORCES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-02-td-conquest', createdAt: at(1, '08:30:00'),
    enterprise: 'rbc', category: 'competitive-macro', scope: 'product', productLine: 'rbc-chequing',
    channels: ['google-search', 'instagram', 'facebook'],
    title: "TD's $500 Cash Bonus Is Lifting 'RBC vs TD' Comparison Search — Defend Now Before the Switcher Window Closes",
    summary: "In the days after TD's national $500 chequing offer, branded 'RBC vs TD' and 'best chequing bonus' search rose sharply — a leading indicator that switchers are actively comparing. RBC currently bids defensively on only a fraction of those comparison terms, and the Everyday Banking offer is not surfaced in the comparison moment. A focused search-defense and a matched limited-time offer captures switchers already in-market rather than ceding them. Correlation, not causation — but the window is short.",
    evidence: [
      "'RBC vs TD' and 'best chequing bonus Canada' search volume up materially since the TD launch",
      'RBC bids on a minority of high-intent comparison queries; TD is bidding on RBC-brand terms',
      'Everyday Banking offer is not present in the comparison-shopping moment',
      'Switcher conquest CVR is highest within the first 10 days of a competitive offer',
    ],
    confidence: 0.82,
    impactEstimate: 'Defending comparison search and surfacing a matched offer recaptures in-market switchers before the competitive window closes.',
    recommendedAction: 'Expand defensive search coverage on RBC-vs-competitor comparison terms and surface a matched limited-time Everyday Banking offer in the comparison moment.',
    status: 'new',
    linkedNewsId: 'news-rbc-td-cashback-offer',
    actionSteps: [
      { id: 's1', title: 'Expand defensive comparison-term coverage', subtitle: 'CONQUEST + BRAND-DEFENSE', type: 'bidding', completed: false },
      { id: 's2', title: 'Surface a matched limited-time offer', subtitle: 'EVERYDAY BANKING', type: 'creative', completed: false },
      { id: 's3', title: 'Track switcher CVR daily through the window', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-03-mortgage-timing', createdAt: at(2, '10:15:00'),
    enterprise: 'rbc', category: 'national-regional', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search', 'ttd', 'facebook'],
    title: 'Mortgage Demand Is Firming in BC Two Weeks Ahead of Ontario — National Pacing Is Under-Weighting the Earlier Market',
    summary: 'Branded mortgage search and pre-approval starts are rising in BC roughly two weeks before the same lift appears in Ontario, but the national mortgage flight paces budget evenly across both. The result is BC demand outrunning delivery while Ontario weight arrives before its demand does. Front-loading BC and lagging Ontario to match the real demand curve captures more pre-approvals at a lower cost-per-application across the same total budget.',
    evidence: [
      'BC branded-mortgage search leads Ontario by ~14 days into the spring window',
      'National flight paces evenly; it does not follow the regional demand curve',
      'BC cost-per-application is climbing as demand outruns delivery',
      'Ontario weight is arriving ahead of its demand inflection',
    ],
    confidence: 0.79,
    impactEstimate: 'Sequencing weight to the regional demand curve lifts pre-approval volume at a lower blended cost-per-application with no added budget.',
    recommendedAction: 'Front-load BC mortgage weight now and lag Ontario by ~2 weeks to match the regional demand curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load BC mortgage weight', subtitle: 'MATCH DEMAND CURVE', type: 'budget', completed: false },
      { id: 's2', title: 'Lag Ontario delivery ~2 weeks', subtitle: 'AVOID EARLY OVER-DELIVERY', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-04-newcomer-creative', createdAt: at(4, '13:00:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-newcomers',
    channels: ['facebook', 'instagram', 'tiktok'],
    title: 'The 3-Step "Arrive & Bank" Creative Outperforms Everywhere It Runs — but Only Carries Two of the Five Arrival Languages',
    summary: 'Ranking Newcomers creative across regions, the simple 3-step "Arrive & Bank" execution beats every alternative on both completion and account-open rate. Yet it is localized only in English and French, while a large share of 2026 arrivals are concentrated in communities where in-language creative consistently lifts CVR. Extending the proven execution into the top arrival languages is a high-confidence scale move, not an experiment.',
    evidence: [
      '3-step "Arrive & Bank" leads all Newcomers creative on completion and account-open rate',
      'Currently localized in English and French only',
      'In-language creative shows a consistent CVR lift in newcomer segments',
      'Top 2026 arrival communities are addressable in-platform',
    ],
    confidence: 0.81,
    impactEstimate: 'Extending the proven creative into the top arrival languages scales a known winner into its highest-CVR audiences.',
    recommendedAction: 'Localize the winning "Arrive & Bank" execution into the top arrival languages and weight delivery to matched communities.',
    status: 'new',
    linkedNewsId: 'news-rbc-newcomer-targets',
    actionSteps: [
      { id: 's1', title: 'Localize the winning creative', subtitle: 'TOP ARRIVAL LANGUAGES', type: 'creative', completed: false },
      { id: 's2', title: 'Weight delivery to matched communities', subtitle: 'ON + BC SETTLEMENT AREAS', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-05-audience-overlap', createdAt: at(6, '09:45:00'),
    enterprise: 'rbc', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'ttd'],
    title: 'Mass-Affluent Buyers Are Being Bid On by Four Product Lines at Once — RBC Is Competing Against Itself in the Auction',
    summary: 'Everyday Banking, Mortgages, Avion, and Wealth all target overlapping mass-affluent segments in the same auctions, bidding up RBC\'s own CPMs against itself. STRATIS measures the overlap at roughly a third of the addressable pool. Coordinating bids and sequencing the product story per user — rather than four products shouting at once — lowers blended CPM and presents a coherent cross-sell journey instead of internal auction competition.',
    evidence: [
      '~33% of the mass-affluent pool is targeted by 4+ live RBC campaigns simultaneously',
      'Overlapping demand is inflating RBC-vs-RBC auction CPMs',
      'No cross-product sequencing exists for shared users',
      'Coordinated bidding lowers blended CPM with no reach loss',
    ],
    confidence: 0.77,
    impactEstimate: 'De-duplicating internal auction competition lowers blended CPM and turns four competing messages into a sequenced cross-sell journey.',
    recommendedAction: 'Coordinate bids across product lines on shared mass-affluent audiences and sequence the cross-sell story per user.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Coordinate bids on shared audiences', subtitle: 'STOP RBC-VS-RBC COMPETITION', type: 'bidding', completed: false },
      { id: 's2', title: 'Sequence the cross-sell story per user', subtitle: 'ONE JOURNEY, NOT FOUR', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-06-agency-arbitrage', createdAt: at(9, '11:20:00'),
    enterprise: 'rbc', category: 'agency-arbitrage', scope: 'brand',
    channels: ['google-search', 'facebook', 'linkedin'],
    title: 'Branch & Local Is Beating National on Cost-per-Application for the Same Product — the Local Playbook Should Cascade Up',
    summary: 'On Mortgages, the Tier 3 Branch & Local team is delivering a materially lower cost-per-application than the national Tier 1 flight for the same product, driven by tighter geo-conversion targeting and advisor-booking creative. The pattern repeats across Small Business. Rather than treat this as a local anomaly, the national flight should adopt the Branch playbook\'s targeting and booking-led creative where it scales.',
    evidence: [
      'Branch & Local cost-per-application on Mortgages is below the national flight for the same product',
      'Advantage traces to geo-conversion targeting + advisor-booking creative',
      'Same pattern holds on Small Business',
      'National flight does not currently use the Branch booking-led creative',
    ],
    confidence: 0.75,
    impactEstimate: 'Cascading the Branch & Local targeting and booking-led creative into the national flight lowers blended cost-per-application at scale.',
    recommendedAction: 'Adopt the Branch & Local geo-targeting and advisor-booking creative in the national Mortgages flight where it scales.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the Branch & Local playbook', subtitle: 'TARGETING + BOOKING CREATIVE', type: 'targeting', completed: false },
      { id: 's2', title: 'Cascade into the national Mortgages flight', subtitle: 'WHERE IT SCALES', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-07-search-headroom', createdAt: at(3, '09:40:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search'],
    title: 'Mortgage Paid Search Is Capped ~20% Below the Point Where Cost-per-Application Starts to Climb',
    summary: 'Marginal cost-per-application on the mortgage search flight holds flat until roughly 30% above the current spend cap, then inflects upward — so the cap is leaving in-market applications unclaimed at target CPA. Lifting the ceiling toward the inflection captures incremental applications without degrading efficiency. STRATIS tracks the marginal curve continuously so the cap follows profitability, not a fixed budget line.',
    evidence: [
      'Marginal CPA holds flat from the current cap to ~+30% spend',
      'CPA inflects upward only beyond that point',
      'The current cap sits ~20% below the inflection',
      'In-market demand is unmet at target CPA inside the headroom',
    ],
    confidence: 0.78,
    impactEstimate: 'Raising the cap to the marginal-CPA inflection captures incremental applications still at target efficiency.',
    recommendedAction: 'Lift the mortgage search cap toward the marginal-CPA inflection and hold it there as STRATIS tracks the curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Lift the search cap to the CPA inflection', subtitle: 'MAINTAIN TARGET CPA', type: 'budget', completed: false },
      { id: 's2', title: 'Track marginal CPA continuously', subtitle: 'STRATIS HOLDS THE CURVE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-08-wealth-underreach', createdAt: at(7, '10:50:00'),
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['ttd', 'linkedin', 'google-search'],
    title: 'Wealth and Small Business Reach Under 30% of the Mass-Affluent Base the Brand Already Pays to Reach',
    summary: 'Everyday Banking and Mortgages saturate the mass-affluent audience while Wealth and Small Business — the highest-LTV products in the book — reach less than a third of the same addressable base. The brand already pays to reach these people through other product lines, so extending coverage to the under-served high-LTV products is reach the portfolio is leaving unclaimed rather than new audience to buy.',
    evidence: [
      'Everyday & Mortgages reach >60% of the mass-affluent base',
      'Wealth reaches ~28%, Small Business ~24% of the same base',
      'These are the highest-LTV products in the portfolio',
      'The base is already addressable through other live lines',
    ],
    confidence: 0.80,
    impactEstimate: 'Extending high-LTV product reach into the already-paid-for base claims unclaimed coverage at low marginal cost.',
    recommendedAction: 'Reallocate over-delivered Everyday/Mortgage reach toward Wealth and Small Business across the shared mass-affluent base.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Extend Wealth + Small Business reach', subtitle: 'SHARED MASS-AFFLUENT BASE', type: 'targeting', completed: false },
      { id: 's2', title: 'Fund from over-delivered lines', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-rbc-09-renewal-cliff', createdAt: at(2, '08:55:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search', 'facebook'],
    title: 'The Mortgage Renewal Flight Is Spending Flat — but 60% of This Year\'s Renewals Cliff Into a Single 90-Day Window',
    summary: 'A large cohort of fixed-rate mortgages written at pandemic-era lows mature this year, and the renewal book is heavily bunched into one 90-day window rather than spread evenly. The retention flight, however, paces a flat monthly budget — under-delivering in the cliff window when intent and attrition risk both spike, and over-delivering in the quiet months. Front-loading retention spend into the renewal cliff defends the highest-LTV balances exactly when they are in play. With the Bank of Canada holding rates, switchers are shopping renewals harder than usual.',
    evidence: [
      '~60% of 2026 RBC renewals mature inside a single 90-day window',
      'The retention flight paces flat monthly spend, ignoring the maturity curve',
      'Branded "mortgage renewal rate" search concentrates ahead of the cliff',
      'Attrition risk on renewals is highest in the 45 days before maturity',
      'Visible only by aligning the maturity book against media pacing',
    ],
    confidence: 0.83,
    impactEstimate: 'Concentrating retention weight into the renewal cliff defends high-LTV balances at the moment of highest attrition risk with no added budget.',
    recommendedAction: 'Re-pace the renewal flight to front-load the 90-day maturity cliff and pull weight out of the quiet months.',
    status: 'new',
    linkedNewsId: 'news-rbc-boc-rate-hold',
    actionSteps: [
      { id: 's1', title: 'Re-pace spend to the maturity cliff', subtitle: 'FRONT-LOAD THE 90-DAY WINDOW', type: 'scheduling', completed: false },
      { id: 's2', title: 'Pull weight from quiet months', subtitle: 'NO ADDED BUDGET', type: 'budget', completed: false },
      { id: 's3', title: 'Trigger off branded renewal search', subtitle: 'STRATIS WATCHES INTENT', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-rbc-10-cross-sell-sequence', createdAt: at(5, '10:05:00'),
    enterprise: 'rbc', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'google-search', 'ttd'],
    title: 'New Chequing Customers Who See Avion Before Wealth Convert to a Second Product 2x — but the Portfolio Pitches All Three at Once',
    summary: 'Tracing shared users across product lines, customers who acquire chequing first and are then sequenced into Avion, and only later into Wealth, open a second RBC product at roughly twice the rate of those hit by all three messages simultaneously. Today every line bids the same fresh-chequing cohort independently, so the cross-sell story arrives scrambled. Enforcing a chequing→credit→wealth sequence on shared users turns four competing pitches into one compounding journey — and only STRATIS sees the cohort across all lines at once.',
    evidence: [
      'Chequing→Avion→Wealth sequenced users open a 2nd product ~2x vs. simultaneous exposure',
      'All three lines currently bid the fresh-chequing cohort independently',
      'No ordering logic exists on shared new-to-bank users',
      'Wealth uptake is highest 60–90 days after first product, not on day one',
      'The cohort is only visible by joining identity across product lines',
    ],
    confidence: 0.78,
    impactEstimate: 'Sequencing the cross-sell story lifts second-product open rates without buying any new audience.',
    recommendedAction: 'Enforce a chequing→credit→wealth message sequence on shared new-to-bank users instead of pitching all three at once.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Define the cross-sell sequence', subtitle: 'CHEQUING → AVION → WEALTH', type: 'targeting', completed: false },
      { id: 's2', title: 'Suppress later products until stage unlocks', subtitle: 'ONE JOURNEY PER USER', type: 'targeting', completed: false },
      { id: 's3', title: 'Time Wealth to the 60–90 day window', subtitle: 'STRATIS TRACKS COHORTS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-11-fraud-trust', createdAt: at(8, '12:30:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-chequing',
    channels: ['facebook', 'instagram', 'spotify'],
    title: 'The E-Transfer Security Message Lifts Switcher Intent More Than Any Cash-Bonus Creative — and It Is Barely in Rotation',
    summary: 'Among Everyday Banking executions, the Interac fraud-protection / security-leadership message is driving the strongest lift in switcher consideration per impression — outperforming the cash-bonus creative that dominates the rotation. With Interac asking banks to lead consumer education, the trust angle is both timely and differentiated, yet it sits at a sliver of delivery. Re-weighting rotation toward the security message captures a proven switcher driver at the exact moment fraud is in the headlines. This is a creative-mix shift, not new spend.',
    evidence: [
      'Security/fraud-protection creative leads all Everyday Banking executions on switcher-intent lift',
      'It currently holds a small share of rotation vs. cash-bonus creative',
      'Trust/security is a proven driver of switching in retail banking',
      'Interac has asked member banks to lead consumer-education messaging',
      'Lift is measured per impression, controlling for delivery weight',
    ],
    confidence: 0.79,
    impactEstimate: 'Re-weighting rotation toward the security message scales the highest switcher-intent creative at no added cost.',
    recommendedAction: 'Shift Everyday Banking creative rotation toward the e-transfer security message while fraud is in the news cycle.',
    status: 'new',
    linkedNewsId: 'news-rbc-interac-fraud',
    actionSteps: [
      { id: 's1', title: 'Re-weight rotation to the security message', subtitle: 'TRUST OVER CASH-BONUS', type: 'creative', completed: false },
      { id: 's2', title: 'Target high-intent switcher segments', subtitle: 'CONQUEST AUDIENCES', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-12-open-banking', createdAt: at(11, '09:15:00'),
    enterprise: 'rbc', category: 'competitive-macro', scope: 'brand',
    channels: ['google-search', 'linkedin', 'ttd'],
    title: 'Open Banking Goes Live in 2027 — RBC\'s Switcher Defense and Conquest Are Both Funded for a World With Switching Friction',
    summary: 'The finalized consumer-driven banking framework strips away the account-data friction that has long protected incumbents, raising the stakes on conquest and retention at the same time. RBC\'s current mix still leans on acquisition creative built for a high-friction world and under-invests in always-on retention of its most portable balances. STRATIS correlates renewal and conquest performance against the framework timeline so the portfolio can shift toward defensible retention before friction disappears — a structural reallocation, not a campaign tweak.',
    evidence: [
      'Open-banking data portability phases in through 2027, lowering switching friction industry-wide',
      'Current mix over-indexes on high-friction acquisition creative',
      'Most-portable balances (chequing, Avion) are under-defended in always-on retention',
      'Conquest upside and attrition risk both rise as friction falls',
      'STRATIS correlates renewal + conquest performance against the framework timeline',
    ],
    confidence: 0.74,
    impactEstimate: 'Rebalancing toward always-on retention of portable balances protects the book before open-banking friction disappears.',
    recommendedAction: 'Shift mix toward always-on retention of portable balances ahead of open-banking go-live while sustaining conquest.',
    status: 'new',
    linkedNewsId: 'news-rbc-open-banking',
    actionSteps: [
      { id: 's1', title: 'Fund always-on retention of portable balances', subtitle: 'CHEQUING + AVION', type: 'budget', completed: false },
      { id: 's2', title: 'Hold conquest pressure on switchers', subtitle: 'BOTH SIDES OF THE GATE', type: 'targeting', completed: false },
      { id: 's3', title: 'Track performance vs. 2027 timeline', subtitle: 'STRATIS CORRELATES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-13-avion-seasonality', createdAt: at(13, '11:40:00'),
    enterprise: 'rbc', category: 'national-regional', scope: 'product', productLine: 'rbc-avion',
    channels: ['instagram', 'facebook', 'google-search', 'ttd'],
    title: 'Avion Travel-Redemption Intent Surges in Alberta and BC Six Weeks Before the National Booking Peak — but Spend Is National-Flat',
    summary: 'Travel-redemption search and Avion booking-intent signals spike earlier and harder in Alberta and BC ahead of the summer travel window, while the conquest flight pumps a flat national budget. Western buyers are entering the redemption mindset weeks before the national average, so the card-switcher pitch lands there when intent is hottest yet receives no extra weight. Regionally front-loading Avion into the early-redemption markets captures switchers at peak travel-intent at a lower cost-per-acquisition. Only a portfolio view exposes the regional lead.',
    evidence: [
      'Alberta + BC travel-redemption search leads the national booking peak by ~6 weeks',
      'The Avion conquest flight paces a flat national budget',
      'Switcher CVR rises when the card pitch meets active travel-intent',
      'Western redemption intent cools as the national average peaks',
      'Regional lead is only visible deduped across the national flight',
    ],
    confidence: 0.76,
    impactEstimate: 'Front-loading Avion into early-redemption Western markets captures switchers at peak travel-intent at a lower CPA.',
    recommendedAction: 'Front-load Avion conquest weight into Alberta and BC ahead of the national travel-booking peak.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load Avion in AB + BC', subtitle: 'AHEAD OF NATIONAL PEAK', type: 'budget', completed: false },
      { id: 's2', title: 'Sync creative to travel-redemption intent', subtitle: 'MEET THE BOOKING MINDSET', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-14-linkedin-smallbiz', createdAt: at(10, '09:30:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-business',
    channels: ['linkedin', 'google-search', 'facebook'],
    title: 'On Small Business, LinkedIn Is Delivering Advisor Bookings at Half the Cost of Facebook — but Holds a Quarter of the Budget',
    summary: 'Across the Small Business flight, LinkedIn is producing qualified advisor-booking leads at roughly half the cost-per-booking of Facebook, with higher lead quality from owner and decision-maker targeting. Yet budget allocation is inverted — Facebook holds the majority of spend while the more efficient channel is starved. Shifting weight toward LinkedIn up to the point its cost-per-booking starts to climb captures more qualified bookings at the same total spend. STRATIS tracks the marginal curve so the shift stops at efficiency, not at a fixed split.',
    evidence: [
      'LinkedIn cost-per-advisor-booking is ~50% of Facebook on the Small Business flight',
      'Budget is inverted — Facebook holds the majority of spend',
      'LinkedIn owner/decision-maker targeting yields higher lead quality',
      'LinkedIn has marginal headroom before cost-per-booking inflects',
      'Efficiency gap is only visible normalizing booking quality across channels',
    ],
    confidence: 0.80,
    impactEstimate: 'Re-weighting Small Business spend toward LinkedIn captures more qualified advisor bookings at the same total budget.',
    recommendedAction: 'Shift Small Business budget toward LinkedIn up to its marginal cost-per-booking inflection.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift budget toward LinkedIn', subtitle: 'CHASE COST-PER-BOOKING', type: 'budget', completed: false },
      { id: 's2', title: 'Hold the shift at the inflection', subtitle: 'STRATIS TRACKS THE CURVE', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-rbc-15-quebec-french', createdAt: at(14, '10:25:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-chequing',
    channels: ['facebook', 'instagram', 'tiktok'],
    title: 'Quebec Is Running Translated National Creative — Purpose-Built French Executions Lift CVR a Third Where They Exist',
    summary: 'In Quebec, most Everyday Banking delivery is direct translation of the national English creative rather than purpose-built French-language executions. Where genuinely French-first creative does run, completion and account-open rates lift by roughly a third, and the work also sits more cleanly against Quebec language-and-tone expectations. Treating Quebec as a translated afterthought leaves both performance and brand fit on the table; commissioning French-first executions for the top-spend formats is a high-confidence creative move tied to a market that buys differently.',
    evidence: [
      'Most Quebec delivery is translated national creative, not French-first work',
      'Purpose-built French executions lift account-open rate ~33% where they run',
      'French-first work fits Quebec language-and-tone expectations more cleanly',
      'Translated creative under-indexes on completion in Quebec vs. ROC',
      'Gap is only visible comparing Quebec creative variants head-to-head',
    ],
    confidence: 0.77,
    impactEstimate: 'Commissioning French-first executions for top-spend formats scales a proven CVR lift in a market that buys differently.',
    recommendedAction: 'Commission purpose-built French-first creative for the top-spend Quebec formats instead of translating national work.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Commission French-first executions', subtitle: 'TOP-SPEND QUEBEC FORMATS', type: 'creative', completed: false },
      { id: 's2', title: 'A/B against translated control', subtitle: 'PROVE THE LIFT', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-16-wealth-ctv-mix', createdAt: at(12, '13:20:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-wealth',
    channels: ['ctv', 'google-search', 'ttd', 'linkedin'],
    title: 'Wealth Pours Budget Into CTV Awareness While High-Intent Search Sits Capped — the Mix Is Inverted for a Considered Product',
    summary: 'The Wealth flight weights heavily toward CTV brand awareness, but mass-affluent investing is a considered, search-led decision where bottom-funnel queries convert far more efficiently. Search is capped well below its profitable demand while CTV runs past the point of incremental reach. Rebalancing from over-delivered CTV into uncapped high-intent search lifts qualified consultations at a lower blended cost. CTV still seeds consideration — but the mix should follow how this audience actually decides, not a default awareness tilt.',
    evidence: [
      'Wealth budget skews to CTV awareness over bottom-funnel search',
      'High-intent Wealth search converts consultations far more efficiently than CTV',
      'Search is capped below profitable demand; CTV runs past incremental reach',
      'Mass-affluent investing is a considered, search-led decision',
      'The efficiency inversion is only visible comparing channels on cost-per-consultation',
    ],
    confidence: 0.78,
    impactEstimate: 'Rebalancing from over-delivered CTV into uncapped high-intent search lifts qualified consultations at a lower blended cost.',
    recommendedAction: 'Shift Wealth budget from over-delivered CTV awareness into uncapped high-intent search.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Lift the Wealth search cap', subtitle: 'CHASE HIGH-INTENT DEMAND', type: 'budget', completed: false },
      { id: 's2', title: 'Trim CTV past incremental reach', subtitle: 'KEEP A CONSIDERATION FLOOR', type: 'budget', completed: false },
      { id: 's3', title: 'Track cost-per-consultation by channel', subtitle: 'STRATIS HOLDS THE MIX', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-17-booking-funnel', createdAt: at(15, '09:50:00'),
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['google-search', 'facebook', 'linkedin'],
    title: 'Advisor-Booking Journeys Convert Twice as Often as Online-Application Journeys on High-Consideration Products — but Get a Third of the Spend',
    summary: 'On the highest-consideration products — Mortgages, Wealth, and Small Business — journeys that route to a booked advisor conversation convert at roughly double the rate of self-serve online-application journeys, yet the portfolio still defaults most spend to online-application creative. The booking funnel wins because these decisions need a human, and the Branch & Local team already proves it at the local level. Re-pointing high-consideration creative toward advisor-booking calls-to-action, rather than online forms, lifts conversion across the most valuable products. Only a cross-product view shows the funnel gap consistently.',
    evidence: [
      'Advisor-booking journeys convert ~2x online-application journeys on Mortgages, Wealth, Small Business',
      'Most high-consideration spend still defaults to online-application creative',
      'Booking wins where the decision needs a human advisor',
      'Branch & Local already proves the booking funnel locally',
      'The funnel gap is only consistent across a cross-product view',
    ],
    confidence: 0.81,
    impactEstimate: 'Re-pointing high-consideration creative to advisor-booking CTAs lifts conversion across the most valuable products.',
    recommendedAction: 'Default high-consideration product creative to advisor-booking calls-to-action over online-application forms.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Switch CTAs to advisor-booking', subtitle: 'MORTGAGES + WEALTH + SMALL BIZ', type: 'creative', completed: false },
      { id: 's2', title: 'Re-weight spend to the booking funnel', subtitle: 'FOLLOW THE CONVERSION', type: 'budget', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const RBC_VISUALS: Record<string, InsightVisual> = {
  'ins-rbc-01-frequency-cap': {
    kind: 'bar', xKey: 'product', series: ['freq'], perBarColor: true,
    yTitle: 'Weekly frequency',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { product: 'Everyday', freq: 11, fill: MUTED },
      { product: 'Mortgages', freq: 9, fill: MUTED },
      { product: 'Avion', freq: 4, fill: MUTED },
      { product: 'Wealth', freq: 2, fill: MUTED },
      { product: 'Combined', freq: 26, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 12, label: 'Effective max ~12', color: TEAL }],
    caption: 'No single product over-delivers — deduped exposure hits 26×/week',
  },
  'ins-rbc-02-td-conquest': {
    kind: 'line', xKey: 'week', series: ['search'],
    yTitle: "'RBC vs TD' search (indexed)",
    config: { search: { label: 'Comparison search', color: RED } },
    data: [
      { week: 'W1', search: 100 }, { week: 'W2', search: 102 }, { week: 'W3', search: 104 },
      { week: 'W4', search: 126 }, { week: 'W5', search: 133 }, { week: 'W6', search: 128 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'TD $500 offer launches', color: GRID }],
    caption: 'Comparison search spikes the week TD launches — the switcher window',
  },
  'ins-rbc-03-mortgage-timing': {
    kind: 'line', xKey: 'week', series: ['bc', 'on'],
    yTitle: 'Branded mortgage search (index)',
    config: { bc: { label: 'BC', color: TEAL }, on: { label: 'Ontario', color: PURPLE } },
    data: [
      { week: 'W1', bc: 104, on: 96 }, { week: 'W2', bc: 118, on: 99 }, { week: 'W3', bc: 131, on: 104 },
      { week: 'W4', bc: 128, on: 116 }, { week: 'W5', bc: 117, on: 129 }, { week: 'W6', bc: 108, on: 133 },
    ],
    caption: 'BC demand peaks ~2 weeks before Ontario — even pacing misses both',
  },
  'ins-rbc-04-newcomer-creative': {
    kind: 'bar', xKey: 'variant', series: ['index'], perBarColor: true,
    yTitle: 'Account-open index',
    config: { index: { label: 'Account-open index' } },
    data: [
      { variant: '3-step "Arrive"', index: 142, fill: TEAL },
      { variant: 'Standard', index: 100, fill: MUTED },
      { variant: 'Long-form', index: 86, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Avg', color: GRID }],
    caption: 'The 3-step creative wins — but ships in only 2 of 5 arrival languages',
  },
  'ins-rbc-05-audience-overlap': {
    kind: 'bar', xKey: 'audience', series: ['campaigns'], perBarColor: true,
    yTitle: 'Live campaigns bidding',
    config: { campaigns: { label: 'Campaigns bidding' } },
    data: [
      { audience: 'Mass-Affluent', campaigns: 4, fill: RED },
      { audience: 'First-Home', campaigns: 2, fill: MUTED },
      { audience: 'Newcomers', campaigns: 2, fill: MUTED },
      { audience: 'Switchers', campaigns: 2, fill: MUTED },
      { audience: 'Students', campaigns: 1, fill: MUTED },
    ],
    caption: 'Four product lines bid the same mass-affluent buyer — RBC vs RBC',
  },
  'ins-rbc-06-agency-arbitrage': {
    kind: 'bar', xKey: 'product', series: ['national', 'branch'],
    yTitle: 'Cost per application ($)',
    config: { national: { label: 'National (T1)', color: RED }, branch: { label: 'Branch & Local (T3)', color: TEAL } },
    data: [
      { product: 'Mortgages', national: 148, branch: 112 },
      { product: 'Small Business', national: 96, branch: 74 },
    ],
    caption: 'Branch & Local beats National cost-per-application on the same products',
  },
  'ins-rbc-07-search-headroom': {
    kind: 'line', xKey: 'spend', series: ['cpa'],
    xTitle: 'Mortgage search spend (indexed)', yTitle: 'Cost per application ($)',
    config: { cpa: { label: 'Marginal CPA', color: TEAL } },
    data: [
      { spend: 60, cpa: 138 }, { spend: 80, cpa: 141 }, { spend: 100, cpa: 143 },
      { spend: 120, cpa: 146 }, { spend: 140, cpa: 158 }, { spend: 160, cpa: 178 },
    ],
    refLines: [{ axis: 'x', value: 100, label: 'Current cap', color: RED }],
    caption: 'CPA stays flat to ~+30% spend — the cap sits below profitable demand',
  },
  'ins-rbc-08-wealth-underreach': {
    kind: 'bar', xKey: 'product', series: ['reach'], perBarColor: true,
    yTitle: 'Reach of mass-affluent base (%)',
    config: { reach: { label: 'Reach %' } },
    data: [
      { product: 'Everyday', reach: 71, fill: MUTED },
      { product: 'Mortgages', reach: 64, fill: MUTED },
      { product: 'Avion', reach: 52, fill: MUTED },
      { product: 'Wealth', reach: 28, fill: RED },
      { product: 'Small Business', reach: 24, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 50, label: 'Portfolio avg', color: GRID }],
    caption: 'Wealth & Small Business reach <30% of the base the brand already pays for',
  },
  'ins-rbc-09-renewal-cliff': {
    kind: 'bar', xKey: 'month', series: ['renewals', 'spend'],
    yTitle: 'Indexed share',
    config: { renewals: { label: 'Renewals maturing', color: RED }, spend: { label: 'Retention spend', color: MUTED } },
    data: [
      { month: 'Jan', renewals: 6, spend: 8 }, { month: 'Feb', renewals: 7, spend: 8 },
      { month: 'Mar', renewals: 9, spend: 9 }, { month: 'Apr', renewals: 28, spend: 9 },
      { month: 'May', renewals: 31, spend: 8 }, { month: 'Jun', renewals: 19, spend: 8 },
    ],
    caption: 'Renewals cliff into Apr–Jun while retention spend stays flat',
  },
  'ins-rbc-10-cross-sell-sequence': {
    kind: 'bar', xKey: 'path', series: ['rate'], perBarColor: true,
    yTitle: '2nd-product open rate (index)',
    config: { rate: { label: '2nd-product open rate' } },
    data: [
      { path: 'Sequenced', rate: 200, fill: TEAL },
      { path: 'Simultaneous', rate: 100, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Simultaneous baseline', color: GRID }],
    caption: 'Chequing→Avion→Wealth sequencing doubles second-product opens',
  },
  'ins-rbc-11-fraud-trust': {
    kind: 'bar', xKey: 'creative', series: ['lift'], perBarColor: true,
    yTitle: 'Switcher-intent lift / impression (index)',
    config: { lift: { label: 'Switcher-intent lift' } },
    data: [
      { creative: 'E-transfer security', lift: 148, fill: TEAL },
      { creative: 'Cash-bonus', lift: 100, fill: MUTED },
      { creative: 'Convenience', lift: 88, fill: MUTED },
      { creative: 'Rewards', lift: 79, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Cash-bonus baseline', color: GRID }],
    caption: 'Security message leads switcher-intent lift but holds little rotation',
  },
  'ins-rbc-12-open-banking': {
    kind: 'line', xKey: 'period', series: ['conquest', 'retention'],
    yTitle: 'Mix weight (%)',
    config: { conquest: { label: 'Conquest weight', color: PURPLE }, retention: { label: 'Always-on retention', color: TEAL } },
    data: [
      { period: 'Now', conquest: 72, retention: 28 },
      { period: 'H2-26', conquest: 64, retention: 36 },
      { period: 'H1-27', conquest: 55, retention: 45 },
      { period: 'Go-live', conquest: 50, retention: 50 },
    ],
    refLines: [{ axis: 'x', value: 'Go-live', label: 'Open banking 2027', color: GRID }],
    caption: 'Friction falls in 2027 — shift toward defending portable balances',
  },
  'ins-rbc-13-avion-seasonality': {
    kind: 'line', xKey: 'week', series: ['west', 'national'],
    yTitle: 'Travel-redemption intent (index)',
    config: { west: { label: 'AB + BC', color: TEAL }, national: { label: 'National avg', color: PURPLE } },
    data: [
      { week: 'W1', west: 118, national: 96 }, { week: 'W2', west: 134, national: 100 },
      { week: 'W3', west: 141, national: 108 }, { week: 'W4', west: 132, national: 121 },
      { week: 'W5', west: 119, national: 134 }, { week: 'W6', west: 108, national: 140 },
    ],
    caption: 'Western redemption intent leads the national peak by ~6 weeks',
  },
  'ins-rbc-14-linkedin-smallbiz': {
    kind: 'bar', xKey: 'channel', series: ['cpb', 'budget'],
    yTitle: 'Indexed',
    config: { cpb: { label: 'Cost per booking', color: RED }, budget: { label: 'Budget share', color: BLUE } },
    data: [
      { channel: 'LinkedIn', cpb: 100, budget: 26 },
      { channel: 'Facebook', cpb: 198, budget: 58 },
      { channel: 'Search', cpb: 132, budget: 16 },
    ],
    caption: 'LinkedIn books at half Facebook\'s cost but holds a quarter of budget',
  },
  'ins-rbc-15-quebec-french': {
    kind: 'bar', xKey: 'variant', series: ['index'], perBarColor: true,
    yTitle: 'Account-open index',
    config: { index: { label: 'Account-open index' } },
    data: [
      { variant: 'French-first', index: 133, fill: TEAL },
      { variant: 'Translated national', index: 100, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Translated baseline', color: GRID }],
    caption: 'Purpose-built French creative lifts account-open ~33% over translation',
  },
  'ins-rbc-16-wealth-ctv-mix': {
    kind: 'scatter', xKey: 'spend', series: ['cost'],
    xName: 'Budget share (%)', yName: 'Cost per consultation ($)', perBarColor: true,
    config: { cost: { label: 'Cost per consultation' } },
    legend: [
      { label: 'CTV (over-delivered)', color: RED },
      { label: 'Search (capped)', color: TEAL },
    ],
    data: [
      { spend: 46, cost: 410, fill: RED, name: 'CTV' },
      { spend: 22, cost: 168, fill: TEAL, name: 'Search' },
      { spend: 19, cost: 240, fill: GOLD, name: 'TTD' },
      { spend: 13, cost: 205, fill: PURPLE, name: 'LinkedIn' },
    ],
    caption: 'CTV holds the budget at the worst cost-per-consultation; search is capped',
  },
  'ins-rbc-17-booking-funnel': {
    kind: 'bar', xKey: 'product', series: ['booking', 'online'],
    yTitle: 'Conversion rate (index)',
    config: { booking: { label: 'Advisor-booking journey', color: TEAL }, online: { label: 'Online-application journey', color: MUTED } },
    data: [
      { product: 'Mortgages', booking: 205, online: 100 },
      { product: 'Wealth', booking: 224, online: 100 },
      { product: 'Small Business', booking: 188, online: 100 },
    ],
    caption: 'Advisor-booking journeys convert ~2x online-application on big-ticket products',
  },
};
