// ===========================================================================
// Safeway (Western full-service grocery banner) — Sobeys / Empire client instance
// Representative campaign data + a full insight list + market news.
// Figures are illustrative (a demo dataset), grounded in Safeway's real
// categories, shopper segments, and Western Canada footprint.
// (Internal slugs retain the legacy `rbc-*` keys; only labels/copy are grocery.)
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, PURPLE, MUTED, GRID, BLUE, GOLD } from '../insight-visual-types';

export const RBC_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (Safeway Creative) ──
  { id: 'rbc-everyday-brand', name: 'Fresh & Produce — Western Fresh, Every Day',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-chequing',
    audiences: ['rbc-switchers', 'rbc-students'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'spotify'], geos: ['national'], budgetMultiplier: 1.70,
    plannedBudget: 14_800_000, revPerConvRange: [320, 720], cvrModifier: 0.95, cplCalibration: 0.70, revTrend: 0.0003 },
  { id: 'rbc-mortgages-spring', name: 'Meat & Seafood — Spring Grilling Window',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-mortgages',
    audiences: ['rbc-first-home', 'rbc-mass-affluent'], objective: 'consideration', status: 'live',
    channels: ['google-search', 'facebook', 'instagram', 'ttd'], geos: ['national', 'ontario', 'bc'], budgetMultiplier: 1.55,
    plannedBudget: 12_200_000, revPerConvRange: [1_900, 3_300], cvrModifier: 1.15, cplCalibration: 0.85, revTrend: 0.0006 },
  { id: 'rbc-avion-conquest', name: 'Bakery & Deli — Scene+ Member Conquest',
    enterprise: 'rbc', division: 'tier-1', agency: 'rbc-bbdo', productLine: 'rbc-avion',
    audiences: ['rbc-switchers', 'rbc-mass-affluent'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'instagram', 'facebook', 'ttd'], geos: ['national'], budgetMultiplier: 1.20,
    plannedBudget: 8_600_000, revPerConvRange: [420, 920], cvrModifier: 1.25, cplCalibration: 0.80, revTrend: 0.0004 },

  // ── TIER 2 — REGIONAL / MEDIA (Safeway Media) ──
  { id: 'rbc-newcomers-arrive', name: 'World Foods — New-to-Canada Pantry',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-newcomers',
    audiences: ['rbc-newcomers-aud', 'rbc-students'], objective: 'consideration', status: 'live',
    channels: ['facebook', 'instagram', 'google-search', 'tiktok'], geos: ['ontario', 'bc'], budgetMultiplier: 1.05,
    plannedBudget: 6_400_000, revPerConvRange: [360, 820], cvrModifier: 1.10, cplCalibration: 0.90, revTrend: 0.0005 },
  { id: 'rbc-wealth-affluent', name: 'Centre-Store Grocery — Stock-Up Always-On',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-wealth',
    audiences: ['rbc-mass-affluent'], objective: 'consideration', status: 'live',
    channels: ['linkedin', 'google-search', 'ttd', 'ctv'], geos: ['national', 'ontario'], budgetMultiplier: 1.00,
    plannedBudget: 7_800_000, revPerConvRange: [1_300, 2_700], cvrModifier: 1.05, cplCalibration: 0.75, revTrend: 0.0004 },
  { id: 'rbc-students-bts', name: 'Fresh & Produce — Back-to-School Lunch Value',
    enterprise: 'rbc', division: 'tier-2', agency: 'rbc-initiative', productLine: 'rbc-chequing',
    audiences: ['rbc-students'], objective: 'conversion', status: 'paused',
    channels: ['tiktok', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.85,
    plannedBudget: 3_900_000, revPerConvRange: [220, 560], cvrModifier: 1.20, cplCalibration: 0.95, revTrend: 0.0003 },

  // ── TIER 3 — STORE & LOCAL ──
  { id: 'rbc-smallbiz-local', name: 'Floral & Seasonal — Local Store Events',
    enterprise: 'rbc', division: 'tier-3', agency: 'rbc-branch', productLine: 'rbc-business',
    audiences: ['rbc-small-biz'], objective: 'conversion', status: 'live',
    channels: ['google-search', 'facebook', 'linkedin'], geos: ['ontario', 'alberta'], budgetMultiplier: 0.80,
    plannedBudget: 3_200_000, revPerConvRange: [640, 1_480], cvrModifier: 1.00, cplCalibration: 0.88, revTrend: 0.0004 },
  { id: 'rbc-mortgage-renewal', name: 'Meat & Seafood — Weekly Flyer Retention',
    enterprise: 'rbc', division: 'tier-3', agency: 'rbc-branch', productLine: 'rbc-mortgages',
    audiences: ['rbc-mass-affluent', 'rbc-first-home'], objective: 'retention', status: 'live',
    channels: ['google-search', 'facebook'], geos: ['national'], budgetMultiplier: 0.75,
    plannedBudget: 2_900_000, revPerConvRange: [1_500, 2_800], cvrModifier: 1.10, cplCalibration: 0.92, revTrend: 0.0005 },
];

export const RBC_NEWS: NewsItem[] = [
  { id: 'news-rbc-boc-rate-hold', title: 'StatCan: Western Food Inflation Cools to 2.4% — Shoppers Expected to Trade Back Up to Fresh & Centre-Store',
    source: 'Statistics Canada', date: '2026-05-07', tags: ['macro'], urgency: 'high', regions: ['national'],
    summary: 'Food-at-home inflation across the Prairies and BC eased to 2.4% year-over-year for a third consecutive month, the slowest pace in two years. Easing price pressure is loosening household grocery budgets heading into the summer season.',
    whyItMatters: 'Cooling inflation removes the biggest brake on basket size — shoppers trade back up to fresh and premium centre-store. STRATIS flags the Spring Grilling Meat & Seafood flight as the campaign most exposed to the demand shift; flyer-item search is the leading indicator to watch.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-newcomer-targets', title: "Ottawa Confirms 2026 Immigration Levels — ~395K New Permanent Residents, Concentrated in ON & BC",
    source: 'IRCC', date: '2026-05-04', tags: ['macro', 'partnerships'], urgency: 'high', regions: ['ontario', 'bc'],
    summary: 'Immigration, Refugees and Citizenship Canada confirmed 2026 permanent-resident targets of roughly 395,000, with settlement concentrated in the Greater Vancouver area and other Western urban centres.',
    whyItMatters: 'New Canadians choose a primary grocery store within weeks of arrival — a narrow, high-value loyalty window. The World Foods flight is regionally weighted to exactly where arrivals land; STRATIS is watching for under-served arrival communities.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-td-cashback-offer', title: 'Save-On-Foods Launches Aggressive "Big Hauler" Price-Drop Event — Heaviest Value Push in Two Years',
    source: 'Western Grocer', date: '2026-05-06', tags: ['competitors', 'value'], urgency: 'high', competitor: 'Save-On-Foods',
    regions: ['national'], summary: 'Save-On-Foods began a multi-week "Big Hauler" price-drop event across its BC and Alberta stores — deep cuts on centre-store staples and meat, backed by a heavy flyer, paid-search and social buy.',
    whyItMatters: 'A direct value threat to Fresh & Produce and Bakery & Deli basket share. STRATIS detected branded "Safeway vs Save-On" and "cheapest groceries" comparison search rising in the days after launch — reported as correlation, see the linked recommendation.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-interac-fraud', title: 'Scene+ Reports Surge in Western Member Enrolments — Banners Asked to Lead Personalized-Offer Messaging',
    source: 'Scene+', date: '2026-04-29', tags: ['loyalty', 'social'], urgency: 'medium', regions: ['national'],
    summary: 'Scene+ flagged a quarter-over-quarter rise in new member enrolments across Western Canada and asked partner banners to amplify personalized weekly-offer messaging to activate the new cohort.',
    whyItMatters: 'A loyalty-engagement opportunity adjacent to the Fresh & Produce platform — Scene+ personalized offers are a proven basket-share driver. No spend reallocation required yet; tracked at the brand level.',
    enterprises: ['rbc'] },
  { id: 'news-rbc-open-banking', title: 'Voilà by Sobeys Confirms Western E-Commerce Expansion — New Calgary Fulfilment Live 2027',
    source: 'Empire Company', date: '2026-04-22', tags: ['launch', 'grocery'], urgency: 'medium', regions: ['national'],
    summary: 'Empire confirmed a Western e-commerce expansion for Voilà, with new automated fulfilment serving Calgary and the Prairies phasing in through 2027 to extend online grocery reach beyond BC.',
    whyItMatters: 'Lowers the friction that protects in-store basket share — raising the stakes on online conquest and member retention simultaneously. A structural signal STRATIS is correlating against weekly-flyer and conquest performance.',
    enterprises: ['rbc'] },
];

export const RBC_RADAR_PINS = ['news-rbc-boc-rate-hold', 'news-rbc-td-cashback-offer', 'news-rbc-newcomer-targets'];

export const RBC_INSIGHTS: Insight[] = [
  {
    id: 'ins-rbc-01-frequency-cap', createdAt: todayISO,
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['ctv', 'ooh', 'instagram', 'ttd'],
    title: 'Across All Six Live Categories, the Average Vancouver Shopper Sees a Safeway Ad 26x a Week — Most of It the Same Two Categories',
    summary: 'Fresh & Produce, Meat & Seafood, Bakery & Deli, and Centre-Store all buy the same Premium-Fresh shopper independently, and no cap exists across categories. Deduped across every live Safeway campaign, that shopper sees ~26 Safeway exposures a week, heavily skewed to Fresh & Produce and Meat & Seafood — while Centre-Store and Floral & Seasonal are under-delivered to the same reachable audience. A portfolio-level frequency cap pulls combined weight back to the effective range and frees impressions for the categories being starved.',
    evidence: [
      'Deduped across all 8 live Safeway campaigns: ~26 ad exposures/week to the average reached Western shopper',
      'Per-campaign caps are respected; no portfolio-level cap exists across categories',
      '~60% of combined weight lands on Fresh & Produce + Meat & Seafood',
      'Centre-Store and Floral & Seasonal reach <30% of the same addressable Premium-Fresh pool',
      'Visible only by deduping audiences across every category at once',
    ],
    confidence: 0.86,
    impactEstimate: 'A portfolio-level frequency cap redeploys over-delivered Fresh & Produce weight into under-reached Centre-Store and Floral & Seasonal audiences with no loss of net reach.',
    recommendedAction: 'Set a portfolio-level frequency cap across all live Safeway categories and reallocate recovered weight to under-reached Centre-Store and Floral & Seasonal audiences.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Set a portfolio-level frequency cap', subtitle: 'ACROSS ALL LIVE CATEGORIES', type: 'bidding', completed: false },
      { id: 's2', title: 'Redeploy recovered weight to Centre-Store + Floral & Seasonal', subtitle: 'PRESERVE NET REACH', type: 'budget', completed: false },
      { id: 's3', title: 'Monitor combined exposure continuously', subtitle: 'STRATIS DEDUPES + ENFORCES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-02-td-conquest', createdAt: at(1, '08:30:00'),
    enterprise: 'rbc', category: 'competitive-macro', scope: 'product', productLine: 'rbc-chequing',
    channels: ['google-search', 'instagram', 'facebook'],
    title: "Save-On's \"Big Hauler\" Event Is Lifting 'Safeway vs Save-On' Comparison Search — Defend Basket Share Before Shoppers Switch Stores",
    summary: "In the days after Save-On-Foods' \"Big Hauler\" price-drop event, branded 'Safeway vs Save-On' and 'cheapest groceries this week' search rose sharply — a leading indicator that value shoppers are actively comparing flyers. Safeway currently bids defensively on only a fraction of those comparison terms, and the matching weekly-flyer value offer is not surfaced in the comparison moment. A focused search-defense and a matched price-match flyer feature captures shoppers already in-market rather than ceding the trip. Correlation, not causation — but the window is short.",
    evidence: [
      "'Safeway vs Save-On' and 'cheapest groceries Western Canada' search volume up materially since the Save-On launch",
      'Safeway bids on a minority of high-intent comparison queries; Save-On is bidding on Safeway-brand terms',
      'The matching weekly-flyer value offer is not present in the comparison-shopping moment',
      'Conquest basket-conversion is highest within the first 10 days of a competitor price event',
    ],
    confidence: 0.82,
    impactEstimate: 'Defending comparison search and surfacing a matched flyer offer recaptures in-market shoppers before the competitor price window closes.',
    recommendedAction: 'Expand defensive search coverage on Safeway-vs-Save-On comparison terms and surface a matched weekly-flyer value feature in the comparison moment.',
    status: 'new',
    linkedNewsId: 'news-rbc-td-cashback-offer',
    actionSteps: [
      { id: 's1', title: 'Expand defensive comparison-term coverage', subtitle: 'CONQUEST + BRAND-DEFENSE', type: 'bidding', completed: false },
      { id: 's2', title: 'Surface a matched weekly-flyer value feature', subtitle: 'FRESH & PRODUCE', type: 'creative', completed: false },
      { id: 's3', title: 'Track conquest conversion daily through the window', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-03-mortgage-timing', createdAt: at(2, '10:15:00'),
    enterprise: 'rbc', category: 'national-regional', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search', 'ttd', 'facebook'],
    title: 'Grilling Demand Is Firming in the West Two Weeks Ahead of Ontario — National Pacing Is Under-Weighting the Earlier Market',
    summary: 'Flyer-item search and meat-counter basket starts are rising in the West roughly two weeks before the same lift appears in Ontario, but the national Meat & Seafood flight paces budget evenly across both. The result is Western demand outrunning delivery while Ontario weight arrives before its demand does. Front-loading the West and lagging Ontario to match the real demand curve captures more grilling baskets at a higher ROAS across the same total budget.',
    evidence: [
      'Western flyer-item meat search leads Ontario by ~14 days into the spring grilling window',
      'National flight paces evenly; it does not follow the regional demand curve',
      'Western ROAS is softening as demand outruns delivery and inventory tightens',
      'Ontario weight is arriving ahead of its demand inflection',
    ],
    confidence: 0.79,
    impactEstimate: 'Sequencing weight to the regional demand curve lifts grilling-basket volume at a higher blended ROAS with no added budget.',
    recommendedAction: 'Front-load Western Meat & Seafood weight now and lag Ontario by ~2 weeks to match the regional demand curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load Western meat weight', subtitle: 'MATCH DEMAND CURVE', type: 'budget', completed: false },
      { id: 's2', title: 'Lag Ontario delivery ~2 weeks', subtitle: 'AVOID EARLY OVER-DELIVERY', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-04-newcomer-creative', createdAt: at(4, '13:00:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-newcomers',
    channels: ['facebook', 'instagram', 'tiktok'],
    title: 'The "Taste of Home" World Foods Creative Outperforms Everywhere It Runs — but Only Carries Two of the Five Arrival Languages',
    summary: 'Ranking World Foods creative across regions, the simple "Taste of Home" execution — showing familiar pantry staples on the shelf — beats every alternative on both video completion and store-trip conversion. Yet it is localized only in English and Punjabi, while a large share of 2026 arrivals are concentrated in communities where in-language creative consistently lifts conversion. Extending the proven execution into the top arrival languages is a high-confidence scale move, not an experiment.',
    evidence: [
      '"Taste of Home" leads all World Foods creative on completion and store-trip conversion',
      'Currently localized in English and Punjabi only',
      'In-language creative shows a consistent conversion lift in newcomer communities',
      'Top 2026 arrival communities are addressable in-platform',
    ],
    confidence: 0.81,
    impactEstimate: 'Extending the proven creative into the top arrival languages scales a known winner into its highest-converting audiences.',
    recommendedAction: 'Localize the winning "Taste of Home" execution into the top arrival languages and weight delivery to matched communities.',
    status: 'new',
    linkedNewsId: 'news-rbc-newcomer-targets',
    actionSteps: [
      { id: 's1', title: 'Localize the winning creative', subtitle: 'TOP ARRIVAL LANGUAGES', type: 'creative', completed: false },
      { id: 's2', title: 'Weight delivery to matched communities', subtitle: 'ON + BC SETTLEMENT AREAS', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-05-audience-overlap', createdAt: at(6, '09:45:00'),
    enterprise: 'rbc', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'ttd'],
    title: 'Premium-Fresh Shoppers Are Being Bid On by Four Categories at Once — Safeway Is Competing Against Itself in the Auction',
    summary: 'Fresh & Produce, Meat & Seafood, Bakery & Deli, and Centre-Store all target overlapping Premium-Fresh shopper segments in the same auctions, bidding up Safeway\'s own CPMs against itself. STRATIS measures the overlap at roughly a third of the addressable pool. Coordinating bids and sequencing the category story per shopper — rather than four categories shouting at once — lowers blended CPM and presents a coherent full-basket journey instead of internal auction competition.',
    evidence: [
      '~33% of the Premium-Fresh pool is targeted by 4+ live Safeway campaigns simultaneously',
      'Overlapping demand is inflating Safeway-vs-Safeway auction CPMs',
      'No cross-category sequencing exists for shared shoppers',
      'Coordinated bidding lowers blended CPM with no reach loss',
    ],
    confidence: 0.77,
    impactEstimate: 'De-duplicating internal auction competition lowers blended CPM and turns four competing messages into a sequenced full-basket journey.',
    recommendedAction: 'Coordinate bids across categories on shared Premium-Fresh audiences and sequence the full-basket story per shopper.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Coordinate bids on shared audiences', subtitle: 'STOP SAFEWAY-VS-SAFEWAY COMPETITION', type: 'bidding', completed: false },
      { id: 's2', title: 'Sequence the full-basket story per shopper', subtitle: 'ONE JOURNEY, NOT FOUR', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-06-agency-arbitrage', createdAt: at(9, '11:20:00'),
    enterprise: 'rbc', category: 'agency-arbitrage', scope: 'brand',
    channels: ['google-search', 'facebook', 'linkedin'],
    title: 'Store & Local Is Beating National on ROAS for the Same Category — the Local Playbook Should Cascade Up',
    summary: 'On Meat & Seafood, the Tier 3 Store & Local team is delivering a materially higher ROAS than the national Tier 1 flight for the same category, driven by tighter store-radius targeting and "this-week-in-your-store" flyer creative. The pattern repeats across Floral & Seasonal. Rather than treat this as a local anomaly, the national flight should adopt the Store & Local playbook\'s targeting and flyer-led creative where it scales.',
    evidence: [
      'Store & Local ROAS on Meat & Seafood is above the national flight for the same category',
      'Advantage traces to store-radius targeting + "this-week-in-your-store" flyer creative',
      'Same pattern holds on Floral & Seasonal',
      'National flight does not currently use the Store & Local flyer-led creative',
    ],
    confidence: 0.75,
    impactEstimate: 'Cascading the Store & Local targeting and flyer-led creative into the national flight lifts blended ROAS at scale.',
    recommendedAction: 'Adopt the Store & Local geo-targeting and weekly-flyer creative in the national Meat & Seafood flight where it scales.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the Store & Local playbook', subtitle: 'TARGETING + FLYER CREATIVE', type: 'targeting', completed: false },
      { id: 's2', title: 'Cascade into the national Meat & Seafood flight', subtitle: 'WHERE IT SCALES', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-07-search-headroom', createdAt: at(3, '09:40:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search'],
    title: 'Meat & Seafood Paid Search Is Capped ~20% Below the Point Where ROAS Starts to Fall',
    summary: 'Marginal ROAS on the Meat & Seafood search flight holds flat until roughly 30% above the current spend cap, then begins to fall — so the cap is leaving in-market grilling baskets unclaimed at target ROAS. Lifting the ceiling toward the inflection captures incremental baskets without degrading efficiency. STRATIS tracks the marginal curve continuously so the cap follows profitability, not a fixed budget line.',
    evidence: [
      'Marginal ROAS holds flat from the current cap to ~+30% spend',
      'ROAS softens only beyond that point',
      'The current cap sits ~20% below the inflection',
      'In-market flyer-item demand is unmet at target ROAS inside the headroom',
    ],
    confidence: 0.78,
    impactEstimate: 'Raising the cap to the marginal-ROAS inflection captures incremental baskets still at target efficiency.',
    recommendedAction: 'Lift the Meat & Seafood search cap toward the marginal-ROAS inflection and hold it there as STRATIS tracks the curve.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Lift the search cap to the ROAS inflection', subtitle: 'MAINTAIN TARGET ROAS', type: 'budget', completed: false },
      { id: 's2', title: 'Track marginal ROAS continuously', subtitle: 'STRATIS HOLDS THE CURVE', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-08-wealth-underreach', createdAt: at(7, '10:50:00'),
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['ttd', 'linkedin', 'google-search'],
    title: 'Centre-Store and Floral & Seasonal Reach Under 30% of the Premium-Fresh Base the Brand Already Pays to Reach',
    summary: 'Fresh & Produce and Meat & Seafood saturate the Premium-Fresh shopper audience while Centre-Store and Floral & Seasonal — the highest-margin, basket-building categories — reach less than a third of the same addressable base. The brand already pays to reach these shoppers through other categories, so extending coverage to the under-served high-margin categories is reach the portfolio is leaving unclaimed rather than new audience to buy.',
    evidence: [
      'Fresh & Produce + Meat & Seafood reach >60% of the Premium-Fresh base',
      'Centre-Store reaches ~28%, Floral & Seasonal ~24% of the same base',
      'These are among the highest-margin basket-builders in the portfolio',
      'The base is already addressable through other live categories',
    ],
    confidence: 0.80,
    impactEstimate: 'Extending high-margin category reach into the already-paid-for base claims unclaimed coverage at low marginal cost.',
    recommendedAction: 'Reallocate over-delivered Fresh & Produce / Meat reach toward Centre-Store and Floral & Seasonal across the shared Premium-Fresh base.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Extend Centre-Store + Floral & Seasonal reach', subtitle: 'SHARED PREMIUM-FRESH BASE', type: 'targeting', completed: false },
      { id: 's2', title: 'Fund from over-delivered categories', subtitle: 'NO NEW BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-rbc-09-renewal-cliff', createdAt: at(2, '08:55:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-mortgages',
    channels: ['google-search', 'facebook'],
    title: 'The Meat & Seafood Flyer Flight Is Spending Flat — but 60% of Summer Grilling Volume Lands in a Single 90-Day Window',
    summary: 'The bulk of the year\'s grilling and BBQ basket volume concentrates into one 90-day summer window — long weekends, patio season, holiday cookouts — rather than spreading evenly. The flyer-retention flight, however, paces a flat monthly budget, under-delivering in the peak window when shopper intent and competitor pressure both spike, and over-delivering in the quiet months. Front-loading flyer spend into the grilling peak defends the highest-margin baskets exactly when they are in play. With food inflation cooling, shoppers are trading up to premium cuts harder than usual.',
    evidence: [
      '~60% of 2026 grilling-basket volume lands inside a single 90-day summer window',
      'The flyer-retention flight paces flat monthly spend, ignoring the demand curve',
      'Branded "BBQ deals this week" search concentrates ahead of the long weekends',
      'Competitor price pressure on meat is highest in the 45 days before each long weekend',
      'Visible only by aligning the seasonal demand curve against media pacing',
    ],
    confidence: 0.83,
    impactEstimate: 'Concentrating flyer weight into the grilling peak defends high-margin baskets at the moment of highest competitor pressure with no added budget.',
    recommendedAction: 'Re-pace the flyer flight to front-load the 90-day grilling peak and pull weight out of the quiet months.',
    status: 'new',
    linkedNewsId: 'news-rbc-boc-rate-hold',
    actionSteps: [
      { id: 's1', title: 'Re-pace spend to the grilling peak', subtitle: 'FRONT-LOAD THE 90-DAY WINDOW', type: 'scheduling', completed: false },
      { id: 's2', title: 'Pull weight from quiet months', subtitle: 'NO ADDED BUDGET', type: 'budget', completed: false },
      { id: 's3', title: 'Trigger off branded BBQ-deal search', subtitle: 'STRATIS WATCHES INTENT', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-rbc-10-cross-sell-sequence', createdAt: at(5, '10:05:00'),
    enterprise: 'rbc', category: 'audience-overlap', scope: 'brand',
    channels: ['instagram', 'facebook', 'google-search', 'ttd'],
    title: 'New Shoppers Who See Bakery & Deli Before Centre-Store Build a Second-Category Basket 2x — but the Portfolio Pitches All Three at Once',
    summary: 'Tracing shared shoppers across categories, those who start in Fresh & Produce and are then sequenced into Bakery & Deli, and only later into Centre-Store, add a second category to their basket at roughly twice the rate of those hit by all three messages simultaneously. Today every category bids the same new-shopper cohort independently, so the cross-category story arrives scrambled. Enforcing a produce→bakery/deli→centre-store sequence on shared shoppers turns four competing pitches into one compounding basket-building journey — and only STRATIS sees the cohort across all categories at once.',
    evidence: [
      'Produce→Bakery/Deli→Centre-Store sequenced shoppers add a 2nd category ~2x vs. simultaneous exposure',
      'All three categories currently bid the new-shopper cohort independently',
      'No ordering logic exists on shared new-to-banner shoppers',
      'Centre-Store stock-up uptake is highest 60–90 days after first trip, not on day one',
      'The cohort is only visible by joining Scene+ identity across categories',
    ],
    confidence: 0.78,
    impactEstimate: 'Sequencing the cross-category story lifts second-category basket rates without buying any new audience.',
    recommendedAction: 'Enforce a produce→bakery/deli→centre-store message sequence on shared new-to-banner shoppers instead of pitching all three at once.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Define the cross-category sequence', subtitle: 'PRODUCE → BAKERY/DELI → CENTRE-STORE', type: 'targeting', completed: false },
      { id: 's2', title: 'Suppress later categories until stage unlocks', subtitle: 'ONE JOURNEY PER SHOPPER', type: 'targeting', completed: false },
      { id: 's3', title: 'Time Centre-Store to the 60–90 day window', subtitle: 'STRATIS TRACKS COHORTS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-11-fraud-trust', createdAt: at(8, '12:30:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-chequing',
    channels: ['facebook', 'instagram', 'spotify'],
    title: 'The Scene+ Personalized-Offer Message Lifts Trip Intent More Than Any Price-Drop Creative — and It Is Barely in Rotation',
    summary: 'Among Fresh & Produce executions, the Scene+ "your weekly personalized offers" / loyalty message is driving the strongest lift in store-trip consideration per impression — outperforming the generic price-drop creative that dominates the rotation. With Scene+ asking banners to lead personalized-offer messaging to the new member cohort, the loyalty angle is both timely and differentiated, yet it sits at a sliver of delivery. Re-weighting rotation toward the Scene+ message captures a proven basket-share driver at the exact moment enrolments are surging. This is a creative-mix shift, not new spend.',
    evidence: [
      'Scene+ personalized-offer creative leads all Fresh & Produce executions on trip-intent lift',
      'It currently holds a small share of rotation vs. generic price-drop creative',
      'Personalized loyalty offers are a proven driver of basket share in grocery',
      'Scene+ has asked partner banners to lead personalized-offer messaging',
      'Lift is measured per impression, controlling for delivery weight',
    ],
    confidence: 0.79,
    impactEstimate: 'Re-weighting rotation toward the Scene+ message scales the highest trip-intent creative at no added cost.',
    recommendedAction: 'Shift Fresh & Produce creative rotation toward the Scene+ personalized-offer message while member enrolments are surging.',
    status: 'new',
    linkedNewsId: 'news-rbc-interac-fraud',
    actionSteps: [
      { id: 's1', title: 'Re-weight rotation to the Scene+ message', subtitle: 'LOYALTY OVER PRICE-DROP', type: 'creative', completed: false },
      { id: 's2', title: 'Target high-intent conquest segments', subtitle: 'SAVE-ON SWITCHERS', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-rbc-12-open-banking', createdAt: at(11, '09:15:00'),
    enterprise: 'rbc', category: 'competitive-macro', scope: 'brand',
    channels: ['google-search', 'linkedin', 'ttd'],
    title: 'Voilà Goes Live in the West in 2027 — Safeway\'s Conquest and Member Retention Are Both Funded for an In-Store-Only World',
    summary: 'The confirmed Western Voilà e-commerce expansion strips away the in-store-only habit that has long protected basket share, raising the stakes on online conquest and member retention at the same time. Safeway\'s current mix still leans on in-store-trip creative built for a single-channel world and under-invests in always-on retention of its most portable shoppers — the ones most likely to try online grocery. STRATIS correlates flyer and conquest performance against the expansion timeline so the portfolio can shift toward defensible omni-channel retention before the habit shifts — a structural reallocation, not a campaign tweak.',
    evidence: [
      'Voilà Western fulfilment phases in through 2027, lowering the in-store-only habit across the region',
      'Current mix over-indexes on single-channel in-store-trip creative',
      'Most-portable shoppers (Fresh & Produce, Bakery & Deli regulars) are under-defended in always-on retention',
      'Online conquest upside and switching risk both rise as the channel opens',
      'STRATIS correlates flyer + conquest performance against the expansion timeline',
    ],
    confidence: 0.74,
    impactEstimate: 'Rebalancing toward always-on retention of portable shoppers protects basket share before the omni-channel habit shifts.',
    recommendedAction: 'Shift mix toward always-on retention of portable shoppers ahead of Voilà Western go-live while sustaining online conquest.',
    status: 'new',
    linkedNewsId: 'news-rbc-open-banking',
    actionSteps: [
      { id: 's1', title: 'Fund always-on retention of portable shoppers', subtitle: 'FRESH & PRODUCE + BAKERY/DELI', type: 'budget', completed: false },
      { id: 's2', title: 'Hold conquest pressure on switchers', subtitle: 'BOTH SIDES OF THE GATE', type: 'targeting', completed: false },
      { id: 's3', title: 'Track performance vs. 2027 timeline', subtitle: 'STRATIS CORRELATES', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-13-avion-seasonality', createdAt: at(13, '11:40:00'),
    enterprise: 'rbc', category: 'national-regional', scope: 'product', productLine: 'rbc-avion',
    channels: ['instagram', 'facebook', 'google-search', 'ttd'],
    title: 'Bakery & Deli Entertaining Demand Surges in Alberta and BC Six Weeks Before the National Peak — but Spend Is National-Flat',
    summary: 'Party-platter and deli-tray search and Bakery & Deli basket-intent signals spike earlier and harder in Alberta and BC ahead of the summer entertaining window, while the conquest flight pumps a flat national budget. Western shoppers are entering the entertaining mindset weeks before the national average, so the platter pitch lands there when intent is hottest yet receives no extra weight. Regionally front-loading Bakery & Deli into the early-demand markets captures shoppers at peak entertaining-intent at a higher ROAS. Only a portfolio view exposes the regional lead.',
    evidence: [
      'Alberta + BC platter / deli-tray search leads the national peak by ~6 weeks',
      'The Bakery & Deli conquest flight paces a flat national budget',
      'Conquest ROAS rises when the platter pitch meets active entertaining-intent',
      'Western entertaining intent cools as the national average peaks',
      'Regional lead is only visible deduped across the national flight',
    ],
    confidence: 0.76,
    impactEstimate: 'Front-loading Bakery & Deli into early-demand Western markets captures shoppers at peak entertaining-intent at a higher ROAS.',
    recommendedAction: 'Front-load Bakery & Deli conquest weight into Alberta and BC ahead of the national entertaining peak.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load Bakery & Deli in AB + BC', subtitle: 'AHEAD OF NATIONAL PEAK', type: 'budget', completed: false },
      { id: 's2', title: 'Sync creative to entertaining intent', subtitle: 'MEET THE PLATTER MINDSET', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-14-linkedin-smallbiz', createdAt: at(10, '09:30:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-business',
    channels: ['linkedin', 'google-search', 'facebook'],
    title: 'On Floral & Seasonal, LinkedIn Is Delivering Catering & Corporate Orders at Half the Cost of Facebook — but Holds a Quarter of the Budget',
    summary: 'Across the Floral & Seasonal flight, LinkedIn is producing qualified catering and corporate-gifting leads at roughly half the cost-per-order of Facebook, with higher order value from office-manager and event-planner targeting. Yet budget allocation is inverted — Facebook holds the majority of spend while the more efficient channel is starved. Shifting weight toward LinkedIn up to the point its cost-per-order starts to climb captures more qualified orders at the same total spend. STRATIS tracks the marginal curve so the shift stops at efficiency, not at a fixed split.',
    evidence: [
      'LinkedIn cost-per-catering-order is ~50% of Facebook on the Floral & Seasonal flight',
      'Budget is inverted — Facebook holds the majority of spend',
      'LinkedIn office-manager/event-planner targeting yields higher order value',
      'LinkedIn has marginal headroom before cost-per-order inflects',
      'Efficiency gap is only visible normalizing order quality across channels',
    ],
    confidence: 0.80,
    impactEstimate: 'Re-weighting Floral & Seasonal spend toward LinkedIn captures more qualified catering orders at the same total budget.',
    recommendedAction: 'Shift Floral & Seasonal budget toward LinkedIn up to its marginal cost-per-order inflection.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift budget toward LinkedIn', subtitle: 'CHASE COST-PER-ORDER', type: 'budget', completed: false },
      { id: 's2', title: 'Hold the shift at the inflection', subtitle: 'STRATIS TRACKS THE CURVE', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-rbc-15-quebec-french', createdAt: at(14, '10:25:00'),
    enterprise: 'rbc', category: 'creative-performance', scope: 'product', productLine: 'rbc-chequing',
    channels: ['facebook', 'instagram', 'tiktok'],
    title: 'The West Is Running Repurposed National Creative — Purpose-Built "Western Fresh & Local" Executions Lift Conversion a Third Where They Exist',
    summary: 'In the Western markets, most Fresh & Produce delivery is direct repurposing of the national creative rather than purpose-built "Western fresh & local" executions — Okanagan fruit, Alberta-grown, BC seafood. Where genuinely local-first creative does run, completion and store-trip rates lift by roughly a third, and the work also sits more cleanly against Western shoppers\' "buy local" expectations. Treating the West as a repurposed afterthought leaves both performance and brand fit on the table; commissioning local-first executions for the top-spend formats is a high-confidence creative move tied to a region that buys differently.',
    evidence: [
      'Most Western delivery is repurposed national creative, not local-first work',
      'Purpose-built "Western fresh & local" executions lift store-trip rate ~33% where they run',
      'Local-first work fits Western "buy local" expectations more cleanly',
      'Repurposed creative under-indexes on completion in the West vs. the national average',
      'Gap is only visible comparing Western creative variants head-to-head',
    ],
    confidence: 0.77,
    impactEstimate: 'Commissioning local-first executions for top-spend formats scales a proven conversion lift in a region that buys differently.',
    recommendedAction: 'Commission purpose-built "Western fresh & local" creative for the top-spend formats instead of repurposing national work.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Commission local-first executions', subtitle: 'TOP-SPEND WESTERN FORMATS', type: 'creative', completed: false },
      { id: 's2', title: 'A/B against repurposed control', subtitle: 'PROVE THE LIFT', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-rbc-16-wealth-ctv-mix', createdAt: at(12, '13:20:00'),
    enterprise: 'rbc', category: 'tactical-efficiency', scope: 'product', productLine: 'rbc-wealth',
    channels: ['ctv', 'google-search', 'ttd', 'linkedin'],
    title: 'Centre-Store Pours Budget Into CTV Awareness While High-Intent Search Sits Capped — the Mix Is Inverted for a Stock-Up Trip',
    summary: 'The Centre-Store flight weights heavily toward CTV brand awareness, but stock-up grocery is a list-led, search-driven trip where bottom-funnel "on sale this week" queries convert far more efficiently. Search is capped well below its profitable demand while CTV runs past the point of incremental reach. Rebalancing from over-delivered CTV into uncapped high-intent search lifts qualified store trips at a higher blended ROAS. CTV still seeds awareness — but the mix should follow how this shopper actually plans the trip, not a default awareness tilt.',
    evidence: [
      'Centre-Store budget skews to CTV awareness over bottom-funnel search',
      'High-intent Centre-Store search converts trips far more efficiently than CTV',
      'Search is capped below profitable demand; CTV runs past incremental reach',
      'Stock-up grocery is a list-led, search-driven trip',
      'The efficiency inversion is only visible comparing channels on cost-per-trip',
    ],
    confidence: 0.78,
    impactEstimate: 'Rebalancing from over-delivered CTV into uncapped high-intent search lifts qualified store trips at a higher blended ROAS.',
    recommendedAction: 'Shift Centre-Store budget from over-delivered CTV awareness into uncapped high-intent search.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Lift the Centre-Store search cap', subtitle: 'CHASE HIGH-INTENT DEMAND', type: 'budget', completed: false },
      { id: 's2', title: 'Trim CTV past incremental reach', subtitle: 'KEEP AN AWARENESS FLOOR', type: 'budget', completed: false },
      { id: 's3', title: 'Track cost-per-trip by channel', subtitle: 'STRATIS HOLDS THE MIX', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-rbc-17-booking-funnel', createdAt: at(15, '09:50:00'),
    enterprise: 'rbc', category: 'strategic-opener', scope: 'brand',
    channels: ['google-search', 'facebook', 'linkedin'],
    title: '"Add-to-List / Voilà Cart" Journeys Convert Twice as Often as Single-Item Click Journeys on Basket-Building Categories — but Get a Third of the Spend',
    summary: 'On the most basket-building categories — Meat & Seafood, Centre-Store, and Floral & Seasonal — journeys that route shoppers into an add-to-list or Voilà-cart action convert to a full trip at roughly double the rate of single-item click journeys, yet the portfolio still defaults most spend to single-item promo creative. The cart funnel wins because these trips are planned around a list, and the Store & Local team already proves it at the local level. Re-pointing basket-building creative toward add-to-list / Voilà-cart calls-to-action, rather than single-item clicks, lifts conversion across the most valuable categories. Only a cross-category view shows the funnel gap consistently.',
    evidence: [
      'Add-to-list / Voilà-cart journeys convert ~2x single-item journeys on Meat & Seafood, Centre-Store, Floral & Seasonal',
      'Most basket-building spend still defaults to single-item promo creative',
      'The cart funnel wins where the trip is planned around a list',
      'Store & Local already proves the cart funnel locally',
      'The funnel gap is only consistent across a cross-category view',
    ],
    confidence: 0.81,
    impactEstimate: 'Re-pointing basket-building creative to add-to-list / Voilà-cart CTAs lifts conversion across the most valuable categories.',
    recommendedAction: 'Default basket-building category creative to add-to-list / Voilà-cart calls-to-action over single-item clicks.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Switch CTAs to add-to-list / Voilà-cart', subtitle: 'MEAT & SEAFOOD + CENTRE-STORE + FLORAL', type: 'creative', completed: false },
      { id: 's2', title: 'Re-weight spend to the cart funnel', subtitle: 'FOLLOW THE CONVERSION', type: 'budget', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const RBC_VISUALS: Record<string, InsightVisual> = {
  'ins-rbc-01-frequency-cap': {
    kind: 'bar', xKey: 'product', series: ['freq'], perBarColor: true,
    yTitle: 'Weekly frequency',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { product: 'Fresh', freq: 11, fill: MUTED },
      { product: 'Meat', freq: 9, fill: MUTED },
      { product: 'Bakery/Deli', freq: 4, fill: MUTED },
      { product: 'Centre-Store', freq: 2, fill: MUTED },
      { product: 'Combined', freq: 26, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 12, label: 'Effective max ~12', color: TEAL }],
    caption: 'No single category over-delivers — deduped exposure hits 26×/week',
  },
  'ins-rbc-02-td-conquest': {
    kind: 'line', xKey: 'week', series: ['search'],
    yTitle: "'Safeway vs Save-On' search (indexed)",
    config: { search: { label: 'Comparison search', color: RED } },
    data: [
      { week: 'W1', search: 100 }, { week: 'W2', search: 102 }, { week: 'W3', search: 104 },
      { week: 'W4', search: 126 }, { week: 'W5', search: 133 }, { week: 'W6', search: 128 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'Save-On "Big Hauler" launches', color: GRID }],
    caption: 'Comparison search spikes the week Save-On launches — the basket-share window',
  },
  'ins-rbc-03-mortgage-timing': {
    kind: 'line', xKey: 'week', series: ['bc', 'on'],
    yTitle: 'Flyer-item meat search (index)',
    config: { bc: { label: 'West', color: TEAL }, on: { label: 'Ontario', color: PURPLE } },
    data: [
      { week: 'W1', bc: 104, on: 96 }, { week: 'W2', bc: 118, on: 99 }, { week: 'W3', bc: 131, on: 104 },
      { week: 'W4', bc: 128, on: 116 }, { week: 'W5', bc: 117, on: 129 }, { week: 'W6', bc: 108, on: 133 },
    ],
    caption: 'Western demand peaks ~2 weeks before Ontario — even pacing misses both',
  },
  'ins-rbc-04-newcomer-creative': {
    kind: 'bar', xKey: 'variant', series: ['index'], perBarColor: true,
    yTitle: 'Store-trip index',
    config: { index: { label: 'Store-trip index' } },
    data: [
      { variant: '"Taste of Home"', index: 142, fill: TEAL },
      { variant: 'Standard', index: 100, fill: MUTED },
      { variant: 'Long-form', index: 86, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Avg', color: GRID }],
    caption: 'The "Taste of Home" creative wins — but ships in only 2 of 5 arrival languages',
  },
  'ins-rbc-05-audience-overlap': {
    kind: 'bar', xKey: 'audience', series: ['campaigns'], perBarColor: true,
    yTitle: 'Live campaigns bidding',
    config: { campaigns: { label: 'Campaigns bidding' } },
    data: [
      { audience: 'Premium-Fresh', campaigns: 4, fill: RED },
      { audience: 'Young Families', campaigns: 2, fill: MUTED },
      { audience: 'New Canadians', campaigns: 2, fill: MUTED },
      { audience: 'Save-On Switchers', campaigns: 2, fill: MUTED },
      { audience: 'Students', campaigns: 1, fill: MUTED },
    ],
    caption: 'Four categories bid the same Premium-Fresh shopper — Safeway vs Safeway',
  },
  'ins-rbc-06-agency-arbitrage': {
    kind: 'bar', xKey: 'product', series: ['national', 'branch'],
    yTitle: 'ROAS',
    config: { national: { label: 'National (T1)', color: RED }, branch: { label: 'Store & Local (T3)', color: TEAL } },
    data: [
      { product: 'Meat & Seafood', national: 3.2, branch: 4.6 },
      { product: 'Floral & Seasonal', national: 2.8, branch: 3.9 },
    ],
    caption: 'Store & Local beats National on ROAS for the same categories',
  },
  'ins-rbc-07-search-headroom': {
    kind: 'line', xKey: 'spend', series: ['cpa'],
    xTitle: 'Meat & Seafood search spend (indexed)', yTitle: 'ROAS',
    config: { cpa: { label: 'Marginal ROAS', color: TEAL } },
    data: [
      { spend: 60, cpa: 4.6 }, { spend: 80, cpa: 4.5 }, { spend: 100, cpa: 4.4 },
      { spend: 120, cpa: 4.3 }, { spend: 140, cpa: 3.7 }, { spend: 160, cpa: 3.1 },
    ],
    refLines: [{ axis: 'x', value: 100, label: 'Current cap', color: RED }],
    caption: 'ROAS stays flat to ~+30% spend — the cap sits below profitable demand',
  },
  'ins-rbc-08-wealth-underreach': {
    kind: 'bar', xKey: 'product', series: ['reach'], perBarColor: true,
    yTitle: 'Reach of Premium-Fresh base (%)',
    config: { reach: { label: 'Reach %' } },
    data: [
      { product: 'Fresh', reach: 71, fill: MUTED },
      { product: 'Meat', reach: 64, fill: MUTED },
      { product: 'Bakery/Deli', reach: 52, fill: MUTED },
      { product: 'Centre-Store', reach: 28, fill: RED },
      { product: 'Floral/Seasonal', reach: 24, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 50, label: 'Portfolio avg', color: GRID }],
    caption: 'Centre-Store & Floral reach <30% of the base the brand already pays for',
  },
  'ins-rbc-09-renewal-cliff': {
    kind: 'bar', xKey: 'month', series: ['renewals', 'spend'],
    yTitle: 'Indexed share',
    config: { renewals: { label: 'Grilling volume', color: RED }, spend: { label: 'Flyer spend', color: MUTED } },
    data: [
      { month: 'Jan', renewals: 6, spend: 8 }, { month: 'Feb', renewals: 7, spend: 8 },
      { month: 'Mar', renewals: 9, spend: 9 }, { month: 'Apr', renewals: 28, spend: 9 },
      { month: 'May', renewals: 31, spend: 8 }, { month: 'Jun', renewals: 19, spend: 8 },
    ],
    caption: 'Grilling volume peaks Apr–Jun while flyer spend stays flat',
  },
  'ins-rbc-10-cross-sell-sequence': {
    kind: 'bar', xKey: 'path', series: ['rate'], perBarColor: true,
    yTitle: '2nd-category basket rate (index)',
    config: { rate: { label: '2nd-category basket rate' } },
    data: [
      { path: 'Sequenced', rate: 200, fill: TEAL },
      { path: 'Simultaneous', rate: 100, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Simultaneous baseline', color: GRID }],
    caption: 'Produce→Bakery/Deli→Centre-Store sequencing doubles second-category baskets',
  },
  'ins-rbc-11-fraud-trust': {
    kind: 'bar', xKey: 'creative', series: ['lift'], perBarColor: true,
    yTitle: 'Trip-intent lift / impression (index)',
    config: { lift: { label: 'Trip-intent lift' } },
    data: [
      { creative: 'Scene+ offers', lift: 148, fill: TEAL },
      { creative: 'Price-drop', lift: 100, fill: MUTED },
      { creative: 'Convenience', lift: 88, fill: MUTED },
      { creative: 'Fresh quality', lift: 79, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Price-drop baseline', color: GRID }],
    caption: 'Scene+ message leads trip-intent lift but holds little rotation',
  },
  'ins-rbc-12-open-banking': {
    kind: 'line', xKey: 'period', series: ['conquest', 'retention'],
    yTitle: 'Mix weight (%)',
    config: { conquest: { label: 'Conquest weight', color: PURPLE }, retention: { label: 'Always-on retention', color: TEAL } },
    data: [
      { period: 'Now', conquest: 72, retention: 28 },
      { period: 'H2-26', conquest: 64, retention: 36 },
      { period: 'H1-27', conquest: 55, retention: 45 },
      { period: 'Go-live', conquest: 50, retention: 50 },
    ],
    refLines: [{ axis: 'x', value: 'Go-live', label: 'Voilà West 2027', color: GRID }],
    caption: 'The channel opens in 2027 — shift toward defending portable shoppers',
  },
  'ins-rbc-13-avion-seasonality': {
    kind: 'line', xKey: 'week', series: ['west', 'national'],
    yTitle: 'Entertaining intent (index)',
    config: { west: { label: 'AB + BC', color: TEAL }, national: { label: 'National avg', color: PURPLE } },
    data: [
      { week: 'W1', west: 118, national: 96 }, { week: 'W2', west: 134, national: 100 },
      { week: 'W3', west: 141, national: 108 }, { week: 'W4', west: 132, national: 121 },
      { week: 'W5', west: 119, national: 134 }, { week: 'W6', west: 108, national: 140 },
    ],
    caption: 'Western entertaining intent leads the national peak by ~6 weeks',
  },
  'ins-rbc-14-linkedin-smallbiz': {
    kind: 'bar', xKey: 'channel', series: ['cpb', 'budget'],
    yTitle: 'Indexed',
    config: { cpb: { label: 'Cost per order', color: RED }, budget: { label: 'Budget share', color: BLUE } },
    data: [
      { channel: 'LinkedIn', cpb: 100, budget: 26 },
      { channel: 'Facebook', cpb: 198, budget: 58 },
      { channel: 'Search', cpb: 132, budget: 16 },
    ],
    caption: 'LinkedIn orders at half Facebook\'s cost but holds a quarter of budget',
  },
  'ins-rbc-15-quebec-french': {
    kind: 'bar', xKey: 'variant', series: ['index'], perBarColor: true,
    yTitle: 'Store-trip index',
    config: { index: { label: 'Store-trip index' } },
    data: [
      { variant: 'Western local-first', index: 133, fill: TEAL },
      { variant: 'Repurposed national', index: 100, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 100, label: 'Repurposed baseline', color: GRID }],
    caption: 'Purpose-built Western local creative lifts store-trips ~33% over repurposed',
  },
  'ins-rbc-16-wealth-ctv-mix': {
    kind: 'scatter', xKey: 'spend', series: ['cost'],
    xName: 'Budget share (%)', yName: 'Cost per trip ($)', perBarColor: true,
    config: { cost: { label: 'Cost per trip' } },
    legend: [
      { label: 'CTV (over-delivered)', color: RED },
      { label: 'Search (capped)', color: TEAL },
    ],
    data: [
      { spend: 46, cost: 410, fill: RED, name: 'CTV' },
      { spend: 22, cost: 168, fill: TEAL, name: 'Search' },
      { spend: 19, cost: 240, fill: GOLD, name: 'TTD' },
      { spend: 13, cost: 205, fill: PURPLE, name: 'LinkedIn' },
    ],
    caption: 'CTV holds the budget at the worst cost-per-trip; search is capped',
  },
  'ins-rbc-17-booking-funnel': {
    kind: 'bar', xKey: 'product', series: ['booking', 'online'],
    yTitle: 'Conversion rate (index)',
    config: { booking: { label: 'Add-to-list / Voilà-cart journey', color: TEAL }, online: { label: 'Single-item journey', color: MUTED } },
    data: [
      { product: 'Meat & Seafood', booking: 205, online: 100 },
      { product: 'Centre-Store', booking: 224, online: 100 },
      { product: 'Floral & Seasonal', booking: 188, online: 100 },
    ],
    caption: 'Add-to-list / Voilà-cart journeys convert ~2x single-item on basket-building categories',
  },
};
