// ===========================================================================
// Tim Hortons — QSR / Restaurant client instance
// Representative campaign data + a full insight list + market news.
// App/offer-led QSR; "conversions" are Tims Rewards sign-ups and offer
// redemptions, revenue is low-AOV per redemption. Illustrative demo figures
// grounded in the real product lines, audiences, and agency roster.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, MUTED, GRID, PURPLE } from '../insight-visual-types';

export const TIM_HORTONS_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (Zulu Alpha Kilo) ──
  { id: 'th-hotbev-brand', name: 'Hot Beverages — It\'s Tims Time Brand Hero',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-hot-bev',
    audiences: ['th-daily-regulars', 'th-commuters'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'spotify'], geos: ['national'], budgetMultiplier: 1.60,
    plannedBudget: 12_800_000, revPerConvRange: [9, 26], cvrModifier: 1.00, cplCalibration: 0.60, revTrend: 0.0003 },
  { id: 'th-coldbev-summer', name: 'Cold Beverages — Summer Refresh Hero',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-cold-bev',
    audiences: ['th-cold-younger', 'th-families'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'tiktok', 'instagram', 'ooh'], geos: ['national', 'ontario'], budgetMultiplier: 1.35,
    plannedBudget: 9_200_000, revPerConvRange: [8, 24], cvrModifier: 1.05, cplCalibration: 0.60, revTrend: 0.0004 },
  { id: 'th-breakfast-value', name: 'Breakfast — Morning Value Routine',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-breakfast',
    audiences: ['th-commuters', 'th-value-seekers'], objective: 'consideration', status: 'live',
    channels: ['ctv', 'facebook', 'google-search', 'spotify'], geos: ['national'], budgetMultiplier: 1.15,
    plannedBudget: 6_900_000, revPerConvRange: [10, 28], cvrModifier: 1.10, cplCalibration: 0.62, revTrend: 0.0003 },

  // ── TIER 2 — REGIONAL / MEDIA (Touché!) ──
  { id: 'th-rewards-acquisition', name: 'Tims Rewards — App Sign-Up Acquisition',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-rewards',
    audiences: ['th-app-members', 'th-daily-regulars'], objective: 'conversion', status: 'live',
    channels: ['tiktok', 'instagram', 'google-search', 'facebook'], geos: ['national'], budgetMultiplier: 1.25,
    plannedBudget: 7_600_000, revPerConvRange: [12, 32], cvrModifier: 1.25, cplCalibration: 0.68, revTrend: 0.0005 },
  { id: 'th-coldbrew-younger', name: 'Cold Brew — Younger Daypart Push',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-cold-bev',
    audiences: ['th-cold-younger'], objective: 'consideration', status: 'live',
    channels: ['tiktok', 'instagram', 'spotify'], geos: ['ontario', 'quebec'], budgetMultiplier: 0.90,
    plannedBudget: 4_400_000, revPerConvRange: [9, 25], cvrModifier: 1.15, cplCalibration: 0.64, revTrend: 0.0005 },
  { id: 'th-lunch-daypart', name: 'Lunch — Afternoon Daypart Expansion',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-lunch',
    audiences: ['th-value-seekers', 'th-families'], objective: 'consideration', status: 'paused',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.80,
    plannedBudget: 3_600_000, revPerConvRange: [11, 30], cvrModifier: 1.00, cplCalibration: 0.60, revTrend: 0.0004 },

  // ── TIER 3 — LOCAL STORE MARKETING ──
  { id: 'th-baked-lto-local', name: 'Baked Goods — Local LTO & Donut Drops',
    enterprise: 'tim-hortons', division: 'tier-3', agency: 'th-local', productLine: 'th-baked',
    audiences: ['th-families', 'th-daily-regulars'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['ontario', 'atlantic'], budgetMultiplier: 0.70,
    plannedBudget: 2_900_000, revPerConvRange: [8, 22], cvrModifier: 1.10, cplCalibration: 0.66, revTrend: 0.0004 },
  { id: 'th-rewards-winback-local', name: 'Tims Rewards — Lapsed Visitor Win-Back',
    enterprise: 'tim-hortons', division: 'tier-3', agency: 'th-local', productLine: 'th-rewards',
    audiences: ['th-lapsed', 'th-value-seekers'], objective: 'retention', status: 'live',
    channels: ['facebook', 'google-search'], geos: ['national'], budgetMultiplier: 0.65,
    plannedBudget: 2_500_000, revPerConvRange: [10, 27], cvrModifier: 1.20, cplCalibration: 0.70, revTrend: 0.0005 },
];

export const TIM_HORTONS_NEWS: NewsItem[] = [
  { id: 'news-th-coldbrew-heatwave', title: 'Environment Canada Forecasts Hotter-Than-Average Summer — Cold-Beverage QSR Demand Expected to Surge',
    source: 'Environment Canada', date: '2026-05-07', tags: ['macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'Environment Canada\'s seasonal outlook points to a hotter-than-average summer across most of the country, a known driver of iced and cold-brew QSR demand.',
    whyItMatters: 'A weather tailwind landing as the Summer Refresh and Cold Brew flights ramp. STRATIS is correlating temperature against cold-beverage redemption to pace weight to the heat curve — see the linked recommendation.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-mcdonalds-coffee', title: "McDonald's Canada Relaunches McCafé Rewards with Aggressive Free-Coffee Ladder",
    source: 'Restaurants Canada', date: '2026-05-05', tags: ['competitors'], urgency: 'high', competitor: "McDonald's",
    regions: ['national'], summary: "McDonald's Canada relaunched McCafé Rewards with a faster free-drink ladder and a national app-install push targeting morning daypart regulars.",
    whyItMatters: 'A direct threat to morning-daypart loyalty and Tims Rewards acquisition. STRATIS detected rising "best coffee rewards app" comparison search — reported as correlation; see the recommended defense.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-app-loyalty-data', title: 'Loyalty-App Penetration in Canadian QSR Crosses 40% — Frequency Lift Concentrated in Top Quintile',
    source: 'Technomic', date: '2026-05-01', tags: ['macro', 'social'], urgency: 'high', regions: ['national'],
    summary: 'QSR loyalty-app penetration crossed 40% nationally, with the largest visit-frequency lift concentrated among the most engaged members.',
    whyItMatters: 'Confirms that app members drive disproportionate frequency. STRATIS flags the Rewards acquisition flight as the highest-leverage spend in the portfolio for compounding visit frequency.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-coffee-futures', title: 'Arabica Coffee Futures Ease from Multi-Year Highs as Brazil Harvest Firms',
    source: 'Bloomberg', date: '2026-04-28', tags: ['macro'], urgency: 'medium', regions: ['national'],
    summary: 'Arabica futures eased from multi-year highs on improved Brazilian harvest expectations, relieving input-cost pressure across coffee QSR.',
    whyItMatters: 'A modest margin tailwind that supports value-led messaging in the breakfast routine. Tracked at the brand level; no reallocation required yet.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-nhl-sponsorship', title: 'Tim Hortons Renews Grassroots Hockey Programming Ahead of Playoff Co-Viewing Peak',
    source: 'Marketing Magazine', date: '2026-04-23', tags: ['sports', 'sponsorships', 'partnerships'], urgency: 'medium', regions: ['national'],
    summary: 'Tim Hortons renewed its grassroots hockey programming heading into the national playoff co-viewing window, reinforcing a core brand-equity asset.',
    whyItMatters: 'A brand-equity moment adjacent to the Hot Beverages hero. STRATIS is correlating sponsorship salience against branded search; no media reallocation required.',
    enterprises: ['tim-hortons'] },
];

export const TIM_HORTONS_RADAR_PINS = ['news-th-coldbrew-heatwave', 'news-th-mcdonalds-coffee', 'news-th-app-loyalty-data'];

export const TIM_HORTONS_INSIGHTS: Insight[] = [
  {
    id: 'ins-th-01-rewards-leverage', createdAt: todayISO,
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'brand',
    channels: ['tiktok', 'instagram', 'google-search', 'facebook'],
    title: 'App Members Drive Disproportionate Visit Frequency — yet Rewards Acquisition Gets Less Weight Than Any Single Product Hero',
    summary: 'Loyalty data now confirms app members visit far more often than non-members, and the lift compounds with engagement. But across the live portfolio, Rewards acquisition receives less weight than any single product hero, so the highest-leverage spend in the business is under-funded relative to its downstream value. STRATIS holds per-member frequency value against acquisition spend and finds the Rewards flight materially under-invested. Re-weighting toward Rewards acquisition buys compounding frequency, not a one-time impression.',
    evidence: [
      'App members visit materially more often than non-members; lift compounds with engagement',
      'Rewards acquisition receives less weight than any single product hero',
      'Per-member downstream value exceeds product-hero impression value',
      'The highest-leverage spend in the portfolio is the most under-funded',
    ],
    confidence: 0.86,
    impactEstimate: 'Re-weighting toward Rewards acquisition converts one-time impressions into compounding visit frequency across the member base.',
    recommendedAction: 'Increase Rewards acquisition weight, funded from over-delivered product-hero impressions, to back the highest-leverage spend.',
    status: 'new',
    linkedNewsId: 'news-th-app-loyalty-data',
    actionSteps: [
      { id: 's1', title: 'Increase Rewards acquisition weight', subtitle: 'HIGHEST-LEVERAGE SPEND', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered product heroes', subtitle: 'NO NET BUDGET ADD', type: 'budget', completed: false },
      { id: 's3', title: 'Track member frequency vs spend', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-02-mccafe-defense', createdAt: at(1, '08:30:00'),
    enterprise: 'tim-hortons', category: 'competitive-macro', scope: 'product', productLine: 'th-rewards',
    channels: ['google-search', 'tiktok', 'facebook'],
    title: "McCafé's Rewards Relaunch Is Lifting 'Best Coffee Rewards App' Search — Defend the Morning Daypart Before Members Switch",
    summary: "After McDonald's relaunched McCafé Rewards with a faster free-drink ladder, 'best coffee rewards app' and 'McCafé vs Tims' comparison search rose, concentrated in the morning daypart where loyalty is most contested. Tims Rewards is not currently surfaced in that comparison moment, and the acquisition offer does not lead with the free-drink ladder. A focused search defense and a matched ladder-forward message holds the morning regular before the switch hardens into habit.",
    evidence: [
      "'Best coffee rewards app' and 'McCafé vs Tims' search rising since the relaunch",
      'Lift concentrated in the contested morning daypart',
      'Tims Rewards is absent from the comparison moment',
      'Acquisition offer does not lead with the free-drink ladder',
    ],
    confidence: 0.83,
    impactEstimate: 'Defending comparison search and matching the ladder message holds morning-daypart members before switching becomes habit.',
    recommendedAction: 'Expand defensive search on coffee-rewards comparison terms and lead Rewards acquisition with a ladder-forward offer.',
    status: 'new',
    linkedNewsId: 'news-th-mcdonalds-coffee',
    actionSteps: [
      { id: 's1', title: 'Defend coffee-rewards comparison search', subtitle: 'MORNING DAYPART', type: 'bidding', completed: false },
      { id: 's2', title: 'Lead acquisition with the ladder offer', subtitle: 'MATCH THE COMPETITIVE HOOK', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-03-heat-pacing', createdAt: at(2, '10:45:00'),
    enterprise: 'tim-hortons', category: 'national-regional', scope: 'product', productLine: 'th-cold-bev',
    channels: ['ctv', 'tiktok', 'instagram'],
    title: 'Cold-Beverage Redemption Tracks Temperature — Pace the Summer Flights to the Heat Curve, Not the Calendar',
    summary: 'Cold-beverage redemption correlates tightly with daily high temperature, and Environment Canada\'s outlook points to an early, hotter-than-average summer concentrated first in Ontario and Quebec. The Summer Refresh and Cold Brew flights currently pace evenly on a calendar plan. Shifting to temperature-responsive pacing — front-loading the markets heating first — captures demand at its peak instead of after it, at the same total budget.',
    evidence: [
      'Cold-beverage redemption correlates with daily high temperature',
      'Hotter-than-average summer forecast, arriving earliest in ON & QC',
      'Summer flights pace evenly on a calendar plan',
      'Temperature-responsive pacing captures peak demand windows',
    ],
    confidence: 0.81,
    impactEstimate: 'Pacing to the heat curve captures cold-beverage demand at its peak rather than after it, at no added budget.',
    recommendedAction: 'Switch the summer cold-beverage flights to temperature-responsive pacing, front-loading the markets heating first.',
    status: 'new',
    linkedNewsId: 'news-th-coldbrew-heatwave',
    actionSteps: [
      { id: 's1', title: 'Adopt temperature-responsive pacing', subtitle: 'HEAT CURVE, NOT CALENDAR', type: 'scheduling', completed: false },
      { id: 's2', title: 'Front-load the earliest-heating markets', subtitle: 'ON + QC FIRST', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-04-daypart-overlap', createdAt: at(4, '13:30:00'),
    enterprise: 'tim-hortons', category: 'audience-overlap', scope: 'brand',
    channels: ['ctv', 'facebook', 'spotify'],
    title: 'Breakfast and Hot Beverages Are Buying the Same Commuter in the Same Morning Window — Combined Frequency Is Past Useful',
    summary: 'The Breakfast value flight and the Hot Beverages hero both target morning commuters in overlapping CTV and audio windows, with no shared cap. Deduped, the morning commuter sees both messages well past the point where the second one adds anything. Because they share an audience and a daypart, a single coordinated morning message — or an enforced split where one owns awareness and the other owns the value offer — recovers wasted frequency and reads as one coherent morning story.',
    evidence: [
      'Breakfast and Hot Beverages overlap on morning commuters',
      'Shared CTV and audio windows, no coordinated cap',
      'Combined morning frequency is past the useful point',
      'No role split between awareness and value offer',
    ],
    confidence: 0.78,
    impactEstimate: 'Coordinating the morning message recovers wasted frequency and presents one coherent commuter story.',
    recommendedAction: 'Cap combined morning-daypart frequency across the two flights and enforce an awareness-vs-offer role split.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap combined morning frequency', subtitle: 'BREAKFAST + HOT BEV', type: 'bidding', completed: false },
      { id: 's2', title: 'Split roles: awareness vs value offer', subtitle: 'ONE MORNING STORY', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-05-creative-fatigue', createdAt: at(6, '09:15:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-cold-bev',
    channels: ['tiktok', 'instagram'],
    title: 'The Summer Refresh Cold-Brew Cut Is Wearing Out on TikTok Before Peak Season Even Starts',
    summary: 'The Cold Brew younger-daypart cut\'s completion and save rates on TikTok have slipped for two weeks while delivery climbed — early fatigue ahead of the hottest, highest-demand weeks. Burning the hero creative before peak season risks entering the demand surge with a tired asset. Rotating fresh short-form now, and reserving a creative refresh for the forecasted heat peak, keeps the asset effective exactly when redemption demand is highest.',
    evidence: [
      'TikTok completion and save rates down two consecutive weeks',
      'Delivery rose over the same window',
      'Fatigue is arriving before peak demand weeks',
      'Risk of entering the heat surge with a worn asset',
    ],
    confidence: 0.80,
    impactEstimate: 'Rotating fresh creative now preserves asset effectiveness into the peak-demand heat window.',
    recommendedAction: 'Rotate fresh Cold Brew short-form on TikTok now and hold a refresh for the forecasted heat peak.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Rotate fresh short-form now', subtitle: 'TIKTOK COLD BREW', type: 'creative', completed: false },
      { id: 's2', title: 'Reserve a refresh for the heat peak', subtitle: 'PROTECT PEAK DEMAND', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-06-agency-arbitrage', createdAt: at(9, '11:45:00'),
    enterprise: 'tim-hortons', category: 'agency-arbitrage', scope: 'brand',
    channels: ['facebook', 'google-search', 'instagram'],
    title: 'Local Store Marketing Wins Lapsed Visitors Back Cheaper Than the National Flight — the Local Offer Should Cascade Up',
    summary: 'The Tier 3 Local Store Marketing team recovers lapsed Tims Rewards visitors at a lower cost-per-reactivation than national retention, because the offer is tied to a specific nearby restaurant and a relevant daypart. National Win-Back uses a generic offer. Cascading the local geo-and-daypart offer mechanic into the national retention flight scales a proven reactivation efficiency rather than confining it to local activation.',
    evidence: [
      'Local Store Marketing cost-per-reactivation is below national retention',
      'Advantage traces to a nearby-restaurant, daypart-relevant offer',
      'National Win-Back uses a generic offer',
      'The local mechanic is replicable nationally with geo targeting',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the local geo-and-daypart offer into the national flight lowers blended cost-per-reactivation.',
    recommendedAction: 'Adopt the Local Store Marketing geo-and-daypart offer mechanic in the national Win-Back flight.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the local offer mechanic', subtitle: 'GEO + DAYPART TIED', type: 'targeting', completed: false },
      { id: 's2', title: 'Cascade into national Win-Back', subtitle: 'REPLACE GENERIC OFFER', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-07-coldbev-channel', createdAt: at(3, '10:25:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-cold-bev',
    channels: ['ctv', 'tiktok', 'spotify', 'instagram'],
    title: 'Cold-Beverage Cost-per-Completed-View Is Lowest on TikTok yet Most Weight Sits in CTV',
    summary: "TikTok delivers a completed cold-beverage view at roughly half CTV's cost, but CTV holds the majority of the cold-bev video budget. A partial shift of completion-objective weight from CTV into TikTok buys more efficient views into the younger cold-bev audience — without giving up CTV's broad reach role on the hero.",
    evidence: [
      "TikTok cost-per-completed-view is ~half of CTV's",
      'CTV holds the majority of cold-bev video weight',
      'The younger cold-bev audience over-indexes on TikTok',
      "A partial shift preserves CTV's reach role",
    ],
    confidence: 0.75,
    impactEstimate: 'Shifting completion-objective weight to TikTok buys more efficient completed views at the same budget.',
    recommendedAction: "Move a portion of cold-bev completion weight from CTV to TikTok while holding CTV's reach role.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift completion weight CTV → TikTok', subtitle: 'CHEAPER COMPLETED VIEWS', type: 'budget', completed: false },
      { id: 's2', title: 'Hold CTV reach on the hero', subtitle: 'PARTIAL SHIFT ONLY', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-08-rewards-value', createdAt: at(8, '11:35:00'),
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'product', productLine: 'th-rewards',
    channels: ['tiktok', 'instagram', 'facebook', 'google-search'],
    title: 'Tims Rewards Members Carry ~3× the Visit Value of Non-Members but Acquisition Gets a Fraction of the Weight',
    summary: 'Rewards members visit more often and spend more per visit — roughly three times the visit value of non-members — yet Rewards acquisition receives a small share of portfolio weight next to the product heroes. Funding acquisition from over-delivered hero impressions compounds the member base that drives the most downstream value, rather than buying one-time reach.',
    evidence: [
      'Members carry ~3× the visit value of non-members',
      'Rewards acquisition gets a fraction of portfolio weight',
      'Member value compounds with visit frequency',
      'Hero impressions are over-delivered at current weight',
    ],
    confidence: 0.85,
    impactEstimate: 'Funding member acquisition from over-delivered hero weight compounds the highest-value cohort in the base.',
    recommendedAction: 'Shift a measured share of over-delivered hero impressions into Rewards member acquisition.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Increase Rewards acquisition weight', subtitle: 'COMPOUNDS MEMBER VALUE', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered heroes', subtitle: 'NO NET BUDGET ADD', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-09-lunch-incrementality', createdAt: at(2, '09:50:00'),
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'product', productLine: 'th-lunch',
    channels: ['facebook', 'instagram', 'google-search'],
    title: 'The Paused Lunch Daypart Was Driving Incremental Visits, Not Cannibalizing Coffee — Restarting It Is the Cleanest Growth Lever in the Portfolio',
    summary: 'The Lunch afternoon-daypart flight was paused on the assumption it pulled from the morning coffee routine, but redemption-time data shows its conversions clustered in the 11am–2pm window where Tims runs nearly empty media. Across the portfolio, no other flight owns that window, so the lunch visit is additive rather than a shifted coffee trip. STRATIS sees this because it reads conversion timing against every other flight\'s delivery, not lunch in isolation. Restarting Lunch at a measured weight buys incremental afternoon visits the rest of the portfolio cannot reach.',
    evidence: [
      'Paused on a cannibalization assumption never tested against timing data',
      'Lunch conversions cluster in the 11am–2pm media-light window',
      'No other live flight owns the afternoon daypart',
      'Conversion timing shows additive visits, not shifted coffee trips',
    ],
    confidence: 0.82,
    impactEstimate: 'Restarting Lunch at measured weight captures incremental afternoon visits no other flight reaches.',
    recommendedAction: 'Restart the Lunch daypart flight at a measured weight and hold it to the empty 11am–2pm window.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Restart Lunch at measured weight', subtitle: 'INCREMENTAL, NOT CANNIBAL', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate delivery 11am–2pm', subtitle: 'OWN THE EMPTY WINDOW', type: 'scheduling', completed: false },
      { id: 's3', title: 'Hold incrementality readout', subtitle: 'STRATIS MONITORS TIMING', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-10-quebec-fit', createdAt: at(5, '10:10:00'),
    enterprise: 'tim-hortons', category: 'national-regional', scope: 'brand',
    channels: ['ctv', 'facebook', 'instagram'],
    title: 'The National Hero Creative Underperforms in Quebec — a French-First Cut Beats the Dubbed National Asset on Every Engagement Metric',
    summary: 'The national Hot Beverages and Summer Refresh heroes run in Quebec as dubbed versions of the English master, and they trail their national average on completion, save, and offer click. The local-market cut built French-first — not translated — outperforms the dubbed asset across the board in Quebec delivery. STRATIS surfaces this because it compares Quebec performance against the same creative\'s national baseline rather than judging Quebec in isolation. Routing Quebec weight to a French-first cut recovers engagement the dubbed asset leaves on the table.',
    evidence: [
      'Dubbed national heroes trail national average on completion in Quebec',
      'French-first local cut outperforms the dubbed asset on save and click',
      'Gap is consistent across Hot Bev and Summer Refresh delivery',
      'Visible only when Quebec is held against the asset\'s national baseline',
    ],
    confidence: 0.79,
    impactEstimate: 'Routing Quebec to a French-first cut recovers engagement the dubbed asset forfeits.',
    recommendedAction: 'Replace dubbed hero delivery in Quebec with a French-first creative cut.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Promote the French-first cut in QC', subtitle: 'NOT A DUBBED MASTER', type: 'creative', completed: false },
      { id: 's2', title: 'Route Quebec weight to the local cut', subtitle: 'QC DELIVERY ONLY', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-11-family-bundle-crossshop', createdAt: at(3, '08:20:00'),
    enterprise: 'tim-hortons', category: 'audience-overlap', scope: 'brand',
    channels: ['facebook', 'instagram', 'ooh'],
    title: 'Families Buying Baked Goods Cross-Shop Lunch at High Rates — yet the Two Flights Target Them in Isolation With No Bundle Hand-Off',
    summary: 'The Baked Goods local flight and the paused Lunch flight both reach Families, and redemption data shows a family who redeems a baked-goods offer cross-shops Lunch at a far higher rate than the base. But the two flights target Families independently, with no bundle message or sequencing between them. STRATIS sees the cross-shop because it joins redemption across product lines for the same household, a link single-flight planning never makes. Sequencing a baked-goods-to-lunch family bundle turns two isolated offers into one higher-value basket.',
    evidence: [
      'Baked-goods family redeemers cross-shop Lunch above the base rate',
      'Baked Goods and Lunch both target Families independently',
      'No bundle message or offer sequencing between the flights',
      'Cross-shop visible only by joining redemption per household',
    ],
    confidence: 0.77,
    impactEstimate: 'Sequencing a family bundle turns two isolated offers into one higher-value basket.',
    recommendedAction: 'Sequence a baked-goods-to-lunch family bundle across the two flights that share the Families audience.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Sequence baked-goods → lunch offer', subtitle: 'FAMILY BUNDLE', type: 'creative', completed: false },
      { id: 's2', title: 'Share the Families audience across flights', subtitle: 'ONE HOUSEHOLD VIEW', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-12-spotify-commute', createdAt: at(7, '08:55:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-breakfast',
    channels: ['spotify', 'ctv', 'facebook'],
    title: 'Spotify Morning-Commute Audio Drives Breakfast Offer Clicks at a Fraction of CTV Cost — but Holds the Smallest Slice of the Flight',
    summary: 'On the Breakfast value flight, Spotify audio in the 6am–9am commute window delivers offer clicks at roughly a third of CTV\'s cost-per-click, because the message lands exactly when the morning routine decision is made. Yet Spotify holds the smallest share of the flight\'s weight while CTV carries the most. A measured shift of lower-funnel weight from CTV into morning-commute audio buys more offer engagement at the same budget, while CTV keeps its broad awareness role.',
    evidence: [
      'Spotify commute-window cost-per-offer-click ~⅓ of CTV',
      'Audio lands at the moment the morning routine is decided',
      'Spotify holds the smallest weight share; CTV the largest',
      'A measured shift preserves CTV awareness reach',
    ],
    confidence: 0.76,
    impactEstimate: 'Shifting lower-funnel weight to commute audio buys more offer engagement at the same budget.',
    recommendedAction: 'Move a portion of Breakfast lower-funnel weight from CTV into Spotify morning-commute audio.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift offer weight CTV → Spotify', subtitle: 'CHEAPER OFFER CLICKS', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate audio in the 6–9am commute', subtitle: 'DECISION MOMENT', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-13-baked-lto-spikes', createdAt: at(6, '12:40:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-baked',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'Donut-Drop LTOs Spike Demand for ~72 Hours Then Decay — yet Baked-Goods Weight Paces Flat Across the Whole Window',
    summary: 'Local LTO and donut-drop redemption spikes hard in the first three days of each drop and decays sharply after, but the Baked Goods flight spends flat across the entire LTO window. The back half of every drop buys impressions into demand that has already passed. STRATIS sees the decay curve because it reads redemption velocity per drop, not aggregate LTO spend. Front-weighting each drop into its first 72 hours and trimming the tail concentrates spend where the spike actually is.',
    evidence: [
      'Donut-drop redemption spikes in the first ~72 hours then decays',
      'Baked Goods weight paces flat across the full LTO window',
      'Back-half spend buys impressions into demand already passed',
      'Decay curve visible only at per-drop redemption velocity',
    ],
    confidence: 0.77,
    impactEstimate: 'Front-weighting each drop into its first 72 hours concentrates spend on the actual demand spike.',
    recommendedAction: 'Front-load baked-goods LTO weight into the first 72 hours of each drop and trim the decayed tail.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load drops into 72-hour spike', subtitle: 'MATCH THE DECAY CURVE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Trim the decayed tail spend', subtitle: 'DEMAND HAS PASSED', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-14-drive-thru-ooh', createdAt: at(10, '14:05:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ooh', 'instagram', 'facebook'],
    title: 'OOH Near Drive-Thru Routes Converts Far Above Generic Boards — Proximity-Targeted Inventory Is Buried in a Flat National Buy',
    summary: 'OOH placements within a short drive of Tims locations on commuter routes drive redemption at a multiple of generic high-reach boards, but the national OOH buy treats all inventory as interchangeable reach. The proximity signal — board to nearby drive-thru — is what converts, and it is currently diluted across placements with no nearby restaurant. STRATIS reads board-level redemption against location proximity, a join single-channel planning never makes. Re-weighting the buy toward proximity inventory lifts conversion at the same OOH spend.',
    evidence: [
      'Proximity boards convert at a multiple of generic high-reach boards',
      'National buy treats all OOH inventory as interchangeable reach',
      'Converting signal is board-to-nearby-drive-thru proximity',
      'Board redemption joined to location proximity only at portfolio level',
    ],
    confidence: 0.74,
    impactEstimate: 'Re-weighting OOH toward proximity inventory lifts conversion at the same total OOH spend.',
    recommendedAction: 'Re-weight the OOH buy toward inventory within drive-thru proximity on commuter routes.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Prioritize drive-thru-proximity boards', subtitle: 'PROXIMITY IS THE SIGNAL', type: 'targeting', completed: false },
      { id: 's2', title: 'Trim generic non-proximity inventory', subtitle: 'SAME OOH BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-15-offer-ladder-wear', createdAt: at(11, '11:20:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-rewards',
    channels: ['tiktok', 'instagram', 'facebook'],
    title: 'The Rewards Offer-Ladder Creative Has Hit Frequency Saturation — Redemption per Impression Is Falling While Reach Plateaus',
    summary: 'The Tims Rewards acquisition flight runs a single offer-ladder creative that has now saturated its core audience: redemption per impression is sliding while incremental reach flattens, the signature of frequency wear with no fresh audience left to find. The flight keeps spending against the same saturated pool. STRATIS sees saturation because it tracks redemption-per-impression against reach curve, not raw redemptions. Refreshing the ladder creative and expanding into adjacent lookalikes restores efficiency the saturated buy is bleeding.',
    evidence: [
      'Redemption per impression falling as incremental reach flattens',
      'Single offer-ladder creative against a saturated core audience',
      'Classic frequency-wear signature, not a seasonal dip',
      'Visible only as redemption-per-impression vs the reach curve',
    ],
    confidence: 0.78,
    impactEstimate: 'Refreshing the ladder creative and expanding lookalikes restores efficiency the saturated buy is losing.',
    recommendedAction: 'Refresh the offer-ladder creative and expand the Rewards acquisition pool into adjacent lookalikes.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Refresh the offer-ladder creative', subtitle: 'FREQUENCY SATURATED', type: 'creative', completed: false },
      { id: 's2', title: 'Expand into adjacent lookalikes', subtitle: 'FRESH AUDIENCE', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-16-nhl-branded-search', createdAt: at(13, '09:35:00'),
    enterprise: 'tim-hortons', category: 'competitive-macro', scope: 'brand',
    channels: ['google-search', 'ctv', 'spotify'],
    title: 'Playoff Co-Viewing Is Lifting Branded Tims Search — but Search Capture Is Under-Funded for the Sponsorship-Driven Demand',
    summary: 'Branded "Tim Hortons near me" and menu search rises during playoff co-viewing windows, tracking the grassroots-hockey sponsorship salience rather than any media flight. The branded-search line is currently funded for baseline demand, so it under-captures the sponsorship-driven spikes and cedes the click to aggregators. STRATIS correlates sponsorship salience to branded search across the portfolio, a link the social/sponsorship teams and search buyers do not share. Pulsing branded-search capacity to the co-viewing schedule converts brand equity into measured visits.',
    evidence: [
      'Branded Tims search rises in playoff co-viewing windows',
      'Spikes track sponsorship salience, not any paid flight',
      'Branded search funded for baseline, under-captures the spikes',
      'Sponsorship-to-search correlation lives only at portfolio level',
    ],
    confidence: 0.75,
    impactEstimate: 'Pulsing branded-search capacity to the co-viewing schedule converts equity spikes into captured visits.',
    recommendedAction: 'Pulse branded-search budget to the playoff co-viewing schedule to capture sponsorship-driven demand.',
    status: 'new',
    linkedNewsId: 'news-th-nhl-sponsorship',
    actionSteps: [
      { id: 's1', title: 'Pulse branded search to co-viewing nights', subtitle: 'CAPTURE THE SPIKE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Lift caps on branded terms', subtitle: 'DON\'T CEDE THE CLICK', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-th-17-coldbrew-younger-growth', createdAt: at(14, '10:30:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-cold-bev',
    channels: ['tiktok', 'instagram', 'spotify'],
    title: 'Cold Brew Is Growing the Afternoon Daypart Among Younger Members While Hot Bev Stays Flat — the Creative Should Lean Into the New Occasion',
    summary: 'Cold Brew redemption among younger members is growing fastest in the afternoon daypart, an occasion Hot Beverages has never owned, while hot-bev frequency in the same cohort stays flat. The current Cold Brew creative still frames the drink as a morning-coffee alternative, missing the afternoon occasion that is actually driving its growth. STRATIS sees the emerging daypart because it reads cold-bev redemption timing against hot-bev in the same members. Re-cutting the creative around the afternoon occasion compounds the daypart the portfolio is newly winning.',
    evidence: [
      'Cold Brew growth among younger members concentrates in the afternoon',
      'Hot-bev frequency in the same cohort stays flat',
      'Current creative frames Cold Brew as a morning-coffee swap',
      'New afternoon occasion visible only against hot-bev timing',
    ],
    confidence: 0.79,
    impactEstimate: 'Re-cutting creative around the afternoon occasion compounds the daypart the portfolio is newly winning.',
    recommendedAction: 'Re-cut the Cold Brew creative around the afternoon occasion driving younger-member growth.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Re-cut creative for the afternoon occasion', subtitle: 'NOT A MORNING SWAP', type: 'creative', completed: false },
      { id: 's2', title: 'Weight delivery to the afternoon daypart', subtitle: 'YOUNGER MEMBERS', type: 'scheduling', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const TIM_HORTONS_VISUALS: Record<string, InsightVisual> = {
  'ins-th-01-rewards-leverage': {
    kind: 'bar', xKey: 'line', series: ['weight'], perBarColor: true,
    yTitle: 'Share of media weight (%)',
    config: { weight: { label: 'Media weight share' } },
    data: [
      { line: 'Hot Bev', weight: 26, fill: MUTED },
      { line: 'Cold Bev', weight: 20, fill: MUTED },
      { line: 'Breakfast', weight: 16, fill: MUTED },
      { line: 'Tims Rewards', weight: 12, fill: RED },
    ],
    caption: 'Rewards drives the most downstream frequency yet gets the least weight',
  },
  'ins-th-02-mccafe-defense': {
    kind: 'line', xKey: 'week', series: ['search'],
    yTitle: "'Best coffee rewards app' search",
    config: { search: { label: 'Comparison search', color: RED } },
    data: [
      { week: 'W1', search: 100 }, { week: 'W2', search: 103 }, { week: 'W3', search: 107 },
      { week: 'W4', search: 129 }, { week: 'W5', search: 138 }, { week: 'W6', search: 134 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'McCafé relaunch', color: GRID }],
    caption: 'Comparison search jumps after the McCafé relaunch — defend the morning',
  },
  'ins-th-03-heat-pacing': {
    kind: 'scatter', xKey: 'temp', series: ['redemption'],
    xName: 'Daily high (°C)', yName: 'Cold-bev redemptions (index)', perBarColor: true,
    config: { redemption: { label: 'Cold-bev redemptions' } },
    legend: [{ label: 'Daily observation', color: TEAL }],
    data: [
      { temp: 9, redemption: 72, fill: MUTED, name: 'Day' },
      { temp: 14, redemption: 88, fill: MUTED, name: 'Day' },
      { temp: 18, redemption: 104, fill: TEAL, name: 'Day' },
      { temp: 23, redemption: 126, fill: TEAL, name: 'Day' },
      { temp: 27, redemption: 145, fill: TEAL, name: 'Day' },
      { temp: 31, redemption: 168, fill: TEAL, name: 'Day' },
    ],
    caption: 'Each dot is a day — cold-bev redemption tracks the daily high',
  },
  'ins-th-04-daypart-overlap': {
    kind: 'bar', xKey: 'flight', series: ['freq'], perBarColor: true,
    yTitle: 'Morning frequency (commuter)',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { flight: 'Breakfast', freq: 10, fill: MUTED },
      { flight: 'Hot Bev', freq: 9, fill: MUTED },
      { flight: 'Combined', freq: 19, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 11, label: 'Effective max', color: TEAL }],
    caption: 'Two flights hit the same commuter — combined morning frequency 19×',
  },
  'ins-th-05-creative-fatigue': {
    kind: 'line', xKey: 'week', series: ['save', 'spend'],
    yTitle: 'Indexed to 100',
    config: { save: { label: 'TikTok save rate', color: RED }, spend: { label: 'Spend', color: BLUE } },
    data: [
      { week: 'W1', save: 100, spend: 100 }, { week: 'W2', save: 97, spend: 106 },
      { week: 'W3', save: 92, spend: 111 }, { week: 'W4', save: 88, spend: 117 },
    ],
    caption: 'Save rate falls as spend climbs — wearing out before peak heat',
  },
  'ins-th-06-agency-arbitrage': {
    kind: 'bar', xKey: 'team', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per reactivation ($)',
    config: { cost: { label: 'Cost per reactivation' } },
    data: [
      { team: 'Local Store Mktg', cost: 6.4, fill: TEAL },
      { team: 'National Win-Back', cost: 9.8, fill: RED },
    ],
    caption: 'Local reactivation beats national — the geo-daypart offer should scale',
  },
  'ins-th-07-coldbev-channel': {
    kind: 'bar', xKey: 'channel', series: ['cpv'], perBarColor: true,
    yTitle: 'Cost per completed view (¢)',
    config: { cpv: { label: 'Cost per completed view' } },
    data: [
      { channel: 'CTV', cpv: 4.8, fill: RED },
      { channel: 'Spotify', cpv: 3.6, fill: MUTED },
      { channel: 'Instagram', cpv: 3.1, fill: MUTED },
      { channel: 'TikTok', cpv: 2.4, fill: TEAL },
    ],
    caption: 'TikTok delivers the cheapest completed view — most weight sits in CTV',
  },
  'ins-th-08-rewards-value': {
    kind: 'bar', xKey: 'metric', series: ['member', 'nonmember'],
    yTitle: 'Indexed to non-member',
    config: { member: { label: 'Rewards member', color: TEAL }, nonmember: { label: 'Non-member', color: MUTED } },
    data: [
      { metric: 'Visit value', member: 312, nonmember: 100 },
      { metric: 'Acquisition weight', member: 12, nonmember: 88 },
    ],
    caption: 'Members carry ~3× visit value but a fraction of acquisition weight',
  },
  'ins-th-09-lunch-incrementality': {
    kind: 'bar', xKey: 'window', series: ['visits'], perBarColor: true,
    yTitle: 'Lunch conversions (index)',
    config: { visits: { label: 'Conversions by hour' } },
    data: [
      { window: '8–11am', visits: 14, fill: MUTED },
      { window: '11am–2pm', visits: 71, fill: TEAL },
      { window: '2–5pm', visits: 22, fill: MUTED },
      { window: '5–8pm', visits: 9, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 30, label: 'Other-flight coverage', color: RED }],
    caption: 'Lunch conversions cluster in the empty 11am–2pm window',
  },
  'ins-th-10-quebec-fit': {
    kind: 'bar', xKey: 'metric', series: ['dubbed', 'french'],
    yTitle: 'Indexed to national average',
    config: { dubbed: { label: 'Dubbed national', color: MUTED }, french: { label: 'French-first cut', color: TEAL } },
    data: [
      { metric: 'Completion', dubbed: 86, french: 108 },
      { metric: 'Save rate', dubbed: 81, french: 114 },
      { metric: 'Offer click', dubbed: 78, french: 119 },
    ],
    caption: 'French-first cut beats the dubbed master across QC engagement',
  },
  'ins-th-11-family-bundle-crossshop': {
    kind: 'bar', xKey: 'group', series: ['lunch'], perBarColor: true,
    yTitle: 'Lunch cross-shop rate (%)',
    config: { lunch: { label: 'Cross-shops Lunch' } },
    data: [
      { group: 'Baked-goods family redeemers', lunch: 41, fill: TEAL },
      { group: 'All families', lunch: 23, fill: MUTED },
      { group: 'Non-family base', lunch: 14, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 23, label: 'Base family rate', color: RED }],
    caption: 'Baked-goods family redeemers cross-shop Lunch far above the base',
  },
  'ins-th-12-spotify-commute': {
    kind: 'bar', xKey: 'channel', series: ['cpc'], perBarColor: true,
    yTitle: 'Cost per offer click ($)',
    config: { cpc: { label: 'Cost per offer click' } },
    data: [
      { channel: 'CTV', cpc: 2.7, fill: RED },
      { channel: 'Facebook', cpc: 1.5, fill: MUTED },
      { channel: 'Spotify (6–9am)', cpc: 0.9, fill: TEAL },
    ],
    caption: 'Commute audio drives the cheapest breakfast offer click',
  },
  'ins-th-13-baked-lto-spikes': {
    kind: 'line', xKey: 'day', series: ['redemption', 'spend'],
    yTitle: 'Indexed to drop launch',
    config: { redemption: { label: 'Redemption velocity', color: TEAL }, spend: { label: 'Flat spend pacing', color: RED } },
    data: [
      { day: 'D1', redemption: 100, spend: 100 }, { day: 'D2', redemption: 92, spend: 100 },
      { day: 'D3', redemption: 74, spend: 100 }, { day: 'D4', redemption: 41, spend: 100 },
      { day: 'D5', redemption: 28, spend: 100 }, { day: 'D6', redemption: 19, spend: 100 },
    ],
    refLines: [{ axis: 'x', value: 'D3', label: '72-hour spike', color: GRID }],
    caption: 'Demand decays after 72 hours while baked-goods spend stays flat',
  },
  'ins-th-14-drive-thru-ooh': {
    kind: 'bar', xKey: 'inventory', series: ['conv'], perBarColor: true,
    yTitle: 'Redemption per board (index)',
    config: { conv: { label: 'Redemption per board' } },
    data: [
      { inventory: 'Drive-thru proximity', conv: 184, fill: TEAL },
      { inventory: 'Commuter route', conv: 121, fill: BLUE },
      { inventory: 'Generic high-reach', conv: 100, fill: MUTED },
    ],
    caption: 'Proximity boards convert far above generic high-reach inventory',
  },
  'ins-th-15-offer-ladder-wear': {
    kind: 'line', xKey: 'week', series: ['rpi', 'reach'],
    yTitle: 'Indexed to 100',
    config: { rpi: { label: 'Redemption / impression', color: RED }, reach: { label: 'Incremental reach', color: BLUE } },
    data: [
      { week: 'W1', rpi: 100, reach: 100 }, { week: 'W2', rpi: 96, reach: 112 },
      { week: 'W3', rpi: 89, reach: 119 }, { week: 'W4', rpi: 81, reach: 122 },
      { week: 'W5', rpi: 73, reach: 123 },
    ],
    caption: 'Redemption per impression falls as reach plateaus — frequency wear',
  },
  'ins-th-16-nhl-branded-search': {
    kind: 'line', xKey: 'night', series: ['search', 'capture'],
    yTitle: 'Branded search (index)',
    config: { search: { label: 'Branded search demand', color: PURPLE }, capture: { label: 'Funded capture', color: MUTED } },
    data: [
      { night: 'Reg 1', search: 100, capture: 98 }, { night: 'Reg 2', search: 108, capture: 101 },
      { night: 'Playoff 1', search: 152, capture: 104 }, { night: 'Playoff 2', search: 171, capture: 106 },
      { night: 'Playoff 3', search: 164, capture: 103 },
    ],
    refLines: [{ axis: 'x', value: 'Playoff 1', label: 'Co-viewing peak', color: GRID }],
    caption: 'Playoff nights spike branded search past funded capture',
  },
  'ins-th-17-coldbrew-younger-growth': {
    kind: 'pie', nameKey: 'daypart', valueKey: 'growth', series: ['growth'],
    config: { growth: { label: 'Cold Brew growth share' } },
    legend: [
      { label: 'Afternoon', color: TEAL },
      { label: 'Morning', color: MUTED },
      { label: 'Evening', color: BLUE },
    ],
    data: [
      { daypart: 'Afternoon', growth: 58, fill: TEAL },
      { daypart: 'Morning', growth: 27, fill: MUTED },
      { daypart: 'Evening', growth: 15, fill: BLUE },
    ],
    caption: 'Younger-member Cold Brew growth concentrates in the afternoon',
  },
};
