// ===========================================================================
// Foodland — community / rural grocery banner (Empire / Sobeys family)
// Representative campaign data + a full insight list + market news.
// Smaller-format, franchised stores across rural Ontario + Atlantic, anchored
// on local & Ontario-grown sourcing, community trust, convenience, and Scene+.
// "conversions" are transactions / baskets, revenue is attributed sales, and
// the headline KPI is ROAS. Illustrative demo figures grounded in the real
// categories, shopper segments, and agency roster.
// ===========================================================================
import type { Insight, NewsItem } from '@/types';
import { type CampaignDef, at, todayISO } from './_shared';
import { type InsightVisual, TEAL, RED, BLUE, MUTED, GRID, PURPLE } from '../insight-visual-types';

export const TIM_HORTONS_CAMPAIGN_DEFS: CampaignDef[] = [
  // ── TIER 1 — NATIONAL BRAND (Foodland Creative) ──
  { id: 'th-hotbev-brand', name: 'Fresh & Produce — Real Food, Real Communities Brand Hero',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-hot-bev',
    audiences: ['th-daily-regulars', 'th-commuters'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'ooh', 'instagram', 'spotify'], geos: ['national'], budgetMultiplier: 1.60,
    plannedBudget: 12_800_000, revPerConvRange: [9, 26], cvrModifier: 1.00, cplCalibration: 0.60, revTrend: 0.0003 },
  { id: 'th-coldbev-summer', name: 'Local & Ontario-Grown — Summer Harvest Hero',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-cold-bev',
    audiences: ['th-cold-younger', 'th-families'], objective: 'awareness', status: 'live',
    channels: ['ctv', 'tiktok', 'instagram', 'ooh'], geos: ['national', 'ontario'], budgetMultiplier: 1.35,
    plannedBudget: 9_200_000, revPerConvRange: [8, 24], cvrModifier: 1.05, cplCalibration: 0.60, revTrend: 0.0004 },
  { id: 'th-breakfast-value', name: 'Meat & Deli — Weekly Family Value',
    enterprise: 'tim-hortons', division: 'tier-1', agency: 'th-zulu', productLine: 'th-breakfast',
    audiences: ['th-commuters', 'th-value-seekers'], objective: 'consideration', status: 'live',
    channels: ['ctv', 'facebook', 'google-search', 'spotify'], geos: ['national'], budgetMultiplier: 1.15,
    plannedBudget: 6_900_000, revPerConvRange: [10, 28], cvrModifier: 1.10, cplCalibration: 0.62, revTrend: 0.0003 },

  // ── TIER 2 — REGIONAL / MEDIA (Foodland Media) ──
  { id: 'th-rewards-acquisition', name: 'Scene+ Loyalty — Member Sign-Up Acquisition',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-rewards',
    audiences: ['th-app-members', 'th-daily-regulars'], objective: 'conversion', status: 'live',
    channels: ['tiktok', 'instagram', 'google-search', 'facebook'], geos: ['national'], budgetMultiplier: 1.25,
    plannedBudget: 7_600_000, revPerConvRange: [12, 32], cvrModifier: 1.25, cplCalibration: 0.68, revTrend: 0.0005 },
  { id: 'th-coldbrew-younger', name: 'Local & Ontario-Grown — Younger-Household Push',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-cold-bev',
    audiences: ['th-cold-younger'], objective: 'consideration', status: 'live',
    channels: ['tiktok', 'instagram', 'spotify'], geos: ['ontario', 'quebec'], budgetMultiplier: 0.90,
    plannedBudget: 4_400_000, revPerConvRange: [9, 25], cvrModifier: 1.15, cplCalibration: 0.64, revTrend: 0.0005 },
  { id: 'th-lunch-daypart', name: 'Centre-Store Grocery — Stock-Up Trip Expansion',
    enterprise: 'tim-hortons', division: 'tier-2', agency: 'th-touche', productLine: 'th-lunch',
    audiences: ['th-value-seekers', 'th-families'], objective: 'consideration', status: 'paused',
    channels: ['facebook', 'instagram', 'google-search'], geos: ['national'], budgetMultiplier: 0.80,
    plannedBudget: 3_600_000, revPerConvRange: [11, 30], cvrModifier: 1.00, cplCalibration: 0.60, revTrend: 0.0004 },

  // ── TIER 3 — LOCAL STORE MARKETING ──
  { id: 'th-baked-lto-local', name: 'Bakery — Local Fresh-Baked Daily Specials',
    enterprise: 'tim-hortons', division: 'tier-3', agency: 'th-local', productLine: 'th-baked',
    audiences: ['th-families', 'th-daily-regulars'], objective: 'conversion', status: 'live',
    channels: ['instagram', 'facebook', 'ooh'], geos: ['ontario', 'atlantic'], budgetMultiplier: 0.70,
    plannedBudget: 2_900_000, revPerConvRange: [8, 22], cvrModifier: 1.10, cplCalibration: 0.66, revTrend: 0.0004 },
  { id: 'th-rewards-winback-local', name: 'Scene+ Loyalty — Lapsed Shopper Win-Back',
    enterprise: 'tim-hortons', division: 'tier-3', agency: 'th-local', productLine: 'th-rewards',
    audiences: ['th-lapsed', 'th-value-seekers'], objective: 'retention', status: 'live',
    channels: ['facebook', 'google-search'], geos: ['national'], budgetMultiplier: 0.65,
    plannedBudget: 2_500_000, revPerConvRange: [10, 27], cvrModifier: 1.20, cplCalibration: 0.70, revTrend: 0.0005 },
];

export const TIM_HORTONS_NEWS: NewsItem[] = [
  { id: 'news-th-coldbrew-heatwave', title: 'Environment Canada Forecasts Hotter, Drier Summer — Local Produce Harvest Windows Expected to Shift Earlier',
    source: 'Environment Canada', date: '2026-05-07', tags: ['macro'], urgency: 'high', regions: ['national', 'ontario'],
    summary: 'Environment Canada\'s seasonal outlook points to a hotter, drier-than-average summer across much of Ontario, a known driver of earlier local produce harvest windows and stronger fresh-grocery demand.',
    whyItMatters: 'A weather signal landing as the Summer Harvest and Local & Ontario-Grown flights ramp. STRATIS is correlating temperature against fresh-produce baskets to pace weight to the harvest curve — see the linked recommendation.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-mcdonalds-coffee', title: "No Frills Launches Aggressive 'Hauler' Value Event in Small-Town Ontario",
    source: 'Canadian Grocer', date: '2026-05-05', tags: ['competitors', 'value'], urgency: 'high', competitor: "No Frills",
    regions: ['national'], summary: "No Frills rolled out an aggressive 'Hauler' price-drop value event with deep weekly specials and a PC Optimum points push aimed squarely at small-town and rural shoppers.",
    whyItMatters: 'A direct threat to value-seeking baskets in the towns Foodland anchors. STRATIS detected rising "No Frills flyer" and "cheapest groceries near me" search — reported as correlation; see the recommended measured defense.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-app-loyalty-data', title: 'Scene+ Penetration in Canadian Grocery Crosses 40% — Basket Lift Concentrated in Top Quintile',
    source: 'Caddle / Dalhousie Agri-Food Lab', date: '2026-05-01', tags: ['loyalty', 'macro'], urgency: 'high', regions: ['national'],
    summary: 'Grocery loyalty penetration crossed 40% nationally, with the largest basket-size and visit-frequency lift concentrated among the most engaged Scene+ members.',
    whyItMatters: 'Confirms that Scene+ members drive disproportionate basket value. STRATIS flags the Scene+ acquisition flight as the highest-leverage spend in the portfolio for compounding shopper frequency.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-coffee-futures', title: 'Wholesale Produce Costs Ease from Multi-Year Highs as Ontario Field Crops Firm',
    source: 'Statistics Canada', date: '2026-04-28', tags: ['macro', 'value'], urgency: 'medium', regions: ['national'],
    summary: 'Wholesale produce costs eased from multi-year highs on a strong Ontario field-crop outlook, relieving input-cost pressure across fresh grocery.',
    whyItMatters: 'A modest margin tailwind that supports value-led messaging on the weekly family basket. Tracked at the brand level; no reallocation required yet.',
    enterprises: ['tim-hortons'] },
  { id: 'news-th-nhl-sponsorship', title: 'Foodland Renews Community Minor-Hockey & Local Fair Sponsorships Ahead of Summer Season',
    source: 'Marketing Magazine', date: '2026-04-23', tags: ['sports', 'sponsorships', 'partnerships'], urgency: 'medium', regions: ['national'],
    summary: 'Foodland renewed its grassroots minor-hockey and small-town fall-fair sponsorships heading into the summer community-event window, reinforcing a core local brand-equity asset.',
    whyItMatters: 'A community brand-equity moment adjacent to the Fresh & Produce hero. STRATIS is correlating sponsorship salience against branded search; no media reallocation required.',
    enterprises: ['tim-hortons'] },
];

export const TIM_HORTONS_RADAR_PINS = ['news-th-coldbrew-heatwave', 'news-th-mcdonalds-coffee', 'news-th-app-loyalty-data'];

export const TIM_HORTONS_INSIGHTS: Insight[] = [
  {
    id: 'ins-th-01-rewards-leverage', createdAt: todayISO,
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'brand',
    channels: ['tiktok', 'instagram', 'google-search', 'facebook'],
    title: 'Scene+ Members Drive Disproportionate Basket Value — yet Loyalty Acquisition Gets Less Weight Than Any Single Category Hero',
    summary: 'Loyalty data now confirms Scene+ members shop more often and spend more per basket than non-members, and the lift compounds with engagement. But across the live portfolio, Scene+ acquisition receives less weight than any single category hero, so the highest-leverage spend in the business is under-funded relative to its downstream value. STRATIS holds per-member basket value against acquisition spend and finds the Scene+ flight materially under-invested. Re-weighting toward Scene+ acquisition buys compounding shopper frequency, not a one-time impression.',
    evidence: [
      'Scene+ members shop materially more often than non-members; lift compounds with engagement',
      'Scene+ acquisition receives less weight than any single category hero',
      'Per-member downstream basket value exceeds category-hero impression value',
      'The highest-leverage spend in the portfolio is the most under-funded',
    ],
    confidence: 0.86,
    impactEstimate: 'Re-weighting toward Scene+ acquisition converts one-time impressions into compounding shopper frequency across the member base.',
    recommendedAction: 'Increase Scene+ acquisition weight, funded from over-delivered category-hero impressions, to back the highest-leverage spend.',
    status: 'new',
    linkedNewsId: 'news-th-app-loyalty-data',
    actionSteps: [
      { id: 's1', title: 'Increase Scene+ acquisition weight', subtitle: 'HIGHEST-LEVERAGE SPEND', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered category heroes', subtitle: 'NO NET BUDGET ADD', type: 'budget', completed: false },
      { id: 's3', title: 'Track member frequency vs spend', subtitle: 'STRATIS MONITORS', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-02-mccafe-defense', createdAt: at(1, '08:30:00'),
    enterprise: 'tim-hortons', category: 'competitive-macro', scope: 'product', productLine: 'th-rewards',
    channels: ['google-search', 'tiktok', 'facebook'],
    title: "No Frills' 'Hauler' Value Event Is Lifting 'Cheapest Groceries Near Me' Search — Defend Value Baskets Before Shoppers Switch",
    summary: "After No Frills launched its aggressive 'Hauler' price-drop event, 'No Frills flyer' and 'cheapest groceries near me' comparison search rose in the small towns Foodland anchors, where value-seeking shoppers are most contested. Foodland's everyday-value and Scene+ offer is not currently surfaced in that comparison moment, and the message does not lead with the points-plus-price hook. A focused search defense and a matched value-forward message holds the local shopper before the switch hardens into habit — a measured counter, not a price war.",
    evidence: [
      "'No Frills flyer' and 'cheapest groceries near me' search rising since the Hauler event",
      'Lift concentrated in contested small-town and rural markets',
      'Foodland value + Scene+ offer is absent from the comparison moment',
      'Message does not lead with the points-plus-price hook',
    ],
    confidence: 0.83,
    impactEstimate: 'Defending comparison search and matching a value-forward message holds local value baskets before switching becomes habit.',
    recommendedAction: 'Expand defensive search on grocery-value comparison terms and lead the offer with a Scene+ points-plus-price hook.',
    status: 'new',
    linkedNewsId: 'news-th-mcdonalds-coffee',
    actionSteps: [
      { id: 's1', title: 'Defend grocery-value comparison search', subtitle: 'SMALL-TOWN MARKETS', type: 'bidding', completed: false },
      { id: 's2', title: 'Lead the offer with points-plus-price', subtitle: 'MATCH THE COMPETITIVE HOOK', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-03-heat-pacing', createdAt: at(2, '10:45:00'),
    enterprise: 'tim-hortons', category: 'national-regional', scope: 'product', productLine: 'th-cold-bev',
    channels: ['ctv', 'tiktok', 'instagram'],
    title: 'Local-Produce Baskets Track Temperature and Harvest — Pace the Summer Flights to the Harvest Curve, Not the Calendar',
    summary: 'Local & Ontario-grown produce baskets correlate tightly with daily high temperature and harvest readiness, and Environment Canada\'s outlook points to an early, hotter-than-average summer concentrated first in Ontario and Quebec. The Summer Harvest and Local & Ontario-Grown flights currently pace evenly on a calendar plan. Shifting to weather- and harvest-responsive pacing — front-loading the markets warming first — captures demand at its peak instead of after it, at the same total budget.',
    evidence: [
      'Local-produce baskets correlate with daily high temperature and harvest timing',
      'Hotter-than-average summer forecast, arriving earliest in ON & QC',
      'Summer flights pace evenly on a calendar plan',
      'Harvest-responsive pacing captures peak fresh-demand windows',
    ],
    confidence: 0.81,
    impactEstimate: 'Pacing to the harvest curve captures local-produce demand at its peak rather than after it, at no added budget.',
    recommendedAction: 'Switch the summer local-produce flights to harvest-responsive pacing, front-loading the markets warming first.',
    status: 'new',
    linkedNewsId: 'news-th-coldbrew-heatwave',
    actionSteps: [
      { id: 's1', title: 'Adopt harvest-responsive pacing', subtitle: 'HARVEST CURVE, NOT CALENDAR', type: 'scheduling', completed: false },
      { id: 's2', title: 'Front-load the earliest-warming markets', subtitle: 'ON + QC FIRST', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-04-daypart-overlap', createdAt: at(4, '13:30:00'),
    enterprise: 'tim-hortons', category: 'audience-overlap', scope: 'brand',
    channels: ['ctv', 'facebook', 'spotify'],
    title: 'Meat & Deli and Fresh & Produce Are Buying the Same Weekly Shopper in the Same Flyer Window — Combined Frequency Is Past Useful',
    summary: 'The Meat & Deli value flight and the Fresh & Produce hero both target the weekly family shopper in overlapping CTV and audio windows around the flyer drop, with no shared cap. Deduped, the weekly shopper sees both messages well past the point where the second one adds anything. Because they share an audience and a flyer window, a single coordinated weekly-basket message — or an enforced split where one owns awareness and the other owns the value offer — recovers wasted frequency and reads as one coherent weekly-shop story.',
    evidence: [
      'Meat & Deli and Fresh & Produce overlap on the weekly family shopper',
      'Shared CTV and audio windows around the flyer drop, no coordinated cap',
      'Combined weekly frequency is past the useful point',
      'No role split between awareness and value offer',
    ],
    confidence: 0.78,
    impactEstimate: 'Coordinating the weekly message recovers wasted frequency and presents one coherent weekly-shop story.',
    recommendedAction: 'Cap combined flyer-window frequency across the two flights and enforce an awareness-vs-offer role split.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Cap combined weekly frequency', subtitle: 'MEAT & DELI + PRODUCE', type: 'bidding', completed: false },
      { id: 's2', title: 'Split roles: awareness vs value offer', subtitle: 'ONE WEEKLY-SHOP STORY', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-05-creative-fatigue', createdAt: at(6, '09:15:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-cold-bev',
    channels: ['tiktok', 'instagram'],
    title: 'The Summer Harvest Local-Produce Cut Is Wearing Out on TikTok Before Peak Season Even Starts',
    summary: 'The Local & Ontario-Grown younger-household cut\'s completion and save rates on TikTok have slipped for two weeks while delivery climbed — early fatigue ahead of the peak harvest and highest-demand weeks. Burning the hero creative before peak season risks entering the demand surge with a tired asset. Rotating fresh short-form now, and reserving a creative refresh for the forecasted harvest peak, keeps the asset effective exactly when fresh-produce demand is highest.',
    evidence: [
      'TikTok completion and save rates down two consecutive weeks',
      'Delivery rose over the same window',
      'Fatigue is arriving before peak harvest weeks',
      'Risk of entering the harvest surge with a worn asset',
    ],
    confidence: 0.80,
    impactEstimate: 'Rotating fresh creative now preserves asset effectiveness into the peak harvest-demand window.',
    recommendedAction: 'Rotate fresh Local & Ontario-Grown short-form on TikTok now and hold a refresh for the forecasted harvest peak.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Rotate fresh short-form now', subtitle: 'TIKTOK LOCAL PRODUCE', type: 'creative', completed: false },
      { id: 's2', title: 'Reserve a refresh for the harvest peak', subtitle: 'PROTECT PEAK DEMAND', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-06-agency-arbitrage', createdAt: at(9, '11:45:00'),
    enterprise: 'tim-hortons', category: 'agency-arbitrage', scope: 'brand',
    channels: ['facebook', 'google-search', 'instagram'],
    title: 'Local Store Marketing Wins Lapsed Shoppers Back Cheaper Than the National Flight — the Local Offer Should Cascade Up',
    summary: 'The Tier 3 Local Store Marketing team recovers lapsed Scene+ shoppers at a lower cost-per-reactivation than national retention, because the offer is tied to a specific nearby Foodland store and locally relevant items. National Win-Back uses a generic offer. Cascading the local store-and-product offer mechanic into the national retention flight scales a proven reactivation efficiency rather than confining it to local activation.',
    evidence: [
      'Local Store Marketing cost-per-reactivation is below national retention',
      'Advantage traces to a nearby-store, locally relevant offer',
      'National Win-Back uses a generic offer',
      'The local mechanic is replicable nationally with geo targeting',
    ],
    confidence: 0.74,
    impactEstimate: 'Scaling the local store-and-product offer into the national flight lowers blended cost-per-reactivation.',
    recommendedAction: 'Adopt the Local Store Marketing store-and-product offer mechanic in the national Win-Back flight.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Codify the local offer mechanic', subtitle: 'STORE + PRODUCT TIED', type: 'targeting', completed: false },
      { id: 's2', title: 'Cascade into national Win-Back', subtitle: 'REPLACE GENERIC OFFER', type: 'creative', completed: false },
    ],
  },
  {
    id: 'ins-th-07-coldbev-channel', createdAt: at(3, '10:25:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-cold-bev',
    channels: ['ctv', 'tiktok', 'spotify', 'instagram'],
    title: 'Local-Produce Cost-per-Completed-View Is Lowest on TikTok yet Most Weight Sits in CTV',
    summary: "TikTok delivers a completed Local & Ontario-Grown view at roughly half CTV's cost, but CTV holds the majority of the local-produce video budget. A partial shift of completion-objective weight from CTV into TikTok buys more efficient views into the younger-household audience — without giving up CTV's broad reach role on the hero.",
    evidence: [
      "TikTok cost-per-completed-view is ~half of CTV's",
      'CTV holds the majority of local-produce video weight',
      'The younger-household audience over-indexes on TikTok',
      "A partial shift preserves CTV's reach role",
    ],
    confidence: 0.75,
    impactEstimate: 'Shifting completion-objective weight to TikTok buys more efficient completed views at the same budget.',
    recommendedAction: "Move a portion of local-produce completion weight from CTV to TikTok while holding CTV's reach role.",
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift completion weight CTV → TikTok', subtitle: 'CHEAPER COMPLETED VIEWS', type: 'budget', completed: false },
      { id: 's2', title: 'Hold CTV reach on the hero', subtitle: 'PARTIAL SHIFT ONLY', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-08-rewards-value', createdAt: at(8, '11:35:00'),
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'product', productLine: 'th-rewards',
    channels: ['tiktok', 'instagram', 'facebook', 'google-search'],
    title: 'Scene+ Members Carry ~3× the Basket Value of Non-Members but Acquisition Gets a Fraction of the Weight',
    summary: 'Scene+ members shop more often and spend more per basket — roughly three times the basket value of non-members — yet Scene+ acquisition receives a small share of portfolio weight next to the category heroes. Funding acquisition from over-delivered hero impressions compounds the member base that drives the most downstream value, rather than buying one-time reach.',
    evidence: [
      'Members carry ~3× the basket value of non-members',
      'Scene+ acquisition gets a fraction of portfolio weight',
      'Member value compounds with shopper frequency',
      'Hero impressions are over-delivered at current weight',
    ],
    confidence: 0.85,
    impactEstimate: 'Funding member acquisition from over-delivered hero weight compounds the highest-value cohort in the base.',
    recommendedAction: 'Shift a measured share of over-delivered hero impressions into Scene+ member acquisition.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Increase Scene+ acquisition weight', subtitle: 'COMPOUNDS MEMBER VALUE', type: 'budget', completed: false },
      { id: 's2', title: 'Fund from over-delivered heroes', subtitle: 'NO NET BUDGET ADD', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-09-lunch-incrementality', createdAt: at(2, '09:50:00'),
    enterprise: 'tim-hortons', category: 'strategic-opener', scope: 'product', productLine: 'th-lunch',
    channels: ['facebook', 'instagram', 'google-search'],
    title: 'The Paused Centre-Store Flight Was Driving Incremental Stock-Up Trips, Not Cannibalizing Fresh — Restarting It Is the Cleanest Growth Lever in the Portfolio',
    summary: 'The Centre-Store Grocery stock-up flight was paused on the assumption it pulled from the weekly fresh shop, but basket data shows its transactions clustered in the mid-week stock-up trip where Foodland runs nearly empty media. Across the portfolio, no other flight owns that mid-week trip, so the centre-store stock-up is additive rather than a shifted fresh shop. STRATIS sees this because it reads transaction timing against every other flight\'s delivery, not centre-store in isolation. Restarting Centre-Store at a measured weight buys incremental mid-week trips the rest of the portfolio cannot reach.',
    evidence: [
      'Paused on a cannibalization assumption never tested against timing data',
      'Centre-store transactions cluster in the mid-week media-light window',
      'No other live flight owns the mid-week stock-up trip',
      'Transaction timing shows additive trips, not shifted fresh shops',
    ],
    confidence: 0.82,
    impactEstimate: 'Restarting Centre-Store at measured weight captures incremental mid-week trips no other flight reaches.',
    recommendedAction: 'Restart the Centre-Store Grocery flight at a measured weight and hold it to the empty mid-week stock-up window.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Restart Centre-Store at measured weight', subtitle: 'INCREMENTAL, NOT CANNIBAL', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate delivery on mid-week', subtitle: 'OWN THE EMPTY WINDOW', type: 'scheduling', completed: false },
      { id: 's3', title: 'Hold incrementality readout', subtitle: 'STRATIS MONITORS TIMING', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-10-quebec-fit', createdAt: at(5, '10:10:00'),
    enterprise: 'tim-hortons', category: 'national-regional', scope: 'brand',
    channels: ['ctv', 'facebook', 'instagram'],
    title: 'The National Hero Creative Underperforms in Quebec — a French-First Cut Beats the Dubbed National Asset on Every Engagement Metric',
    summary: 'The national Fresh & Produce and Summer Harvest heroes run in Quebec as dubbed versions of the English master, and they trail their national average on completion, save, and offer click. The local-market cut built French-first — not translated — outperforms the dubbed asset across the board in Quebec delivery. STRATIS surfaces this because it compares Quebec performance against the same creative\'s national baseline rather than judging Quebec in isolation. Routing Quebec weight to a French-first cut recovers engagement the dubbed asset leaves on the table.',
    evidence: [
      'Dubbed national heroes trail national average on completion in Quebec',
      'French-first local cut outperforms the dubbed asset on save and click',
      'Gap is consistent across Fresh & Produce and Summer Harvest delivery',
      'Visible only when Quebec is held against the asset\'s national baseline',
    ],
    confidence: 0.79,
    impactEstimate: 'Routing Quebec to a French-first cut recovers engagement the dubbed asset forfeits.',
    recommendedAction: 'Replace dubbed hero delivery in Quebec with a French-first creative cut.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Promote the French-first cut in QC', subtitle: 'NOT A DUBBED MASTER', type: 'creative', completed: false },
      { id: 's2', title: 'Route Quebec weight to the local cut', subtitle: 'QC DELIVERY ONLY', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-11-family-bundle-crossshop', createdAt: at(3, '08:20:00'),
    enterprise: 'tim-hortons', category: 'audience-overlap', scope: 'brand',
    channels: ['facebook', 'instagram', 'ooh'],
    title: 'Families Buying Bakery Cross-Shop Centre-Store at High Rates — yet the Two Flights Target Them in Isolation With No Bundle Hand-Off',
    summary: 'The Bakery local flight and the paused Centre-Store flight both reach Rural Families, and basket data shows a family who buys a bakery special cross-shops centre-store grocery at a far higher rate than the base. But the two flights target Families independently, with no bundle message or sequencing between them. STRATIS sees the cross-shop because it joins baskets across categories for the same household, a link single-flight planning never makes. Sequencing a bakery-to-centre-store family bundle turns two isolated offers into one higher-value weekly basket.',
    evidence: [
      'Bakery family shoppers cross-shop Centre-Store above the base rate',
      'Bakery and Centre-Store both target Families independently',
      'No bundle message or offer sequencing between the flights',
      'Cross-shop visible only by joining baskets per household',
    ],
    confidence: 0.77,
    impactEstimate: 'Sequencing a family bundle turns two isolated offers into one higher-value weekly basket.',
    recommendedAction: 'Sequence a bakery-to-centre-store family bundle across the two flights that share the Families audience.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Sequence bakery → centre-store offer', subtitle: 'FAMILY BUNDLE', type: 'creative', completed: false },
      { id: 's2', title: 'Share the Families audience across flights', subtitle: 'ONE HOUSEHOLD VIEW', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-12-spotify-commute', createdAt: at(7, '08:55:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-breakfast',
    channels: ['spotify', 'ctv', 'facebook'],
    title: 'Spotify Drive-Home Audio Drives Meat & Deli Offer Clicks at a Fraction of CTV Cost — but Holds the Smallest Slice of the Flight',
    summary: 'On the Meat & Deli value flight, Spotify audio in the 4pm–6pm drive-home window delivers offer clicks at roughly a third of CTV\'s cost-per-click, because the message lands exactly when the "what\'s for dinner" decision is made on the way home. Yet Spotify holds the smallest share of the flight\'s weight while CTV carries the most. A measured shift of lower-funnel weight from CTV into drive-home audio buys more offer engagement at the same budget, while CTV keeps its broad awareness role.',
    evidence: [
      'Spotify drive-home cost-per-offer-click ~⅓ of CTV',
      'Audio lands at the moment the dinner decision is made',
      'Spotify holds the smallest weight share; CTV the largest',
      'A measured shift preserves CTV awareness reach',
    ],
    confidence: 0.76,
    impactEstimate: 'Shifting lower-funnel weight to drive-home audio buys more offer engagement at the same budget.',
    recommendedAction: 'Move a portion of Meat & Deli lower-funnel weight from CTV into Spotify drive-home audio.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Shift offer weight CTV → Spotify', subtitle: 'CHEAPER OFFER CLICKS', type: 'budget', completed: false },
      { id: 's2', title: 'Concentrate audio in the 4–6pm drive-home', subtitle: 'DECISION MOMENT', type: 'scheduling', completed: false },
    ],
  },
  {
    id: 'ins-th-13-baked-lto-spikes', createdAt: at(6, '12:40:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'product', productLine: 'th-baked',
    channels: ['instagram', 'facebook', 'ooh'],
    title: 'Fresh-Baked Daily Specials Spike Demand for ~72 Hours Then Decay — yet Bakery Weight Paces Flat Across the Whole Window',
    summary: 'Local fresh-baked daily specials sell hard in the first three days of each feature and decay sharply after, but the Bakery flight spends flat across the entire feature window. The back half of every feature buys impressions into demand that has already passed. STRATIS sees the decay curve because it reads basket velocity per feature, not aggregate bakery spend. Front-weighting each feature into its first 72 hours and trimming the tail concentrates spend where the spike actually is.',
    evidence: [
      'Fresh-baked specials sell in the first ~72 hours then decay',
      'Bakery weight paces flat across the full feature window',
      'Back-half spend buys impressions into demand already passed',
      'Decay curve visible only at per-feature basket velocity',
    ],
    confidence: 0.77,
    impactEstimate: 'Front-weighting each feature into its first 72 hours concentrates spend on the actual demand spike.',
    recommendedAction: 'Front-load bakery feature weight into the first 72 hours of each special and trim the decayed tail.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Front-load features into 72-hour spike', subtitle: 'MATCH THE DECAY CURVE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Trim the decayed tail spend', subtitle: 'DEMAND HAS PASSED', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-14-drive-thru-ooh', createdAt: at(10, '14:05:00'),
    enterprise: 'tim-hortons', category: 'tactical-efficiency', scope: 'brand',
    channels: ['ooh', 'instagram', 'facebook'],
    title: 'OOH Near Foodland Stores on Town Routes Converts Far Above Generic Boards — Proximity-Targeted Inventory Is Buried in a Flat National Buy',
    summary: 'OOH placements within a short drive of Foodland stores on main-street and town routes drive baskets at a multiple of generic high-reach boards, but the national OOH buy treats all inventory as interchangeable reach. The proximity signal — board to nearby store — is what converts, and it is currently diluted across placements with no nearby Foodland location. STRATIS reads board-level basket lift against store proximity, a join single-channel planning never makes. Re-weighting the buy toward proximity inventory lifts conversion at the same OOH spend.',
    evidence: [
      'Proximity boards convert at a multiple of generic high-reach boards',
      'National buy treats all OOH inventory as interchangeable reach',
      'Converting signal is board-to-nearby-store proximity',
      'Board basket lift joined to store proximity only at portfolio level',
    ],
    confidence: 0.74,
    impactEstimate: 'Re-weighting OOH toward proximity inventory lifts conversion at the same total OOH spend.',
    recommendedAction: 'Re-weight the OOH buy toward inventory within store proximity on town routes.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Prioritize store-proximity boards', subtitle: 'PROXIMITY IS THE SIGNAL', type: 'targeting', completed: false },
      { id: 's2', title: 'Trim generic non-proximity inventory', subtitle: 'SAME OOH BUDGET', type: 'budget', completed: false },
    ],
  },
  {
    id: 'ins-th-15-offer-ladder-wear', createdAt: at(11, '11:20:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-rewards',
    channels: ['tiktok', 'instagram', 'facebook'],
    title: 'The Scene+ Offer Creative Has Hit Frequency Saturation — Sign-Ups per Impression Are Falling While Reach Plateaus',
    summary: 'The Scene+ acquisition flight runs a single offer creative that has now saturated its core audience: sign-ups per impression are sliding while incremental reach flattens, the signature of frequency wear with no fresh audience left to find. The flight keeps spending against the same saturated pool. STRATIS sees saturation because it tracks sign-ups-per-impression against the reach curve, not raw sign-ups. Refreshing the offer creative and expanding into adjacent lookalikes restores efficiency the saturated buy is bleeding.',
    evidence: [
      'Sign-ups per impression falling as incremental reach flattens',
      'Single offer creative against a saturated core audience',
      'Classic frequency-wear signature, not a seasonal dip',
      'Visible only as sign-ups-per-impression vs the reach curve',
    ],
    confidence: 0.78,
    impactEstimate: 'Refreshing the offer creative and expanding lookalikes restores efficiency the saturated buy is losing.',
    recommendedAction: 'Refresh the Scene+ offer creative and expand the acquisition pool into adjacent lookalikes.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Refresh the Scene+ offer creative', subtitle: 'FREQUENCY SATURATED', type: 'creative', completed: false },
      { id: 's2', title: 'Expand into adjacent lookalikes', subtitle: 'FRESH AUDIENCE', type: 'targeting', completed: false },
    ],
  },
  {
    id: 'ins-th-16-nhl-branded-search', createdAt: at(13, '09:35:00'),
    enterprise: 'tim-hortons', category: 'competitive-macro', scope: 'brand',
    channels: ['google-search', 'ctv', 'spotify'],
    title: 'Community-Event Sponsorships Are Lifting Branded Foodland Search — but Search Capture Is Under-Funded for the Sponsorship-Driven Demand',
    summary: 'Branded "Foodland near me" and weekly-flyer search rises during community minor-hockey and fall-fair sponsorship windows, tracking local sponsorship salience rather than any media flight. The branded-search line is currently funded for baseline demand, so it under-captures the sponsorship-driven spikes and cedes the click to aggregators. STRATIS correlates sponsorship salience to branded search across the portfolio, a link the community/sponsorship teams and search buyers do not share. Pulsing branded-search capacity to the community-event schedule converts brand equity into measured visits.',
    evidence: [
      'Branded Foodland search rises in community-event windows',
      'Spikes track sponsorship salience, not any paid flight',
      'Branded search funded for baseline, under-captures the spikes',
      'Sponsorship-to-search correlation lives only at portfolio level',
    ],
    confidence: 0.75,
    impactEstimate: 'Pulsing branded-search capacity to the community-event schedule converts equity spikes into captured visits.',
    recommendedAction: 'Pulse branded-search budget to the community-event schedule to capture sponsorship-driven demand.',
    status: 'new',
    linkedNewsId: 'news-th-nhl-sponsorship',
    actionSteps: [
      { id: 's1', title: 'Pulse branded search to event windows', subtitle: 'CAPTURE THE SPIKE', type: 'scheduling', completed: false },
      { id: 's2', title: 'Lift caps on branded terms', subtitle: 'DON\'T CEDE THE CLICK', type: 'bidding', completed: false },
    ],
  },
  {
    id: 'ins-th-17-coldbrew-younger-growth', createdAt: at(14, '10:30:00'),
    enterprise: 'tim-hortons', category: 'creative-performance', scope: 'product', productLine: 'th-cold-bev',
    channels: ['tiktok', 'instagram', 'spotify'],
    title: 'Local & Ontario-Grown Is Growing the Younger-Household Shop While Fresh Staples Stay Flat — the Creative Should Lean Into the "Buy Local" Occasion',
    summary: 'Local & Ontario-grown produce baskets among younger households are growing fastest around the "buy local / support Ontario farms" occasion, a motivation the broader Fresh & Produce hero has never owned, while staple-produce frequency in the same cohort stays flat. The current Local & Ontario-Grown creative still frames the items as ordinary produce, missing the local-sourcing story that is actually driving its growth. STRATIS sees the emerging occasion because it reads local-produce basket timing against staple-produce in the same households. Re-cutting the creative around the buy-local occasion compounds the shop the portfolio is newly winning.',
    evidence: [
      'Local-produce growth among younger households concentrates around buy-local',
      'Staple-produce frequency in the same cohort stays flat',
      'Current creative frames the items as ordinary produce',
      'New buy-local occasion visible only against staple-produce timing',
    ],
    confidence: 0.79,
    impactEstimate: 'Re-cutting creative around the buy-local occasion compounds the shop the portfolio is newly winning.',
    recommendedAction: 'Re-cut the Local & Ontario-Grown creative around the buy-local occasion driving younger-household growth.',
    status: 'new',
    actionSteps: [
      { id: 's1', title: 'Re-cut creative for the buy-local occasion', subtitle: 'NOT ORDINARY PRODUCE', type: 'creative', completed: false },
      { id: 's2', title: 'Weight delivery to younger households', subtitle: 'BUY-LOCAL SHOPPERS', type: 'scheduling', completed: false },
    ],
  },
];

// ===== Per-insight charts (each illustrates its insight's specific headline) =====
export const TIM_HORTONS_VISUALS: Record<string, InsightVisual> = {
  'ins-th-01-rewards-leverage': {
    kind: 'bar', xKey: 'line', series: ['weight'], perBarColor: true,
    yTitle: 'Share of media weight (%)',
    config: { weight: { label: 'Media weight share' } },
    data: [
      { line: 'Fresh & Produce', weight: 26, fill: MUTED },
      { line: 'Local & Ont-Grown', weight: 20, fill: MUTED },
      { line: 'Meat & Deli', weight: 16, fill: MUTED },
      { line: 'Scene+ Loyalty', weight: 12, fill: RED },
    ],
    caption: 'Scene+ drives the most downstream frequency yet gets the least weight',
  },
  'ins-th-02-mccafe-defense': {
    kind: 'line', xKey: 'week', series: ['search'],
    yTitle: "'Cheapest groceries near me' search",
    config: { search: { label: 'Comparison search', color: RED } },
    data: [
      { week: 'W1', search: 100 }, { week: 'W2', search: 103 }, { week: 'W3', search: 107 },
      { week: 'W4', search: 129 }, { week: 'W5', search: 138 }, { week: 'W6', search: 134 },
    ],
    refLines: [{ axis: 'x', value: 'W3', label: 'No Frills Hauler event', color: GRID }],
    caption: 'Comparison search jumps after the Hauler event — defend value baskets',
  },
  'ins-th-03-heat-pacing': {
    kind: 'scatter', xKey: 'temp', series: ['redemption'],
    xName: 'Daily high (°C)', yName: 'Local-produce baskets (index)', perBarColor: true,
    config: { redemption: { label: 'Local-produce baskets' } },
    legend: [{ label: 'Daily observation', color: TEAL }],
    data: [
      { temp: 9, redemption: 72, fill: MUTED, name: 'Day' },
      { temp: 14, redemption: 88, fill: MUTED, name: 'Day' },
      { temp: 18, redemption: 104, fill: TEAL, name: 'Day' },
      { temp: 23, redemption: 126, fill: TEAL, name: 'Day' },
      { temp: 27, redemption: 145, fill: TEAL, name: 'Day' },
      { temp: 31, redemption: 168, fill: TEAL, name: 'Day' },
    ],
    caption: 'Each dot is a day — local-produce baskets track the daily high',
  },
  'ins-th-04-daypart-overlap': {
    kind: 'bar', xKey: 'flight', series: ['freq'], perBarColor: true,
    yTitle: 'Weekly frequency (shopper)',
    config: { freq: { label: 'Weekly frequency' } },
    data: [
      { flight: 'Meat & Deli', freq: 10, fill: MUTED },
      { flight: 'Fresh & Produce', freq: 9, fill: MUTED },
      { flight: 'Combined', freq: 19, fill: RED },
    ],
    refLines: [{ axis: 'y', value: 11, label: 'Effective max', color: TEAL }],
    caption: 'Two flights hit the same weekly shopper — combined frequency 19×',
  },
  'ins-th-05-creative-fatigue': {
    kind: 'line', xKey: 'week', series: ['save', 'spend'],
    yTitle: 'Indexed to 100',
    config: { save: { label: 'TikTok save rate', color: RED }, spend: { label: 'Spend', color: BLUE } },
    data: [
      { week: 'W1', save: 100, spend: 100 }, { week: 'W2', save: 97, spend: 106 },
      { week: 'W3', save: 92, spend: 111 }, { week: 'W4', save: 88, spend: 117 },
    ],
    caption: 'Save rate falls as spend climbs — wearing out before peak harvest',
  },
  'ins-th-06-agency-arbitrage': {
    kind: 'bar', xKey: 'team', series: ['cost'], perBarColor: true,
    yTitle: 'Cost per reactivation ($)',
    config: { cost: { label: 'Cost per reactivation' } },
    data: [
      { team: 'Local Store Mktg', cost: 6.4, fill: TEAL },
      { team: 'National Win-Back', cost: 9.8, fill: RED },
    ],
    caption: 'Local reactivation beats national — the store-product offer should scale',
  },
  'ins-th-07-coldbev-channel': {
    kind: 'bar', xKey: 'channel', series: ['cpv'], perBarColor: true,
    yTitle: 'Cost per completed view (¢)',
    config: { cpv: { label: 'Cost per completed view' } },
    data: [
      { channel: 'CTV', cpv: 4.8, fill: RED },
      { channel: 'Spotify', cpv: 3.6, fill: MUTED },
      { channel: 'Instagram', cpv: 3.1, fill: MUTED },
      { channel: 'TikTok', cpv: 2.4, fill: TEAL },
    ],
    caption: 'TikTok delivers the cheapest completed view — most weight sits in CTV',
  },
  'ins-th-08-rewards-value': {
    kind: 'bar', xKey: 'metric', series: ['member', 'nonmember'],
    yTitle: 'Indexed to non-member',
    config: { member: { label: 'Scene+ member', color: TEAL }, nonmember: { label: 'Non-member', color: MUTED } },
    data: [
      { metric: 'Basket value', member: 312, nonmember: 100 },
      { metric: 'Acquisition weight', member: 12, nonmember: 88 },
    ],
    caption: 'Members carry ~3× basket value but a fraction of acquisition weight',
  },
  'ins-th-09-lunch-incrementality': {
    kind: 'bar', xKey: 'window', series: ['visits'], perBarColor: true,
    yTitle: 'Centre-store transactions (index)',
    config: { visits: { label: 'Transactions by trip' } },
    data: [
      { window: 'Weekend fresh', visits: 14, fill: MUTED },
      { window: 'Mid-week stock-up', visits: 71, fill: TEAL },
      { window: 'Weeknight top-up', visits: 22, fill: MUTED },
      { window: 'Late evening', visits: 9, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 30, label: 'Other-flight coverage', color: RED }],
    caption: 'Centre-store transactions cluster in the empty mid-week stock-up trip',
  },
  'ins-th-10-quebec-fit': {
    kind: 'bar', xKey: 'metric', series: ['dubbed', 'french'],
    yTitle: 'Indexed to national average',
    config: { dubbed: { label: 'Dubbed national', color: MUTED }, french: { label: 'French-first cut', color: TEAL } },
    data: [
      { metric: 'Completion', dubbed: 86, french: 108 },
      { metric: 'Save rate', dubbed: 81, french: 114 },
      { metric: 'Offer click', dubbed: 78, french: 119 },
    ],
    caption: 'French-first cut beats the dubbed master across QC engagement',
  },
  'ins-th-11-family-bundle-crossshop': {
    kind: 'bar', xKey: 'group', series: ['lunch'], perBarColor: true,
    yTitle: 'Centre-store cross-shop rate (%)',
    config: { lunch: { label: 'Cross-shops Centre-Store' } },
    data: [
      { group: 'Bakery family shoppers', lunch: 41, fill: TEAL },
      { group: 'All families', lunch: 23, fill: MUTED },
      { group: 'Non-family base', lunch: 14, fill: MUTED },
    ],
    refLines: [{ axis: 'y', value: 23, label: 'Base family rate', color: RED }],
    caption: 'Bakery family shoppers cross-shop Centre-Store far above the base',
  },
  'ins-th-12-spotify-commute': {
    kind: 'bar', xKey: 'channel', series: ['cpc'], perBarColor: true,
    yTitle: 'Cost per offer click ($)',
    config: { cpc: { label: 'Cost per offer click' } },
    data: [
      { channel: 'CTV', cpc: 2.7, fill: RED },
      { channel: 'Facebook', cpc: 1.5, fill: MUTED },
      { channel: 'Spotify (4–6pm)', cpc: 0.9, fill: TEAL },
    ],
    caption: 'Drive-home audio drives the cheapest Meat & Deli offer click',
  },
  'ins-th-13-baked-lto-spikes': {
    kind: 'line', xKey: 'day', series: ['redemption', 'spend'],
    yTitle: 'Indexed to feature launch',
    config: { redemption: { label: 'Basket velocity', color: TEAL }, spend: { label: 'Flat spend pacing', color: RED } },
    data: [
      { day: 'D1', redemption: 100, spend: 100 }, { day: 'D2', redemption: 92, spend: 100 },
      { day: 'D3', redemption: 74, spend: 100 }, { day: 'D4', redemption: 41, spend: 100 },
      { day: 'D5', redemption: 28, spend: 100 }, { day: 'D6', redemption: 19, spend: 100 },
    ],
    refLines: [{ axis: 'x', value: 'D3', label: '72-hour spike', color: GRID }],
    caption: 'Demand decays after 72 hours while bakery spend stays flat',
  },
  'ins-th-14-drive-thru-ooh': {
    kind: 'bar', xKey: 'inventory', series: ['conv'], perBarColor: true,
    yTitle: 'Basket lift per board (index)',
    config: { conv: { label: 'Basket lift per board' } },
    data: [
      { inventory: 'Store proximity', conv: 184, fill: TEAL },
      { inventory: 'Town route', conv: 121, fill: BLUE },
      { inventory: 'Generic high-reach', conv: 100, fill: MUTED },
    ],
    caption: 'Proximity boards convert far above generic high-reach inventory',
  },
  'ins-th-15-offer-ladder-wear': {
    kind: 'line', xKey: 'week', series: ['rpi', 'reach'],
    yTitle: 'Indexed to 100',
    config: { rpi: { label: 'Sign-ups / impression', color: RED }, reach: { label: 'Incremental reach', color: BLUE } },
    data: [
      { week: 'W1', rpi: 100, reach: 100 }, { week: 'W2', rpi: 96, reach: 112 },
      { week: 'W3', rpi: 89, reach: 119 }, { week: 'W4', rpi: 81, reach: 122 },
      { week: 'W5', rpi: 73, reach: 123 },
    ],
    caption: 'Sign-ups per impression fall as reach plateaus — frequency wear',
  },
  'ins-th-16-nhl-branded-search': {
    kind: 'line', xKey: 'night', series: ['search', 'capture'],
    yTitle: 'Branded search (index)',
    config: { search: { label: 'Branded search demand', color: PURPLE }, capture: { label: 'Funded capture', color: MUTED } },
    data: [
      { night: 'Base 1', search: 100, capture: 98 }, { night: 'Base 2', search: 108, capture: 101 },
      { night: 'Event 1', search: 152, capture: 104 }, { night: 'Event 2', search: 171, capture: 106 },
      { night: 'Event 3', search: 164, capture: 103 },
    ],
    refLines: [{ axis: 'x', value: 'Event 1', label: 'Community-event peak', color: GRID }],
    caption: 'Community-event nights spike branded search past funded capture',
  },
  'ins-th-17-coldbrew-younger-growth': {
    kind: 'pie', nameKey: 'daypart', valueKey: 'growth', series: ['growth'],
    config: { growth: { label: 'Local-produce growth share' } },
    legend: [
      { label: 'Buy-local', color: TEAL },
      { label: 'Staple produce', color: MUTED },
      { label: 'Seasonal one-off', color: BLUE },
    ],
    data: [
      { daypart: 'Buy-local', growth: 58, fill: TEAL },
      { daypart: 'Staple produce', growth: 27, fill: MUTED },
      { daypart: 'Seasonal one-off', growth: 15, fill: BLUE },
    ],
    caption: 'Younger-household local-produce growth concentrates around buy-local',
  },
};
